[package]
name = "plugins"
version.workspace = true
edition.workspace = true

[lib]
name = "plugins"
path = "src/lib.rs"

[features]
cli = [
    "dep:clap",
    "dep:colored",
]
[dependencies]
orca-dispatch        = { path = "../orca-dispatch" }
orca-contract    = { path = "../orca-contract", default-features = false }
orca-macro       = { path = "../orca-macro" }
schemars         = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
inventory        = { workspace = true }

orca-utils = { path = "../utils" }
orca-db = { package = "orca-db", path = "../db" }
anyhow = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
clap        = { workspace = true,         optional = true }
colored     = { workspace = true,         optional = true }
rusqlite = { workspace = true }
toml = { workspace = true }
reqwest = { workspace = true, features = ["blocking"] }
orca-sdk = { path = "../sdk/rust" }
fleet = { path = "../fleet" }
uuid = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
rustls-pki-types = { workspace = true }
tokio-rustls = { workspace = true }
tracing = { workspace = true }
serde_yaml = { workspace = true }
sha2 = { workspace = true }
hex = { version = "0.4" }
base64 = { version = "0.22" }
jsonschema = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
