[package]
name    = "orca-graphql"
version = "0.1.0"
edition.workspace = true

[lib]
name = "orca_graphql"
path = "src/lib.rs"

[dependencies]
anyhow     = { workspace = true }
orca-http  = { path = "../http" }
serde      = { workspace = true }
serde_json = { workspace = true }
thiserror  = { workspace = true }

[dev-dependencies]
tokio    = { workspace = true }
wiremock = "0.6"
