[workspace]
members = [
    "projects/agents",
    "projects/auth",
    "projects/commands",
    "projects/db",
    "projects/core",
    "projects/fs",
    "projects/ledger",
    "projects/log",
    "projects/docs",
    "projects/jobs",
    "projects/scanner",
    "projects/server",
    "projects/utils",
]
resolver = "2"

[profile.release]
opt-level = 3
lto = "thin"
strip = true

[profile.dev]
opt-level = 0
