//! Lidarr orca plugin. Thin tool surface over the shared `arr` base library.
//!
//! Tool surface (one-tool-per-resource):
//!
//! - `lidarr.{list, detail, create, update, delete}` — endpoint registry CRUD,
//!   generated by `endpoint_resource!` from the toolkit.
//! - `lidarr.health` — **detection.** Health issues from `/api/v1/health`.
//! - `lidarr.indexers` — configured indexers from `/api/v1/indexer`.
//! - `lidarr.test_indexers` — **remediation.** Re-test every indexer.
//! - `lidarr.system_status` — app name / version / instance.
//!
//! Lidarr speaks `/api/v1` with a `/artist` media model; the [`arr::Flavor`] is
//! fixed to `Lidarr`, so the endpoint row carries no `flavor` column.
//!
//! Endpoint resolution: tools accept the endpoint *name* and load
//! `(base_url, api_key)` from the toolkit-generated `endpoint_db` at call time.
//! Per [[project-colocated-api-clients]] + model B (any creds-holder may
//! execute), the row syncs to every paired peer.
//!
//! Imports flow through `plugin_toolkit::prelude::*` only — the plugin treats
//! the toolkit as the single gateway to the orca system.
#![allow(clippy::disallowed_types)]

use plugin_toolkit::prelude::*;

use arr::{Client, Config, Flavor, HealthIssue, Indexer, IndexerTestResult, SystemStatus};

// ═══════════════════════════════════════════════════════════════════════════
// lidarr.{list,detail,create,update,delete} — endpoint registry CRUD.
// One declaration → five tools, three transports each, schema fragment, db
// helpers, row struct, args/output types. Power scales with the macro.
// ═══════════════════════════════════════════════════════════════════════════

#[endpoint_resource(plugin = "lidarr")]
pub struct LidarrEndpoint {
    pub name: String,
    #[secret]
    pub api_key: String,
}

// ── HTTP client helper ──────────────────────────────────────────────────────

/// Resolve a registered Lidarr endpoint to a live [`Client`], picking the
/// first reachable address from the endpoint's fallback list.
async fn make_client(name: &str) -> Result<Client> {
    let row = {
        let conn = runtime::open_db()?;
        endpoint_db::get(&conn, name)?
            .with_context(|| format!("lidarr endpoint '{name}' not registered"))?
    };
    if !row.enabled {
        bail!("lidarr endpoint '{name}' is disabled");
    }
    let base_url = address::resolve_reachable(name, &row.addresses).await?;
    Ok(Client::new(Config::new(
        base_url,
        row.api_key,
        Flavor::Lidarr,
    )))
}

// ═══════════════════════════════════════════════════════════════════════════
// lidarr.health — DETECTION
// ═══════════════════════════════════════════════════════════════════════════

#[derive(clap::Args, Serialize, Deserialize, JsonSchema)]
pub struct LidarrHealthArgs {
    /// Registered endpoint name.
    pub endpoint: String,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct LidarrHealthOutput {
    /// Total health issues raised.
    pub issue_count: usize,
    /// Health issues from `/health`.
    pub issues: Vec<HealthIssue>,
}

/// **Detection.** Health issues currently raised by a registered Lidarr server.
#[orca_tool(domain = "lidarr", verb = "health")]
async fn lidarr_health(args: LidarrHealthArgs, _ctx: &ToolCtx) -> Result<LidarrHealthOutput> {
    let issues = arr::ops::health(&make_client(&args.endpoint).await?).await?;
    Ok(LidarrHealthOutput {
        issue_count: issues.len(),
        issues,
    })
}

// ═══════════════════════════════════════════════════════════════════════════
// lidarr.indexers — configured indexers
// ═══════════════════════════════════════════════════════════════════════════

#[derive(clap::Args, Serialize, Deserialize, JsonSchema)]
pub struct LidarrIndexersArgs {
    /// Registered endpoint name.
    pub endpoint: String,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct LidarrIndexersOutput {
    /// Configured indexers from `/indexer`.
    pub indexers: Vec<Indexer>,
}

/// Configured indexers on a registered Lidarr server.
#[orca_tool(domain = "lidarr", verb = "indexers")]
async fn lidarr_indexers(args: LidarrIndexersArgs, _ctx: &ToolCtx) -> Result<LidarrIndexersOutput> {
    let indexers = arr::ops::indexers(&make_client(&args.endpoint).await?).await?;
    Ok(LidarrIndexersOutput { indexers })
}

// ═══════════════════════════════════════════════════════════════════════════
// lidarr.test_indexers — REMEDIATION
// ═══════════════════════════════════════════════════════════════════════════

#[derive(clap::Args, Serialize, Deserialize, JsonSchema)]
pub struct LidarrTestIndexersArgs {
    /// Registered endpoint name.
    pub endpoint: String,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct LidarrTestIndexersOutput {
    /// Indexers tested.
    pub tested_count: usize,
    /// Indexers that passed.
    pub valid_count: usize,
    /// Per-indexer result.
    pub results: Vec<IndexerTestResult>,
}

/// **Remediation.** Re-test every indexer on a registered Lidarr server,
/// clearing stale backoff so recovered indexers are used again immediately.
#[orca_tool(domain = "lidarr", verb = "test_indexers")]
async fn lidarr_test_indexers(
    args: LidarrTestIndexersArgs,
    _ctx: &ToolCtx,
) -> Result<LidarrTestIndexersOutput> {
    let results = arr::ops::test_indexers(&make_client(&args.endpoint).await?).await?;
    let valid_count = results
        .iter()
        .filter(|r| r.is_valid.unwrap_or(false))
        .count();
    Ok(LidarrTestIndexersOutput {
        tested_count: results.len(),
        valid_count,
        results,
    })
}

// ═══════════════════════════════════════════════════════════════════════════
// lidarr.system_status — app name + version
// ═══════════════════════════════════════════════════════════════════════════

#[derive(clap::Args, Serialize, Deserialize, JsonSchema)]
pub struct LidarrSystemStatusArgs {
    /// Registered endpoint name.
    pub endpoint: String,
}

/// App name, version, and instance name from `/system/status`.
#[orca_tool(domain = "lidarr", verb = "system_status")]
async fn lidarr_system_status(
    args: LidarrSystemStatusArgs,
    _ctx: &ToolCtx,
) -> Result<SystemStatus> {
    Ok(arr::ops::system_status(&make_client(&args.endpoint).await?).await?)
}

// TODO: lidarr.add_artist — Lidarr-specific media tool over `/api/v1/artist`.
