[package]
name = "docker"
version.workspace = true
edition.workspace = true

[lib]
name = "docker"
path = "src/lib.rs"

[dependencies]
plugin-toolkit = { path = "../../plugin-toolkit" }
macro-runtime = { path = "../../macro-runtime" }
anyhow      = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
thiserror   = { workspace = true }
tokio       = { workspace = true }

dispatch        = { path = "../../dispatch" }
contract    = { path = "../../contract", default-features = false }
derive       = { path = "../../derive" }
schemars         = { workspace = true }
inventory        = { workspace = true }

db = { package = "db", path = "../../db" }
async-trait = { workspace = true }
clap        = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
