[package]
name = "mcp"
version.workspace = true
edition.workspace = true

[lib]
name = "mcp"
path = "src/lib.rs"

[features]
cli = [
    "dep:clap",
]
[dependencies]
orca-dispatch    = { path = "../orca-dispatch" }
orca-contract   = { path = "../orca-contract", default-features = false }
orca-macro      = { path = "../orca-macro" }
platform        = { path = "../platform", default-features = false }
scanner         = { path = "../scanner" }
schemars        = { workspace = true }
serde           = { workspace = true }
serde_json      = { workspace = true }
inventory       = { workspace = true }

orca-utils = { path = "../utils" }
db = { package = "orca-db", path = "../db" }
anyhow = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
dirs = { workspace = true }
futures-util = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }
clap          = { workspace = true,         optional = true }
chrono        = { workspace = true }

[lints]
workspace = true
