[package]
name = "docs"
version.workspace = true
edition.workspace = true

[lib]
name = "docs"
path = "src/lib.rs"

[features]
default = []
native = [
    "orca-contract/native",
    "dep:orca-utils",
    "dep:db",
    "dep:anyhow",
    "dep:async-trait",
    "dep:tokio",
    "dep:chrono",

]
cli = [
    "native",
    "dep:clap",
    "dep:colored",
]

[dependencies]
orca-dispatch        = { path = "../orca-dispatch" }
orca-contract    = { path = "../orca-contract", default-features = false }
orca-macro       = { path = "../orca-macro" }
schemars         = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
inventory        = { workspace = true }

orca-utils  = { path = "../utils",        optional = true }
db          = { package = "orca-db", path = "../db", optional = true }
anyhow      = { workspace = true,         optional = true }
async-trait = { workspace = true,         optional = true }
tokio       = { workspace = true,         optional = true }
chrono      = { workspace = true,         optional = true }
clap        = { workspace = true,         optional = true }
colored     = { workspace = true,         optional = true }
rust-embed  = { workspace = true }

[lints]
workspace = true
