[package]
name = "orca-commands"
version = "0.1.0"
edition.workspace = true

[dependencies]
orca-agents  = { path = "../agents" }
orca-scanner = { path = "../scanner", features = ["php-ast"] }
config       = { package = "orca-config", path = "../config" }
db           = { package = "orca-db", path = "../db" }
orca_fs      = { package = "orca-fs", path = "../fs" }
state        = { package = "orca-state", path = "../state" }

anyhow = "1"
clap = { version = "4", features = ["derive"] }
colored = "3"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.13", default-features = false, features = ["json", "stream", "rustls", "blocking", "form"] }
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
toml = "1"
sha2 = "0.10"
rusqlite = { version = "0.39", features = ["bundled-sqlcipher"] }
rand = "0.9"
regex = "1"
base64 = "0.22"
url = "2"

[dev-dependencies]
tempfile = "3"
