[package]
name = "orca-jobs"
version = "0.1.0"
edition = "2024"

[dependencies]
orca-core  = { path = "../core" }
orca-utils = { path = "../utils" }
config     = { package = "orca-config", path = "../config" }
types      = { package = "orca-types", path = "../types" }
anyhow = "1"
colored = "2"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
