[package]
name = "orca-jobs"
version = "0.1.0"
edition = "2024"

[dependencies]
orca-core  = { path = "../core" }
llm        = { package = "orca-llm",    path = "../llm" }
config     = { package = "orca-config", path = "../config" }
tool       = { package = "orca-tool",   path = "../tool" }
anyhow = "1"
colored = "2"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
