[package]
name = "plugins"
version.workspace = true
edition.workspace = true

[lib]
name = "plugins"
path = "src/lib.rs"

[dependencies]
plugin-toolkit = { path = "../plugin-toolkit" }
contract    = { path = "../contract", default-features = false }
derive       = { path = "../derive" }
schemars         = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }

files    = { path = "../files" }
db = { package = "db", path = "../db" }
anyhow = { workspace = true }
clap        = { workspace = true }
rusqlite = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
