[package]
name = "orca-core"
version = "0.1.0"
edition = "2024"

[dependencies]
orca_fs    = { package = "orca-fs",  path = "../fs" }
config     = { package = "orca-config", path = "../config" }
tool       = { package = "orca-tool",   path = "../tool" }
llm        = { package = "orca-llm",    path = "../llm" }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
colored = "2"
