[package]
name = "mcp"
version.workspace = true
edition.workspace = true

[lib]
name = "mcp"
path = "src/lib.rs"

[dependencies]
dispatch    = { path = "../../dispatch" }
contract   = { path = "../../contract", default-features = false }
derive      = { path = "../../derive" }
schemars        = { workspace = true }
serde           = { workspace = true }
serde_json      = { workspace = true }
inventory       = { workspace = true }

utils = { path = "../../utils" }
db = { package = "db", path = "../../db" }
anyhow = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
dirs = { workspace = true }
futures-util = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }
clap          = { workspace = true }
chrono        = { workspace = true }

[lints]
workspace = true
