#!/usr/bin/env bash
# Trailer / attribution guard.
#
# Blocks any tool call whose payload tries to slip an authorship-attribution or
# "generated by an assistant" trailer into a commit, PR, issue, or file. This
# is the ONLY backstop for `gh pr create` / `gh issue create`: gh bypasses
# git's own commit-msg hooks, so attribution has to be caught here, at the
# tool-call layer, before it ever leaves the machine.
#
# History: an earlier version matched only the narrow author-line variant, so a
# robot-emoji "Generated with <assistant>" credit plus its attribution link
# leaked into a PR body. This version blocks the whole family of trailers.
#
# Exit 2 = blocking error; stderr is shown to Claude. Exit 0 = allow.
set -euo pipefail

payload=$(cat)

# Allow maintenance of the guard itself and its test fixtures — otherwise the
# patterns below (which necessarily contain the very tokens they match) would
# make this file impossible to edit.
self_path=$(printf '%s' "$payload" | jq -r '.tool_input.file_path // empty')
case "$self_path" in
  */hooks/block-coauthor.sh|*/hooks/tests/trailer-guard/*) exit 0 ;;
esac

# Pull every field an attribution string could hide in:
#   Bash:       .tool_input.command   (git commit -m, gh pr create --body, heredocs)
#   Write:      .tool_input.content
#   Edit:       .tool_input.new_string / .old_string
#   MultiEdit:  .tool_input.edits[].new_string
haystack=$(printf '%s' "$payload" | jq -r '
  [
    .tool_input.command // empty,
    .tool_input.content // empty,
    .tool_input.new_string // empty,
    .tool_input.old_string // empty,
    ( .tool_input.edits // [] | map(.new_string // empty) | join("\n") )
  ] | join("\n")
')

# Each entry is a case-insensitive ERE. Anchored to an assistant/vendor token
# where possible so legitimate prose ("stub generated with protoc") is not
# tripped. Bare "claude" is intentionally allowed: this repo references Claude
# model IDs and the claude.ai MCP server.
patterns=(
  # Author-credit trailers, any spelling/spacing (covers the no-separator form).
  'co[-_ ]?authored([-_ ]?by)?'
  # "Generated/Assisted/Written/Created/Made with|by <assistant>".
  '(generated|assisted|authored|written|created|made)[-_ ]?(with|by)[^\n]{0,40}(claude|anthropic|chatgpt|openai|copilot|gpt|gemini|\bll?m\b|\bai\b|assistant|cursor|codex)'
  # The attribution links + robot emoji assistants ship with.
  '🤖'
  'claude\.com/claude-code'
  'claude\.ai/(code|chat)'
  'anthropic\.com/(claude|claude-code)'
  # Author-credit email address form.
  'noreply@anthropic\.com'
  # Generic "<Key>-by:" trailer keys at line start.
  '^(co[-_ ]?authored[-_ ]?by|generated[-_ ]?by|assisted[-_ ]?by|created[-_ ]?by)[[:space:]]*:'
)

for pat in "${patterns[@]}"; do
  if printf '%s' "$haystack" | grep -Eiq "$pat"; then
    {
      echo "Blocked: payload contains an authorship/attribution trailer."
      echo "Matched pattern: /$pat/i"
      echo "User forbids ANY assistant-attribution trailer in commits, PRs, issues, or files."
      echo "Strip the credit line (author trailer, 'Generated with ...', robot emoji, attribution links) and retry."
    } >&2
    exit 2
  fi
done

exit 0
