// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  AgentBackendDetailData,
  AgentBackendDetailErrors,
  AgentBackendDetailResponses,
  AgentBackendUpdateData,
  AgentBackendUpdateErrors,
  AgentBackendUpdateResponses,
  AgentGetData,
  AgentGetErrors,
  AgentGetResponses,
  AgentListData,
  AgentListErrors,
  AgentListResponses,
  AgentRunData,
  AgentRunErrors,
  AgentRunResponses,
  AuthChangePasswordData,
  AuthChangePasswordErrors,
  AuthChangePasswordResponses,
  AuthLoginData,
  AuthLoginErrors,
  AuthLoginResponses,
  AuthLogoutData,
  AuthLogoutErrors,
  AuthLogoutResponses,
  AuthMeData,
  AuthMeErrors,
  AuthMeResponses,
  AuthSessionCreateData,
  AuthSessionCreateErrors,
  AuthSessionCreateResponses,
  AuthSessionDeleteData,
  AuthSessionDeleteErrors,
  AuthSessionDeleteResponses,
  AuthSessionDetailData,
  AuthSessionDetailErrors,
  AuthSessionDetailResponses,
  AuthSigninData,
  AuthSigninErrors,
  AuthSigninResponses,
  AuthSignoutData,
  AuthSignoutResponses,
  AuthSignupData,
  AuthSignupErrors,
  AuthSignupResponses,
  AuthSignupStatusData,
  AuthSignupStatusResponses,
  AuthTokenCreateData,
  AuthTokenCreateErrors,
  AuthTokenCreateResponses,
  AuthTokenDeleteData,
  AuthTokenDeleteErrors,
  AuthTokenDeleteResponses,
  AuthTokenListData,
  AuthTokenListErrors,
  AuthTokenListResponses,
  ConfigDeleteData,
  ConfigDeleteErrors,
  ConfigDeleteResponses,
  ConfigGetData,
  ConfigGetErrors,
  ConfigGetResponses,
  ConfigListData,
  ConfigListErrors,
  ConfigListResponses,
  ConfigSetData,
  ConfigSetErrors,
  ConfigSetResponses,
  DbDetailData,
  DbDetailErrors,
  DbDetailResponses,
  DbUpdateData,
  DbUpdateErrors,
  DbUpdateResponses,
  DockerDeleteData,
  DockerDeleteErrors,
  DockerDeleteResponses,
  DockerDetailData,
  DockerDetailErrors,
  DockerDetailResponses,
  DockerListData,
  DockerListErrors,
  DockerListResponses,
  DockerUpdateData,
  DockerUpdateErrors,
  DockerUpdateResponses,
  FilesDeleteData,
  FilesDeleteErrors,
  FilesDeleteResponses,
  FilesListData,
  FilesListErrors,
  FilesListResponses,
  FilesReadData,
  FilesReadErrors,
  FilesReadResponses,
  FilesSearchData,
  FilesSearchErrors,
  FilesSearchResponses,
  FilesStatData,
  FilesStatErrors,
  FilesStatResponses,
  FilesTreeData,
  FilesTreeErrors,
  FilesTreeResponses,
  FilesUpdateData,
  FilesUpdateErrors,
  FilesUpdateResponses,
  McpDeleteData,
  McpDeleteErrors,
  McpDeleteResponses,
  McpDetailData,
  McpDetailErrors,
  McpDetailResponses,
  McpListData,
  McpListErrors,
  McpListResponses,
  McpRunData,
  McpRunErrors,
  McpRunResponses,
  McpUpdateData,
  McpUpdateErrors,
  McpUpdateResponses,
  NamespaceAccessCreateData,
  NamespaceAccessCreateErrors,
  NamespaceAccessCreateResponses,
  NamespaceAccessDeleteData,
  NamespaceAccessDeleteErrors,
  NamespaceAccessDeleteResponses,
  NamespaceAccessListData,
  NamespaceAccessListErrors,
  NamespaceAccessListResponses,
  NamespaceCreateData,
  NamespaceCreateErrors,
  NamespaceCreateResponses,
  NamespaceDeleteData,
  NamespaceDeleteErrors,
  NamespaceDeleteResponses,
  NamespaceDetailData,
  NamespaceDetailErrors,
  NamespaceDetailResponses,
  NamespaceListData,
  NamespaceListErrors,
  NamespaceListResponses,
  NamespaceUseData,
  NamespaceUseErrors,
  NamespaceUseResponses,
  PkiCreateData,
  PkiCreateErrors,
  PkiCreateResponses,
  PkiListData,
  PkiListErrors,
  PkiListResponses,
  PluginDeleteData,
  PluginDeleteErrors,
  PluginDeleteResponses,
  PluginDetailData,
  PluginDetailErrors,
  PluginDetailResponses,
  PluginListData,
  PluginListErrors,
  PluginListResponses,
  PluginUpdateData,
  PluginUpdateErrors,
  PluginUpdateResponses,
  PodDetailData,
  PodDetailErrors,
  PodDetailResponses,
  PodForgetData,
  PodForgetErrors,
  PodForgetResponses,
  PodHistoryData,
  PodHistoryErrors,
  PodHistoryResponses,
  PodJoinData,
  PodJoinErrors,
  PodJoinResponses,
  PodKickData,
  PodKickErrors,
  PodKickResponses,
  PodLeaveData,
  PodLeaveErrors,
  PodLeaveResponses,
  PodListData,
  PodListErrors,
  PodListResponses,
  PodPingData,
  PodPingErrors,
  PodPingResponses,
  PodRecoverData,
  PodRecoverErrors,
  PodRecoverResponses,
  PodSyncData,
  PodSyncErrors,
  PodSyncResponses,
  PodTrustData,
  PodTrustErrors,
  PodTrustResponses,
  PodUpdateData,
  PodUpdateErrors,
  PodUpdateResponses,
  ScheduleListData,
  ScheduleListErrors,
  ScheduleListResponses,
  ScheduleRunData,
  ScheduleRunErrors,
  ScheduleRunResponses,
  ScheduleStatusData,
  ScheduleStatusErrors,
  ScheduleStatusResponses,
  SecretsDeleteData,
  SecretsDeleteErrors,
  SecretsDeleteResponses,
  SecretsDetailData,
  SecretsDetailErrors,
  SecretsDetailResponses,
  SecretsListData,
  SecretsListErrors,
  SecretsListResponses,
  SecretsSetData,
  SecretsSetErrors,
  SecretsSetResponses,
  SpecDetailData,
  SpecDetailErrors,
  SpecDetailResponses,
  SystemBuildData,
  SystemBuildErrors,
  SystemBuildResponses,
  SystemDeleteData,
  SystemDeleteErrors,
  SystemDeleteResponses,
  SystemDetailData,
  SystemDetailErrors,
  SystemDetailResponses,
  SystemInstallData,
  SystemInstallErrors,
  SystemInstallResponses,
  SystemKillData,
  SystemKillErrors,
  SystemKillResponses,
  SystemServeReleaseData,
  SystemServeReleaseErrors,
  SystemServeReleaseResponses,
  SystemUpdateData,
  SystemUpdateErrors,
  SystemUpdateResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const authChangePassword = <ThrowOnError extends boolean = false>(
  options: Options<AuthChangePasswordData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AuthChangePasswordResponses,
    AuthChangePasswordErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/auth/web/change_password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const authMe = <ThrowOnError extends boolean = false>(
  options?: Options<AuthMeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<AuthMeResponses, AuthMeErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/auth/web/me',
    ...options,
  });

export const authSignin = <ThrowOnError extends boolean = false>(
  options: Options<AuthSigninData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthSigninResponses, AuthSigninErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/auth/web/signin',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const authSignout = <ThrowOnError extends boolean = false>(
  options?: Options<AuthSignoutData, ThrowOnError>,
) =>
  (options?.client ?? client).post<AuthSignoutResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/auth/web/signout',
    ...options,
  });

export const authSignup = <ThrowOnError extends boolean = false>(
  options: Options<AuthSignupData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthSignupResponses, AuthSignupErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/auth/web/signup',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const authSignupStatus = <ThrowOnError extends boolean = false>(
  options?: Options<AuthSignupStatusData, ThrowOnError>,
) =>
  (options?.client ?? client).get<AuthSignupStatusResponses, unknown, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/auth/web/signup_status',
    ...options,
  });

/**
 * agent.backend.detail
 *
 * Show the current agent backend configuration.
 */
export const agentBackendDetail = <ThrowOnError extends boolean = false>(
  options: Options<AgentBackendDetailData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AgentBackendDetailResponses,
    AgentBackendDetailErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/agent.backend.detail',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * agent.backend.update
 *
 * agent_backend_update
 */
export const agentBackendUpdate = <ThrowOnError extends boolean = false>(
  options: Options<AgentBackendUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AgentBackendUpdateResponses,
    AgentBackendUpdateErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/agent.backend.update',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * agent.get
 *
 * Return the full system prompt for a named orca agent.
 */
export const agentGet = <ThrowOnError extends boolean = false>(
  options: Options<AgentGetData, ThrowOnError>,
) =>
  (options.client ?? client).post<AgentGetResponses, AgentGetErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/agent.get',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * agent.list
 *
 * List all available orca agents with their names and descriptions.
 */
export const agentList = <ThrowOnError extends boolean = false>(
  options: Options<AgentListData, ThrowOnError>,
) =>
  (options.client ?? client).post<AgentListResponses, AgentListErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/agent.list',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * agent.run
 *
 * Delegate a task to an orca agent. Backend (local LLM / server-side Anthropic / Claude Code delegation) is selected by `system.agent.backend.detail`. Prefer deterministic tools (read_doc, search_docs, list_services, etc.) over this — only use when the task genuinely needs language model reasoning.
 */
export const agentRun = <ThrowOnError extends boolean = false>(
  options: Options<AgentRunData, ThrowOnError>,
) =>
  (options.client ?? client).post<AgentRunResponses, AgentRunErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/agent.run',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * auth.login
 *
 * Authenticate the operator on THIS host and persist a CLI session at `$ORCA_HOME/session` (mode 0600). Replaces the legacy `first_admin` ambient-identity fallback on CLI + MCP-stdio.
 */
export const authLogin = <ThrowOnError extends boolean = false>(
  options: Options<AuthLoginData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthLoginResponses, AuthLoginErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/auth.login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * auth.logout
 *
 * Revoke the on-disk CLI session and remove `$ORCA_HOME/session`. Idempotent — `revoked=false` means there was no active session to clear.
 */
export const authLogout = <ThrowOnError extends boolean = false>(
  options: Options<AuthLogoutData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthLogoutResponses, AuthLogoutErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/auth.logout',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * auth.session.create
 *
 * Authenticate with a provider. Anthropic: pass `key`. GitHub: device-flow. Atlassian: PKCE.
 */
export const authSessionCreate = <ThrowOnError extends boolean = false>(
  options: Options<AuthSessionCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AuthSessionCreateResponses,
    AuthSessionCreateErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/auth.session.create',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * auth.session.delete
 *
 * Remove a stored credential. `removed=false` if nothing was stored.
 */
export const authSessionDelete = <ThrowOnError extends boolean = false>(
  options: Options<AuthSessionDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AuthSessionDeleteResponses,
    AuthSessionDeleteErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/auth.session.delete',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * auth.session.detail
 *
 * Snapshot every configured credential the host knows about (Anthropic key + OAuth tokens).
 */
export const authSessionDetail = <ThrowOnError extends boolean = false>(
  options: Options<AuthSessionDetailData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    AuthSessionDetailResponses,
    AuthSessionDetailErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/auth.session.detail',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * auth.token.create
 *
 * Mint a new REST/MCP bearer token on THIS host. Plaintext is returned exactly once and cannot be recovered from the DB. Token only authenticates calls to this host's `:12000` — not to other peers.
 */
export const authTokenCreate = <ThrowOnError extends boolean = false>(
  options: Options<AuthTokenCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthTokenCreateResponses, AuthTokenCreateErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/auth.token.create',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * auth.token.delete
 *
 * Revoke a token by id. Returns `revoked=false` if the id wasn't found.
 */
export const authTokenDelete = <ThrowOnError extends boolean = false>(
  options: Options<AuthTokenDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthTokenDeleteResponses, AuthTokenDeleteErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/auth.token.delete',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * auth.token.list
 *
 * List all REST/MCP bearer tokens registered on this host. Token hashes are not returned.
 */
export const authTokenList = <ThrowOnError extends boolean = false>(
  options: Options<AuthTokenListData, ThrowOnError>,
) =>
  (options.client ?? client).post<AuthTokenListResponses, AuthTokenListErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/auth.token.list',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * config.delete
 *
 * Delete a config row owned by the local host.
 */
export const configDelete = <ThrowOnError extends boolean = false>(
  options: Options<ConfigDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).post<ConfigDeleteResponses, ConfigDeleteErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/config.delete',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * config.get
 *
 * Fetch a single config row by noun+name.
 */
export const configGet = <ThrowOnError extends boolean = false>(
  options: Options<ConfigGetData, ThrowOnError>,
) =>
  (options.client ?? client).post<ConfigGetResponses, ConfigGetErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/config.get',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * config.list
 *
 * List config rows. Optionally filter by noun and/or host_owner.
 */
export const configList = <ThrowOnError extends boolean = false>(
  options: Options<ConfigListData, ThrowOnError>,
) =>
  (options.client ?? client).post<ConfigListResponses, ConfigListErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/config.list',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * config.set
 *
 * Upsert a config row. Refuses to write rows owned by a different host — cross-host writes route via the pod mesh once peer-tool dispatch lands (§3.3).
 */
export const configSet = <ThrowOnError extends boolean = false>(
  options: Options<ConfigSetData, ThrowOnError>,
) =>
  (options.client ?? client).post<ConfigSetResponses, ConfigSetErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/config.set',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * db.detail
 *
 * Show current schema version and pending-migration count.
 */
export const dbDetail = <ThrowOnError extends boolean = false>(
  options: Options<DbDetailData, ThrowOnError>,
) =>
  (options.client ?? client).post<DbDetailResponses, DbDetailErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/db.detail',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * db.update
 *
 * Drive the migration runner. `action`: - `migrate`: apply all pending migrations. - `up`: apply the next pending migration (one step). - `down`: revert the most recently applied migration (one step).
 */
export const dbUpdate = <ThrowOnError extends boolean = false>(
  options: Options<DbUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).post<DbUpdateResponses, DbUpdateErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/db.update',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * docker.delete
 *
 * docker_delete
 */
export const dockerDelete = <ThrowOnError extends boolean = false>(
  options: Options<DockerDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).post<DockerDeleteResponses, DockerDeleteErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/docker.delete',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * docker.detail
 *
 * docker_detail
 */
export const dockerDetail = <ThrowOnError extends boolean = false>(
  options: Options<DockerDetailData, ThrowOnError>,
) =>
  (options.client ?? client).post<DockerDetailResponses, DockerDetailErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/docker.detail',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * docker.list
 *
 * List docker resources on this host: local engine status + registered runtimes always; plus compose services for `path` or a project scan for `root`.
 */
export const dockerList = <ThrowOnError extends boolean = false>(
  options: Options<DockerListData, ThrowOnError>,
) =>
  (options.client ?? client).post<DockerListResponses, DockerListErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/docker.list',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * docker.update
 *
 * Combine any of: start the local engine, register a docker runtime, run a compose action. Args determine which sub-operations fire.
 */
export const dockerUpdate = <ThrowOnError extends boolean = false>(
  options: Options<DockerUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).post<DockerUpdateResponses, DockerUpdateErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/docker.update',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * files.delete
 *
 * Combine any of: delete a file (`path`), unregister a root (`unregister_root`), remove a global ignore pattern (`remove_ignore_pattern`).
 */
export const filesDelete = <ThrowOnError extends boolean = false>(
  options: Options<FilesDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).post<FilesDeleteResponses, FilesDeleteErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/files.delete',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * files.list
 *
 * List filesystem resources. No args → registered roots + global ignore patterns. With `path` (and optional `root`) → directory contents at that path.
 */
export const filesList = <ThrowOnError extends boolean = false>(
  options: Options<FilesListData, ThrowOnError>,
) =>
  (options.client ?? client).post<FilesListResponses, FilesListErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/files.list',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * files.read
 *
 * Read a text file. `format="llm"` strips decorative markdown; binary/multi-format reads are deferred to v2.
 */
export const filesRead = <ThrowOnError extends boolean = false>(
  options: Options<FilesReadData, ThrowOnError>,
) =>
  (options.client ?? client).post<FilesReadResponses, FilesReadErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/files.read',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * files.search
 *
 * Case-insensitive line search across one or all registered roots. Returns hits only — LLM summarisation surface dropped 2026-05-29; callers can format hits themselves.
 */
export const filesSearch = <ThrowOnError extends boolean = false>(
  options: Options<FilesSearchData, ThrowOnError>,
) =>
  (options.client ?? client).post<FilesSearchResponses, FilesSearchErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/files.search',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * files.stat
 *
 * Metadata for a single path — kind (file/dir), byte size, existence flag.
 */
export const filesStat = <ThrowOnError extends boolean = false>(
  options: Options<FilesStatData, ThrowOnError>,
) =>
  (options.client ?? client).post<FilesStatResponses, FilesStatErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/files.stat',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * files.tree
 *
 * Recursive directory tree. Compacted by default; pass `raw=true` for the unmodified filesystem layout.
 */
export const filesTree = <ThrowOnError extends boolean = false>(
  options: Options<FilesTreeData, ThrowOnError>,
) =>
  (options.client ?? client).post<FilesTreeResponses, FilesTreeErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/files.tree',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * files.update
 *
 * Combine any of: write a file (`path` + `content`), register/update a root (`register_root_*`), add a global ignore pattern (`add_ignore_pattern`).
 */
export const filesUpdate = <ThrowOnError extends boolean = false>(
  options: Options<FilesUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).post<FilesUpdateResponses, FilesUpdateErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/files.update',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * mcp.delete
 *
 * mcp_delete
 */
export const mcpDelete = <ThrowOnError extends boolean = false>(
  options: Options<McpDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).post<McpDeleteResponses, McpDeleteErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/mcp.delete',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * mcp.detail
 *
 * mcp_detail
 */
export const mcpDetail = <ThrowOnError extends boolean = false>(
  options: Options<McpDetailData, ThrowOnError>,
) =>
  (options.client ?? client).post<McpDetailResponses, McpDetailErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/mcp.detail',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * mcp.list
 *
 * List every registered MCP server with its tool mappings nested.
 */
export const mcpList = <ThrowOnError extends boolean = false>(
  options: Options<McpListData, ThrowOnError>,
) =>
  (options.client ?? client).post<McpListResponses, McpListErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/mcp.list',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * mcp.run
 *
 * Invoke a tool on a registered MCP server. Returns the typed `tools/call` envelope.
 */
export const mcpRun = <ThrowOnError extends boolean = false>(
  options: Options<McpRunData, ThrowOnError>,
) =>
  (options.client ?? client).post<McpRunResponses, McpRunErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/mcp.run',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * mcp.update
 *
 * Register/update a server, add or remove a tool mapping, and/or run a tool sync. Multiple sub-operations can be combined.
 */
export const mcpUpdate = <ThrowOnError extends boolean = false>(
  options: Options<McpUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).post<McpUpdateResponses, McpUpdateErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/mcp.update',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * namespace.access.create
 *
 * Grant another user access to a namespace.  `role` is `viewer` (read-only) or `collaborator` (read/write). The word "share" is intentionally avoided here because orca reserves `share.*` for filesystem-protocol shares (smb/nfs/s3). Granting another principal access to a namespace is an access-control change, not a share.
 */
export const namespaceAccessCreate = <ThrowOnError extends boolean = false>(
  options: Options<NamespaceAccessCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    NamespaceAccessCreateResponses,
    NamespaceAccessCreateErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/namespace.access.create',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * namespace.access.delete
 *
 * Revoke a user's access to a namespace.
 */
export const namespaceAccessDelete = <ThrowOnError extends boolean = false>(
  options: Options<NamespaceAccessDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    NamespaceAccessDeleteResponses,
    NamespaceAccessDeleteErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/namespace.access.delete',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * namespace.access.list
 *
 * List the access grants on a namespace (owner only).
 */
export const namespaceAccessList = <ThrowOnError extends boolean = false>(
  options: Options<NamespaceAccessListData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    NamespaceAccessListResponses,
    NamespaceAccessListErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/namespace.access.list',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * namespace.create
 *
 * Create a new namespace owned by the current user.
 */
export const namespaceCreate = <ThrowOnError extends boolean = false>(
  options: Options<NamespaceCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<NamespaceCreateResponses, NamespaceCreateErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/namespace.create',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * namespace.delete
 *
 * Delete a namespace (owner only).
 */
export const namespaceDelete = <ThrowOnError extends boolean = false>(
  options: Options<NamespaceDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).post<NamespaceDeleteResponses, NamespaceDeleteErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/namespace.delete',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * namespace.detail
 *
 * Show details of a namespace (defaults to the active one).
 */
export const namespaceDetail = <ThrowOnError extends boolean = false>(
  options: Options<NamespaceDetailData, ThrowOnError>,
) =>
  (options.client ?? client).post<NamespaceDetailResponses, NamespaceDetailErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/namespace.detail',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * namespace.list
 *
 * List all namespaces the current user can access (owned + shared).
 */
export const namespaceList = <ThrowOnError extends boolean = false>(
  options: Options<NamespaceListData, ThrowOnError>,
) =>
  (options.client ?? client).post<NamespaceListResponses, NamespaceListErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/namespace.list',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * namespace.use
 *
 * Set the active namespace for the current user.
 */
export const namespaceUse = <ThrowOnError extends boolean = false>(
  options: Options<NamespaceUseData, ThrowOnError>,
) =>
  (options.client ?? client).post<NamespaceUseResponses, NamespaceUseErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/namespace.use',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * pki.create
 *
 * Initialize orca PKI (CA + server cert) or issue a plugin cert. `kind=ca` is safe to re-run; `kind=cert` requires `plugin_id`.
 */
export const pkiCreate = <ThrowOnError extends boolean = false>(
  options: Options<PkiCreateData, ThrowOnError>,
) =>
  (options.client ?? client).post<PkiCreateResponses, PkiCreateErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/pki.create',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * pki.list
 *
 * List all issued plugin certs.
 */
export const pkiList = <ThrowOnError extends boolean = false>(
  options: Options<PkiListData, ThrowOnError>,
) =>
  (options.client ?? client).post<PkiListResponses, PkiListErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/pki.list',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * plugin.delete
 *
 * plugin_delete
 */
export const pluginDelete = <ThrowOnError extends boolean = false>(
  options: Options<PluginDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).post<PluginDeleteResponses, PluginDeleteErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/plugin.delete',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * plugin.detail
 *
 * plugin_detail
 */
export const pluginDetail = <ThrowOnError extends boolean = false>(
  options: Options<PluginDetailData, ThrowOnError>,
) =>
  (options.client ?? client).post<PluginDetailResponses, PluginDetailErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/plugin.detail',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * plugin.list
 *
 * plugin_list
 */
export const pluginList = <ThrowOnError extends boolean = false>(
  options: Options<PluginListData, ThrowOnError>,
) =>
  (options.client ?? client).post<PluginListResponses, PluginListErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/plugin.list',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * plugin.update
 *
 * Install a plugin (`manifest`), toggle enabled (`id` + `enabled`), set/sync credentials, or set data — combine in one call.
 */
export const pluginUpdate = <ThrowOnError extends boolean = false>(
  options: Options<PluginUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).post<PluginUpdateResponses, PluginUpdateErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/plugin.update',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * pod.detail
 *
 * Days-remaining + rotation state for every mesh cert on this host, plus the current `self_secure` (Tier-2 secrets-storage) setting.
 */
export const podDetail = <ThrowOnError extends boolean = false>(
  options: Options<PodDetailData, ThrowOnError>,
) =>
  (options.client ?? client).post<PodDetailResponses, PodDetailErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/pod.detail',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * pod.forget
 *
 * Forget a stale/orphan peer_id mesh-wide: hard-delete it here AND fan a one-way notice to every live member so they drop it too. Use for orphans left by machine_id churn or decommissioned hosts — NOT for evicting a live peer (that's `pod kick`).
 */
export const podForget = <ThrowOnError extends boolean = false>(
  options: Options<PodForgetData, ThrowOnError>,
) =>
  (options.client ?? client).post<PodForgetResponses, PodForgetErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/pod.forget',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * pod.history
 *
 * Snapshot history for one peer, newest-first. Both the UI (timeseries) and the sync puller (watermarked pull) use this. Latest-per-peer is already on `pod.list` (each member row enriches its `system` field from the same `host_status` table), so no separate list verb exists.
 */
export const podHistory = <ThrowOnError extends boolean = false>(
  options: Options<PodHistoryData, ThrowOnError>,
) =>
  (options.client ?? client).post<PodHistoryResponses, PodHistoryErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/pod.history',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * pod.join
 *
 * Initiate or complete a pod-membership pairing.  `action`: - `"invite"` — inviter pushes an offer to a discovered joiner. Requires `addr` (joiner's host or host:port from mDNS discovery). Returns a pairing code to show the operator; the joiner auto-accepts if its daemon received the code in-band. - `"join"` — joiner requests an offer from an inviter not yet in mDNS. Requires `addr` (inviter's host or host:port). Returns the code the inviter will display. - `"accept"` — joiner accepts a pending inbound offer by its 6-char code. Requires `code`. Returns the inviter identity after join.
 */
export const podJoin = <ThrowOnError extends boolean = false>(
  options: Options<PodJoinData, ThrowOnError>,
) =>
  (options.client ?? client).post<PodJoinResponses, PodJoinErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/pod.join',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * pod.kick
 *
 * Evict a paired peer: best-effort notify, then drop `pod_peers` + `pod_trust` rows for it. Mirrors today's `system.peer.delete` semantics.
 */
export const podKick = <ThrowOnError extends boolean = false>(
  options: Options<PodKickData, ThrowOnError>,
) =>
  (options.client ?? client).post<PodKickResponses, PodKickErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/pod.kick',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * pod.leave
 *
 * Voluntary pod exit: notify every paired peer we're leaving (best-effort), then drop all `pod_peers` + `pod_trust` rows on this host. PKI material is left in place — call `system bootstrap` to fully reset.
 */
export const podLeave = <ThrowOnError extends boolean = false>(
  options: Options<PodLeaveData, ThrowOnError>,
) =>
  (options.client ?? client).post<PodLeaveResponses, PodLeaveErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/pod.leave',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * pod.list
 *
 * Unified pod-membership view: joined members + in-flight handshakes + mDNS-discovered candidates, each row tagged by `state`. Replaces the trio of `system.peer.list`, `system.peer.discovery.list`, and `system.peer.handshake.list` (2026-05-28 consolidation).
 */
export const podList = <ThrowOnError extends boolean = false>(
  options: Options<PodListData, ThrowOnError>,
) =>
  (options.client ?? client).post<PodListResponses, PodListErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/pod.list',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * pod.ping
 *
 * mTLS ping a paired peer; returns latency + their self-reported identity. Kept distinct from `system.detail --peer <id>` because ping latency is a *relationship* measurement between this host and the peer, not a property of the peer itself.
 */
export const podPing = <ThrowOnError extends boolean = false>(
  options: Options<PodPingData, ThrowOnError>,
) =>
  (options.client ?? client).post<PodPingResponses, PodPingErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/pod.ping',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * pod.recover
 *
 * Clear a stale `departed_at` flag for a peer on THIS host. Recovery tool for the 2026-05-28 kick/peer-leaving bug (and any future false-depart). No network call — purely local row repair.
 */
export const podRecover = <ThrowOnError extends boolean = false>(
  options: Options<PodRecoverData, ThrowOnError>,
) =>
  (options.client ?? client).post<PodRecoverResponses, PodRecoverErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/pod.recover',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * pod.sync
 *
 * Force a one-shot replication tick on this host (or — with `peer_id` set — on the named remote peer via the universal peer-dispatch path) and return a per-source-peer report. Replaces "wait 60s for the background tick to fire and hope it worked." `peer` arg optionally filters which source peer we pull from (hostname / peer_id / addr) — omit to pull from every paired peer. Admin: this is operator-facing and can surface mesh errors.
 */
export const podSync = <ThrowOnError extends boolean = false>(
  options: Options<PodSyncData, ThrowOnError>,
) =>
  (options.client ?? client).post<PodSyncResponses, PodSyncErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/pod.sync',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * pod.trust
 *
 * Set trust for a paired peer. Without `push`, mutates OUR local trust (`local_secure`). With `push: true`, executes on the remote peer over mTLS so THEY trust US (`peer_secure` from our perspective).
 */
export const podTrust = <ThrowOnError extends boolean = false>(
  options: Options<PodTrustData, ThrowOnError>,
) =>
  (options.client ?? client).post<PodTrustResponses, PodTrustErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/pod.trust',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * pod.update
 *
 * Update pod-level settings on this host or — when `peer_id` is set — on the named remote peer over the pod mesh. Currently exposes `self_secure` (Tier-2 secrets-storage permission). Admin-only because flipping it can authorize secrets replication into this host.
 */
export const podUpdate = <ThrowOnError extends boolean = false>(
  options: Options<PodUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).post<PodUpdateResponses, PodUpdateErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/pod.update',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * schedule.list
 *
 * List schedule rows with their next firing time.
 */
export const scheduleList = <ThrowOnError extends boolean = false>(
  options: Options<ScheduleListData, ThrowOnError>,
) =>
  (options.client ?? client).post<ScheduleListResponses, ScheduleListErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/schedule.list',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * schedule.run
 *
 * Invoke a scheduled job immediately, out-of-band from the loop. Useful for testing schedule wiring without waiting for the next firing.
 */
export const scheduleRun = <ThrowOnError extends boolean = false>(
  options: Options<ScheduleRunData, ThrowOnError>,
) =>
  (options.client ?? client).post<ScheduleRunResponses, ScheduleRunErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/schedule.run',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * schedule.status
 *
 * Show per-job last-run status from the scheduler_runs history.
 */
export const scheduleStatus = <ThrowOnError extends boolean = false>(
  options: Options<ScheduleStatusData, ThrowOnError>,
) =>
  (options.client ?? client).post<ScheduleStatusResponses, ScheduleStatusErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/schedule.status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * secrets.delete
 *
 * Remove a secret. The inline value is zeroed; for external backends only the orca registration is removed (the upstream vault is untouched).
 */
export const secretsDelete = <ThrowOnError extends boolean = false>(
  options: Options<SecretsDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).post<SecretsDeleteResponses, SecretsDeleteErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/secrets.delete',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * secrets.detail
 *
 * [SENSITIVE] Fetch a secret value by name. Resolves via the configured backend.
 */
export const secretsDetail = <ThrowOnError extends boolean = false>(
  options: Options<SecretsDetailData, ThrowOnError>,
) =>
  (options.client ?? client).post<SecretsDetailResponses, SecretsDetailErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/secrets.detail',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * secrets.list
 *
 * List configured secrets (names + backends + metadata). Never returns values.
 */
export const secretsList = <ThrowOnError extends boolean = false>(
  options: Options<SecretsListData, ThrowOnError>,
) =>
  (options.client ?? client).post<SecretsListResponses, SecretsListErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/secrets.list',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * secrets.set
 *
 * Create or update a secret. For 'inline' backend, `value` is required; for external backends, `ref_path` is required (e.g. 'op://Vault/Item/field'). Write the secret on a remote system with the top-level `--peer <h>` flag.
 */
export const secretsSet = <ThrowOnError extends boolean = false>(
  options: Options<SecretsSetData, ThrowOnError>,
) =>
  (options.client ?? client).post<SecretsSetResponses, SecretsSetErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/secrets.set',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * spec.detail
 *
 * Dump orca's own OpenAPI JSON document. Used by build pipelines that don't want to spin up the HTTP server.
 */
export const specDetail = <ThrowOnError extends boolean = false>(
  options: Options<SpecDetailData, ThrowOnError>,
) =>
  (options.client ?? client).post<SpecDetailResponses, SpecDetailErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/spec.detail',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * system.build
 *
 * Build a distributable package (deb/rpm/apk/PKGBUILD/pkg/homebrew) from the current orca binary. Format auto-detected from host OS when not provided. Postinst scripts delegate to `system install --service-user orca` (which absorbed the old `system.bootstrap` + supervisor-install responsibilities).
 */
export const systemBuild = <ThrowOnError extends boolean = false>(
  options: Options<SystemBuildData, ThrowOnError>,
) =>
  (options.client ?? client).post<SystemBuildResponses, SystemBuildErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/system.build',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * system.delete
 *
 * Uninstall orca from this host: remove binary, MCP registration, CLAUDE.md symlinks, AND the daemon supervisor unit (launchd / systemd / openrc / unraid). Absorbed the former `system.daemon.uninstall`.
 */
export const systemDelete = <ThrowOnError extends boolean = false>(
  options: Options<SystemDeleteData, ThrowOnError>,
) =>
  (options.client ?? client).post<SystemDeleteResponses, SystemDeleteErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/system.delete',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * system.detail
 *
 * Snapshot of orca's installation: binary, ~/.claude/CLAUDE.md, vault dir, agents symlink, PKI init, MCP registration.
 */
export const systemDetail = <ThrowOnError extends boolean = false>(
  options: Options<SystemDetailData, ThrowOnError>,
) =>
  (options.client ?? client).post<SystemDetailResponses, SystemDetailErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/system.detail',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * system.install
 *
 * Install orca on this host. Always wires the user-level install (binary, ~/.claude symlinks, MCP registration, PKI). When `service_user` is set, also bootstraps a system service user with SSH access — replaces the former separate `system.bootstrap` tool.
 */
export const systemInstall = <ThrowOnError extends boolean = false>(
  options: Options<SystemInstallData, ThrowOnError>,
) =>
  (options.client ?? client).post<SystemInstallResponses, SystemInstallErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/system.install',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * system.kill
 *
 * Kill stale orca runtime processes (mcp-serve, daemon start) so a binary swap is picked up by their clients on next call. Safe to run before any deploy; no-op when nothing matches.
 */
export const systemKill = <ThrowOnError extends boolean = false>(
  options: Options<SystemKillData, ThrowOnError>,
) =>
  (options.client ?? client).post<SystemKillResponses, SystemKillErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/system.kill',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * system.serve_release
 *
 * Serve a release asset from GitHub on behalf of a peer that lacks the `github_token` secret. Resolves the token locally, downloads the asset for the requested `target`, verifies sha256 against the release checksum blob, and returns the bytes base64-encoded.
 */
export const systemServeRelease = <ThrowOnError extends boolean = false>(
  options: Options<SystemServeReleaseData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    SystemServeReleaseResponses,
    SystemServeReleaseErrors,
    ThrowOnError
  >({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/system.serve_release',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * system.update
 *
 * The single system-update tool. Covers orca binary updates, host identity (hostname/fqdn/addressing), and OS package upgrades. Omit every arg for a read-only state probe.
 */
export const systemUpdate = <ThrowOnError extends boolean = false>(
  options: Options<SystemUpdateData, ThrowOnError>,
) =>
  (options.client ?? client).post<SystemUpdateResponses, SystemUpdateErrors, ThrowOnError>({
    security: [
      {
        in: 'cookie',
        name: 'orca_session',
        type: 'apiKey',
      },
    ],
    url: '/api/v1/system.update',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
