// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

export type AuthErrorResponse = {
  error: string;
};

export type ComponentStatus = {
  installed: boolean;
  path: string;
};

export type ConfluenceSearchQuery = {
  cql?: string | null;
  limit?: number | null;
};

export type CredInfo = {
  key: string;
  synced: boolean;
  updatedAt: string;
};

export type Ctx7Response = {
  content: string;
  libraryId: string;
  title: string;
  topic?: string | null;
};

export type DockerActionRequest = {
  action: string;
  projectPath: string;
  service?: string | null;
  tail?: number | null;
};

export type DockerActionResponse = {
  composeFile?: string | null;
  output: string;
};

export type DockerRuntimeAddRequest = {
  host?: string | null;
  name: string;
  socketPath?: string | null;
  /**
   * HTTP URL for web-based orchestrators (Dockge, Portainer)
   */
  url?: string | null;
};

export type DockerRuntimeInfo = {
  enabled: boolean;
  host?: string | null;
  name: string;
  socketPath?: string | null;
  /**
   * HTTP URL for web-based orchestrators (Dockge, Portainer)
   */
  url?: string | null;
};

export type DockerService = {
  health: string;
  name: string;
  ports: Array<string>;
  running: boolean;
  state: string;
};

export type DockerServicesResponse = {
  composeFile?: string | null;
  services: Array<DockerService>;
};

export type ErrorResponse = {
  error: string;
};

export type FsBrowseResponse = {
  entries: Array<FsEntry>;
  /**
   * Parent directory path (absent when at root).
   */
  parent?: string | null;
  /**
   * Resolved absolute path that was listed.
   */
  path: string;
  /**
   * Whether unrestricted browsing is currently enabled in orca.db.
   */
  unrestrictedEnabled: boolean;
};

export type FsEntry = {
  name: string;
  path: string;
};

export type GraphQlEnum = {
  description?: string | null;
  name: string;
  values: Array<string>;
};

export type GraphQlField = {
  description?: string | null;
  name: string;
  required: boolean;
  typeName: string;
};

export type GraphQlInfo = {
  enums: Array<GraphQlEnum>;
  inputs: Array<GraphQlType>;
  mutations: Array<GraphQlOperation>;
  queries: Array<GraphQlOperation>;
  repo: string;
  subscriptions: Array<GraphQlOperation>;
  types: Array<GraphQlType>;
};

export type GraphQlOperation = {
  args: Array<GraphQlField>;
  deprecated: boolean;
  description?: string | null;
  name: string;
  returns: string;
};

export type GraphQlType = {
  description?: string | null;
  fields: Array<GraphQlField>;
  name: string;
};

export type GraphqlDownloadQuery = {
  /**
   * sdl (default) or introspection
   */
  format?: string | null;
};

export type GraphqlProxyRequest = {
  /**
   * Operation name
   */
  operationName?: string | null;
  /**
   * GraphQL query or mutation document
   */
  query: string;
  /**
   * Shopify shop domain (e.g. "myshop.myshopify.com" or "myshop")
   */
  shop: string;
  /**
   * Shopify Admin API access token
   */
  token: string;
  /**
   * Query variables
   */
  variables?: unknown;
};

export type HealthCheck = {
  label: string;
  ok: boolean;
  output: string;
  tool: string;
};

export type HealthResponse = {
  checks: Array<HealthCheck>;
  timestamp: string;
};

export type JiraIssuesQuery = {
  jql?: string | null;
  maxResults?: number | null;
};

export type LlmProviderAddRequest = {
  /**
   * "lmstudio" | "ollama"
   */
  kind?: string | null;
  name: string;
  url: string;
};

export type LlmProviderInfo = {
  enabled: boolean;
  /**
   * "lmstudio" | "ollama"
   */
  kind: string;
  name: string;
  reachable?: boolean | null;
  url: string;
};

export type LogProject = {
  path: string;
  project: string;
  services: Array<LogService>;
};

export type LogService = {
  health: string;
  name: string;
  ports: Array<string>;
  running: boolean;
  state: string;
};

export type LogServicesResponse = {
  projects: Array<LogProject>;
};

export type LogsResponse = {
  output: string;
};

export type MapRequest = {
  external_tool: string;
  name: string;
  orca_tool: string;
};

export type MappingRow = {
  confidence?: number | null;
  enabled: boolean;
  external_tool: string;
  match_type: string;
  mcp_name: string;
  orca_tool: string;
};

export type McpContent = {
  text: string;
  type: string;
};

export type McpRunRequest = {
  arguments?: unknown;
  name: string;
  server: string;
};

export type McpRunResponse = {
  content: Array<McpContent>;
  isError?: boolean | null;
};

export type McpServerAddRequest = {
  args?: Array<string>;
  command: string;
  env?: {
    [key: string]: string;
  };
  name: string;
};

export type McpServerInfo = {
  args: Array<string>;
  command: string;
  enabled: boolean;
  env: {
    [key: string]: string;
  };
  name: string;
};

export type McpToolInfo = {
  description: string;
  inputSchema: unknown;
  name: string;
  server: string;
};

export type MeOk = {
  role: string;
  user_id: string;
  username: string;
};

export type MpcStatus = {
  registered: boolean;
};

export type NodeType = 'file' | 'dir';

export type OkResponse = {
  ok: boolean;
};

export type PluginDataEntry = {
  key: string;
  updatedAt: string;
  value: {
    [key: string]: unknown;
  };
};

export type PluginInfo = {
  description: string;
  enabled: boolean;
  id: string;
  mcpCommand?: string | null;
  mode: string;
  navLinks: Array<unknown>;
  tier: string;
};

export type PluginInstallRequest = {
  /**
   * Optional instance id override — allows multiple instances of the same
   * plugin template with separate credentials (e.g. "atlassian@infra").
   */
  instanceId?: string | null;
  /**
   * Absolute or ~/ path to the orca-plugin.toml on the server's filesystem.
   */
  manifest: string;
};

export type PluginToolCallRequest = {
  /**
   * Arbitrary JSON the plugin tool expects. Validated by the plugin, not
   * by the host — the host is a transparent forwarder.
   */
  arguments: unknown;
  /**
   * Optional override (seconds). Defaults to `DEFAULT_CALL_TIMEOUT`.
   */
  timeoutSecs?: number | null;
};

export type PluginToolCallResponse = {
  /**
   * Opaque payload returned by the plugin tool.
   */
  result: unknown;
};

export type PluginToolInfo = {
  /**
   * Whether the owning plugin is currently connected to the host.
   */
  connected: boolean;
  description: string;
  fqName: string;
  /**
   * JSON Schema for the tool's input arguments. Returned as a parsed
   * object so the MCP layer can pass it straight through.
   */
  inputSchema: unknown;
  name: string;
  pluginId: string;
  sensitivity: string;
};

export type PrQuery = {
  slug: string;
  workspace: string;
};

export type ProgressRequest = {
  page: string;
};

export type ProgressResponse = {
  page?: string | null;
};

export type RepoInfo = {
  remote: string;
  slug: string;
  workspace: string;
};

export type SchemaColumn = {
  extra?: string;
  fk_target?: string | null;
  key?: string;
  name: string;
  nullable?: boolean;
  type: string;
};

export type SchemaDbAddRequest = {
  container?: string | null;
  database: string;
  domainsFile?: string | null;
  /**
   * mysql | postgres | sqlite
   */
  driver?: string;
  host?: string | null;
  name: string;
  password?: string;
  port?: number | null;
  user?: string;
};

export type SchemaDbInfo = {
  container?: string | null;
  database: string;
  domainsFile?: string | null;
  /**
   * mysql | postgres | sqlite
   */
  driver: string;
  enabled: boolean;
  host?: string | null;
  name: string;
  port?: number | null;
  user: string;
};

export type SchemaDomain = {
  color: string;
  group?: string;
  key: string;
  label: string;
  subgroup?: string;
  tables: Array<string>;
};

export type SchemaForeignKey = {
  column: string;
  refColumn?: string | null;
  refTable: string;
  table: string;
};

export type SchemaResponse = {
  errors?: Array<string> | null;
  showTabs: boolean;
  tabs: Array<SchemaTab>;
};

export type SchemaTab = {
  columns: {
    [key: string]: Array<SchemaColumn>;
  };
  domains: Array<SchemaDomain>;
  foreignKeys: Array<SchemaForeignKey>;
  tables: Array<SchemaTableInfo>;
  title: string;
};

export type SchemaTableInfo = {
  comment: string;
  name: string;
};

export type SearchResult = {
  matches: Array<string>;
  path: string;
  root: string;
};

export type SessionOk = {
  role: string;
  user_id: string;
  username: string;
};

export type SetCredRequest = {
  key: string;
  value: string;
};

export type SetPluginDataRequest = {
  value: {
    [key: string]: unknown;
  };
};

export type SigninRequest = {
  password: string;
  username: string;
};

export type SignupRequest = {
  password: string;
  username: string;
};

export type SignupStatus = {
  allowed: boolean;
  reason: string;
};

export type SpecDownloadQuery = {
  /**
   * json (default) or yaml
   */
  format?: string | null;
};

export type SpecFiles = {
  full?: string | null;
  public?: string | null;
};

export type SpecInfo = {
  cachedAt?: string | null;
  enabled: boolean;
  name: string;
  pathCount?: number | null;
  sourceMcp?: string | null;
  url?: string | null;
};

export type SpecMeta = {
  baseUrl?: string | null;
  capturedAt?: string | null;
  description?: string | null;
  files?: null | SpecFiles;
  notes?: string | null;
  pathCount?: number | null;
  project: string;
  repo: string;
  source: string;
};

export type SpecQuery = {
  /**
   * true adds Content-Disposition: attachment header
   */
  download?: boolean | null;
  /**
   * "json" (default) or "yaml"
   */
  format?: string | null;
};

export type SpecRegisterRequest = {
  name: string;
  url: string;
};

export type SystemActionRequest = {
  /**
   * "install" or "uninstall"
   */
  action: string;
};

export type SystemActionResponse = {
  done: Array<string>;
  errors: Array<string>;
  ok: boolean;
  skipped: Array<string>;
};

export type SystemDevSyncResponse = {
  already_up_to_date: boolean;
  commits_pulled: number;
  detail: string;
};

export type SystemStatusResponse = {
  agents: ComponentStatus;
  binary: ComponentStatus;
  claude_md: ComponentStatus;
  mcp: MpcStatus;
  vault: ComponentStatus;
};

export type TestRunQuery = {
  /**
   * Which suite to run: rust | frontend | e2e | all
   */
  suite: string;
};

export type TestRunResponse = {
  duration_ms: number;
  exit_code: number;
  failed: number;
  output: string;
  passed: number;
  suite: string;
};

export type TransitionBody = {
  transitionId: string;
};

export type TreeNode = {
  children?: Array<TreeNode> | null;
  name: string;
  order?: number | null;
  path: string;
  type: NodeType;
};

export type AuthMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/me';
};

export type AuthMeErrors = {
  /**
   * Not signed in
   */
  401: AuthErrorResponse;
};

export type AuthMeError = AuthMeErrors[keyof AuthMeErrors];

export type AuthMeResponses = {
  /**
   * Current identity
   */
  200: MeOk;
};

export type AuthMeResponse = AuthMeResponses[keyof AuthMeResponses];

export type AuthSigninData = {
  body: SigninRequest;
  path?: never;
  query?: never;
  url: '/api/auth/signin';
};

export type AuthSigninErrors = {
  /**
   * Invalid credentials
   */
  401: AuthErrorResponse;
};

export type AuthSigninError = AuthSigninErrors[keyof AuthSigninErrors];

export type AuthSigninResponses = {
  /**
   * Signed in; session cookie set
   */
  200: SessionOk;
};

export type AuthSigninResponse = AuthSigninResponses[keyof AuthSigninResponses];

export type AuthSignoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/signout';
};

export type AuthSignoutResponses = {
  /**
   * Session revoked; clear-cookie sent
   */
  200: unknown;
};

export type AuthSignupData = {
  body: SignupRequest;
  path?: never;
  query?: never;
  url: '/api/auth/signup';
};

export type AuthSignupErrors = {
  /**
   * Bad request (validation)
   */
  400: AuthErrorResponse;
  /**
   * Public sign-up disabled
   */
  403: AuthErrorResponse;
  /**
   * Username already taken
   */
  409: AuthErrorResponse;
};

export type AuthSignupError = AuthSignupErrors[keyof AuthSignupErrors];

export type AuthSignupResponses = {
  /**
   * Account created; session cookie set
   */
  200: SessionOk;
};

export type AuthSignupResponse = AuthSignupResponses[keyof AuthSignupResponses];

export type AuthSignupStatusData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/auth/signup_status';
};

export type AuthSignupStatusResponses = {
  /**
   * Whether sign-up is currently allowed
   */
  200: SignupStatus;
};

export type AuthSignupStatusResponse = AuthSignupStatusResponses[keyof AuthSignupStatusResponses];

export type ListBitbucketPrsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Bitbucket workspace slug
     */
    workspace: string;
    /**
     * Repository slug
     */
    slug: string;
  };
  url: '/api/bitbucket/prs';
};

export type ListBitbucketPrsErrors = {
  /**
   * Credential or upstream error
   */
  500: ErrorResponse;
};

export type ListBitbucketPrsError = ListBitbucketPrsErrors[keyof ListBitbucketPrsErrors];

export type ListBitbucketPrsResponses = {
  /**
   * Open pull requests from Bitbucket API (pagelen=50)
   */
  200: unknown;
};

export type ListBitbucketReposData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/bitbucket/repos';
};

export type ListBitbucketReposResponses = {
  /**
   * Bitbucket repos found under REBUY_ROOT
   */
  200: Array<RepoInfo>;
};

export type ListBitbucketReposResponse =
  ListBitbucketReposResponses[keyof ListBitbucketReposResponses];

export type SearchConfluenceData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * CQL query (default: type = page ORDER BY lastModified DESC)
     */
    cql?: string;
    /**
     * Max results (default: 25)
     */
    limit?: number;
  };
  url: '/api/confluence/search';
};

export type SearchConfluenceErrors = {
  500: ErrorResponse;
  502: ErrorResponse;
};

export type SearchConfluenceError = SearchConfluenceErrors[keyof SearchConfluenceErrors];

export type SearchConfluenceResponses = {
  /**
   * Confluence search results
   */
  200: unknown;
};

export type GetLibraryDocsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Library name to look up (npm package, crate, etc.)
     */
    q: string;
    /**
     * Specific topic or function to focus on
     */
    topic?: string;
  };
  url: '/api/ctx7';
};

export type GetLibraryDocsErrors = {
  /**
   * Missing query
   */
  400: ErrorResponse;
  /**
   * Library not found
   */
  404: ErrorResponse;
  /**
   * context7 not available
   */
  503: ErrorResponse;
};

export type GetLibraryDocsError = GetLibraryDocsErrors[keyof GetLibraryDocsErrors];

export type GetLibraryDocsResponses = {
  /**
   * Library documentation
   */
  200: Ctx7Response;
};

export type GetLibraryDocsResponse = GetLibraryDocsResponses[keyof GetLibraryDocsResponses];

export type GetDocData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Vault root name (orca/rebuy/docs)
     */
    root: string;
    /**
     * File path relative to root
     */
    path: string;
    /**
     * Pass `llm` to strip decorative markdown (bold, italic, images, HRs) and collapse whitespace — reduces token usage when the content will be read by a language model
     */
    format?: string;
  };
  url: '/api/doc';
};

export type GetDocErrors = {
  /**
   * Unknown root
   */
  400: ErrorResponse;
  /**
   * File not found
   */
  404: ErrorResponse;
};

export type GetDocError = GetDocErrors[keyof GetDocErrors];

export type GetDocResponses = {
  /**
   * Document content as plain text
   */
  200: unknown;
};

export type RunDockerActionData = {
  body: DockerActionRequest;
  path?: never;
  query?: never;
  url: '/api/docker/action';
};

export type RunDockerActionErrors = {
  /**
   * Unknown action
   */
  400: ErrorResponse;
  /**
   * No compose file
   */
  404: ErrorResponse;
  /**
   * Docker error
   */
  500: ErrorResponse;
};

export type RunDockerActionError = RunDockerActionErrors[keyof RunDockerActionErrors];

export type RunDockerActionResponses = {
  /**
   * Action output
   */
  200: DockerActionResponse;
};

export type RunDockerActionResponse = RunDockerActionResponses[keyof RunDockerActionResponses];

export type GetDockerEngineData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/docker/engine';
};

export type GetDockerEngineResponses = {
  /**
   * Docker engine status
   */
  200: unknown;
};

export type StartDockerEngineData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/docker/engine/start';
};

export type StartDockerEngineErrors = {
  /**
   * Failed to start engine
   */
  500: ErrorResponse;
};

export type StartDockerEngineError = StartDockerEngineErrors[keyof StartDockerEngineErrors];

export type StartDockerEngineResponses = {
  /**
   * Engine start output
   */
  200: unknown;
};

export type ListDockerRuntimesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/docker/runtimes';
};

export type ListDockerRuntimesErrors = {
  500: ErrorResponse;
};

export type ListDockerRuntimesError = ListDockerRuntimesErrors[keyof ListDockerRuntimesErrors];

export type ListDockerRuntimesResponses = {
  /**
   * All registered Docker runtimes
   */
  200: Array<DockerRuntimeInfo>;
};

export type ListDockerRuntimesResponse =
  ListDockerRuntimesResponses[keyof ListDockerRuntimesResponses];

export type AddDockerRuntimeData = {
  body: DockerRuntimeAddRequest;
  path?: never;
  query?: never;
  url: '/api/docker/runtimes';
};

export type AddDockerRuntimeErrors = {
  500: ErrorResponse;
};

export type AddDockerRuntimeError = AddDockerRuntimeErrors[keyof AddDockerRuntimeErrors];

export type AddDockerRuntimeResponses = {
  200: OkResponse;
};

export type AddDockerRuntimeResponse = AddDockerRuntimeResponses[keyof AddDockerRuntimeResponses];

export type RemoveDockerRuntimeData = {
  body?: never;
  path: {
    /**
     * Runtime name
     */
    name: string;
  };
  query?: never;
  url: '/api/docker/runtimes/{name}';
};

export type RemoveDockerRuntimeErrors = {
  404: ErrorResponse;
  500: ErrorResponse;
};

export type RemoveDockerRuntimeError = RemoveDockerRuntimeErrors[keyof RemoveDockerRuntimeErrors];

export type RemoveDockerRuntimeResponses = {
  200: OkResponse;
};

export type RemoveDockerRuntimeResponse =
  RemoveDockerRuntimeResponses[keyof RemoveDockerRuntimeResponses];

export type GetDockerServicesData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Absolute path to the Docker Compose project directory
     */
    path: string;
  };
  url: '/api/docker/services';
};

export type GetDockerServicesErrors = {
  /**
   * Docker error
   */
  500: ErrorResponse;
};

export type GetDockerServicesError = GetDockerServicesErrors[keyof GetDockerServicesErrors];

export type GetDockerServicesResponses = {
  /**
   * Compose file path and service list
   */
  200: DockerServicesResponse;
};

export type GetDockerServicesResponse =
  GetDockerServicesResponses[keyof GetDockerServicesResponses];

export type ListEnginesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/engines';
};

export type ListEnginesErrors = {
  500: ErrorResponse;
};

export type ListEnginesError = ListEnginesErrors[keyof ListEnginesErrors];

export type ListEnginesResponses = {
  /**
   * Registered LLM backends
   */
  200: Array<LlmProviderInfo>;
};

export type ListEnginesResponse = ListEnginesResponses[keyof ListEnginesResponses];

export type AddEngineData = {
  body: LlmProviderAddRequest;
  path?: never;
  query?: never;
  url: '/api/engines';
};

export type AddEngineErrors = {
  400: ErrorResponse;
};

export type AddEngineError = AddEngineErrors[keyof AddEngineErrors];

export type AddEngineResponses = {
  200: OkResponse;
};

export type AddEngineResponse = AddEngineResponses[keyof AddEngineResponses];

export type RemoveEngineData = {
  body?: never;
  path: {
    /**
     * Engine name
     */
    name: string;
  };
  query?: never;
  url: '/api/engines/{name}';
};

export type RemoveEngineErrors = {
  404: ErrorResponse;
};

export type RemoveEngineError = RemoveEngineErrors[keyof RemoveEngineErrors];

export type RemoveEngineResponses = {
  200: OkResponse;
};

export type RemoveEngineResponse = RemoveEngineResponses[keyof RemoveEngineResponses];

export type DisableEngineData = {
  body?: never;
  path: {
    /**
     * Engine name
     */
    name: string;
  };
  query?: never;
  url: '/api/engines/{name}/disable';
};

export type DisableEngineErrors = {
  404: ErrorResponse;
};

export type DisableEngineError = DisableEngineErrors[keyof DisableEngineErrors];

export type DisableEngineResponses = {
  200: OkResponse;
};

export type DisableEngineResponse = DisableEngineResponses[keyof DisableEngineResponses];

export type EnableEngineData = {
  body?: never;
  path: {
    /**
     * Engine name
     */
    name: string;
  };
  query?: never;
  url: '/api/engines/{name}/enable';
};

export type EnableEngineErrors = {
  404: ErrorResponse;
};

export type EnableEngineError = EnableEngineErrors[keyof EnableEngineErrors];

export type EnableEngineResponses = {
  200: OkResponse;
};

export type EnableEngineResponse = EnableEngineResponses[keyof EnableEngineResponses];

export type FsBrowseData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Directory to list (supports ~/). Defaults to home directory.
     */
    path?: string;
    /**
     * Request browsing outside home directory (requires fs.allow_unrestricted = true in orca.db).
     */
    allowAll?: boolean;
  };
  url: '/api/fs/browse';
};

export type FsBrowseErrors = {
  400: ErrorResponse;
  403: ErrorResponse;
  500: ErrorResponse;
};

export type FsBrowseError = FsBrowseErrors[keyof FsBrowseErrors];

export type FsBrowseResponses = {
  200: FsBrowseResponse;
};

export type FsBrowseResponse2 = FsBrowseResponses[keyof FsBrowseResponses];

export type ListGithubOrgsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/github/orgs';
};

export type ListGithubOrgsErrors = {
  500: ErrorResponse;
};

export type ListGithubOrgsError = ListGithubOrgsErrors[keyof ListGithubOrgsErrors];

export type ListGithubOrgsResponses = {
  /**
   * Organizations for the authenticated user
   */
  200: unknown;
};

export type ListGithubReposData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter type: all | owner | public | private | member
     */
    type?: string;
    /**
     * Sort by: created | updated | pushed | full_name
     */
    sort?: string;
    /**
     * Results per page (max 100, default 30)
     */
    per_page?: number;
  };
  url: '/api/github/repos';
};

export type ListGithubReposErrors = {
  500: ErrorResponse;
};

export type ListGithubReposError = ListGithubReposErrors[keyof ListGithubReposErrors];

export type ListGithubReposResponses = {
  /**
   * List of repos for the authenticated user
   */
  200: unknown;
};

export type ListGithubIssuesData = {
  body?: never;
  path: {
    /**
     * Repository owner
     */
    owner: string;
    /**
     * Repository name
     */
    repo: string;
  };
  query?: {
    /**
     * Issue state: open | closed | all
     */
    state?: string;
    /**
     * Results per page
     */
    per_page?: number;
  };
  url: '/api/github/repos/{owner}/{repo}/issues';
};

export type ListGithubIssuesErrors = {
  500: ErrorResponse;
};

export type ListGithubIssuesError = ListGithubIssuesErrors[keyof ListGithubIssuesErrors];

export type ListGithubIssuesResponses = {
  /**
   * Issues (PRs excluded)
   */
  200: unknown;
};

export type ListGithubPrsData = {
  body?: never;
  path: {
    /**
     * Repository owner
     */
    owner: string;
    /**
     * Repository name
     */
    repo: string;
  };
  query?: {
    /**
     * PR state: open | closed | all
     */
    state?: string;
    /**
     * Results per page
     */
    per_page?: number;
  };
  url: '/api/github/repos/{owner}/{repo}/pulls';
};

export type ListGithubPrsErrors = {
  500: ErrorResponse;
};

export type ListGithubPrsError = ListGithubPrsErrors[keyof ListGithubPrsErrors];

export type ListGithubPrsResponses = {
  /**
   * Pull requests
   */
  200: unknown;
};

export type GetGithubUserData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/github/user';
};

export type GetGithubUserErrors = {
  500: ErrorResponse;
};

export type GetGithubUserError = GetGithubUserErrors[keyof GetGithubUserErrors];

export type GetGithubUserResponses = {
  /**
   * Authenticated GitHub user
   */
  200: unknown;
};

export type PingData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/health';
};

export type PingResponses = {
  /**
   * Server is alive
   */
  200: unknown;
};

export type ListJiraIssuesData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * JQL query (default: assignee = currentUser() ORDER BY updated DESC)
     */
    jql?: string;
    /**
     * Max results to return (default: 50)
     */
    maxResults?: number;
  };
  url: '/api/jira/issues';
};

export type ListJiraIssuesErrors = {
  /**
   * Config or credential error
   */
  500: ErrorResponse;
  /**
   * Upstream Jira API error
   */
  502: ErrorResponse;
};

export type ListJiraIssuesError = ListJiraIssuesErrors[keyof ListJiraIssuesErrors];

export type ListJiraIssuesResponses = {
  /**
   * Jira search result
   */
  200: unknown;
};

export type GetJiraTransitionsData = {
  body?: never;
  path: {
    /**
     * Jira issue key (e.g. PROJ-123)
     */
    key: string;
  };
  query?: never;
  url: '/api/jira/issues/{key}/transitions';
};

export type GetJiraTransitionsErrors = {
  500: ErrorResponse;
  502: ErrorResponse;
};

export type GetJiraTransitionsError = GetJiraTransitionsErrors[keyof GetJiraTransitionsErrors];

export type GetJiraTransitionsResponses = {
  /**
   * Available transitions
   */
  200: unknown;
};

export type TransitionJiraIssueData = {
  body: TransitionBody;
  path: {
    /**
     * Jira issue key
     */
    key: string;
  };
  query?: never;
  url: '/api/jira/issues/{key}/transitions';
};

export type TransitionJiraIssueErrors = {
  500: ErrorResponse;
  502: ErrorResponse;
};

export type TransitionJiraIssueError = TransitionJiraIssueErrors[keyof TransitionJiraIssueErrors];

export type TransitionJiraIssueResponses = {
  200: OkResponse;
};

export type TransitionJiraIssueResponse =
  TransitionJiraIssueResponses[keyof TransitionJiraIssueResponses];

export type GetLearningProgressData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/learning/progress';
};

export type GetLearningProgressResponses = {
  /**
   * Last visited learning page
   */
  200: ProgressResponse;
};

export type GetLearningProgressResponse =
  GetLearningProgressResponses[keyof GetLearningProgressResponses];

export type SaveLearningProgressData = {
  body: ProgressRequest;
  path?: never;
  query?: never;
  url: '/api/learning/progress';
};

export type SaveLearningProgressResponses = {
  /**
   * Progress saved
   */
  200: unknown;
};

export type GetLogsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Absolute path to the project directory
     */
    project: string;
    /**
     * Specific service name (omit for all)
     */
    service?: string;
    /**
     * Number of log lines to return (default 200)
     */
    tail?: number;
  };
  url: '/api/logs';
};

export type GetLogsErrors = {
  /**
   * No compose file found
   */
  404: ErrorResponse;
  /**
   * Docker error
   */
  500: ErrorResponse;
};

export type GetLogsError = GetLogsErrors[keyof GetLogsErrors];

export type GetLogsResponses = {
  /**
   * Log output
   */
  200: LogsResponse;
};

export type GetLogsResponse = GetLogsResponses[keyof GetLogsResponses];

export type GetLogServicesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/logs/services';
};

export type GetLogServicesErrors = {
  /**
   * Rebuy root not found
   */
  404: ErrorResponse;
};

export type GetLogServicesError = GetLogServicesErrors[keyof GetLogServicesErrors];

export type GetLogServicesResponses = {
  /**
   * All Docker projects and their service states
   */
  200: LogServicesResponse;
};

export type GetLogServicesResponse = GetLogServicesResponses[keyof GetLogServicesResponses];

export type ListMcpMappingsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter by MCP server name
     */
    name?: string;
  };
  url: '/api/mcp/mappings';
};

export type ListMcpMappingsErrors = {
  500: ErrorResponse;
};

export type ListMcpMappingsError = ListMcpMappingsErrors[keyof ListMcpMappingsErrors];

export type ListMcpMappingsResponses = {
  200: Array<MappingRow>;
};

export type ListMcpMappingsResponse = ListMcpMappingsResponses[keyof ListMcpMappingsResponses];

export type CreateMcpMappingData = {
  body: MapRequest;
  path?: never;
  query?: never;
  url: '/api/mcp/mappings';
};

export type CreateMcpMappingErrors = {
  500: ErrorResponse;
};

export type CreateMcpMappingError = CreateMcpMappingErrors[keyof CreateMcpMappingErrors];

export type CreateMcpMappingResponses = {
  200: OkResponse;
};

export type CreateMcpMappingResponse = CreateMcpMappingResponses[keyof CreateMcpMappingResponses];

export type DeleteMcpMappingData = {
  body?: never;
  path: {
    /**
     * Orca tool name to unmap
     */
    orca_tool: string;
  };
  query?: never;
  url: '/api/mcp/mappings/{orca_tool}';
};

export type DeleteMcpMappingErrors = {
  404: ErrorResponse;
  500: ErrorResponse;
};

export type DeleteMcpMappingError = DeleteMcpMappingErrors[keyof DeleteMcpMappingErrors];

export type DeleteMcpMappingResponses = {
  200: OkResponse;
};

export type DeleteMcpMappingResponse = DeleteMcpMappingResponses[keyof DeleteMcpMappingResponses];

export type RunMcpToolData = {
  body: McpRunRequest;
  path?: never;
  query?: never;
  url: '/api/mcp/run';
};

export type RunMcpToolErrors = {
  /**
   * Unknown MCP server
   */
  404: ErrorResponse;
  /**
   * Tool execution error
   */
  500: ErrorResponse;
};

export type RunMcpToolError = RunMcpToolErrors[keyof RunMcpToolErrors];

export type RunMcpToolResponses = {
  /**
   * Tool result
   */
  200: McpRunResponse;
};

export type RunMcpToolResponse = RunMcpToolResponses[keyof RunMcpToolResponses];

export type ListMcpServersData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/mcp/servers';
};

export type ListMcpServersErrors = {
  500: ErrorResponse;
};

export type ListMcpServersError = ListMcpServersErrors[keyof ListMcpServersErrors];

export type ListMcpServersResponses = {
  /**
   * All registered MCP servers
   */
  200: Array<McpServerInfo>;
};

export type ListMcpServersResponse = ListMcpServersResponses[keyof ListMcpServersResponses];

export type AddMcpServerData = {
  body: McpServerAddRequest;
  path?: never;
  query?: never;
  url: '/api/mcp/servers';
};

export type AddMcpServerErrors = {
  500: ErrorResponse;
};

export type AddMcpServerError = AddMcpServerErrors[keyof AddMcpServerErrors];

export type AddMcpServerResponses = {
  200: OkResponse;
};

export type AddMcpServerResponse = AddMcpServerResponses[keyof AddMcpServerResponses];

export type RemoveMcpServerData = {
  body?: never;
  path: {
    /**
     * Server name
     */
    name: string;
  };
  query?: never;
  url: '/api/mcp/servers/{name}';
};

export type RemoveMcpServerErrors = {
  404: ErrorResponse;
  500: ErrorResponse;
};

export type RemoveMcpServerError = RemoveMcpServerErrors[keyof RemoveMcpServerErrors];

export type RemoveMcpServerResponses = {
  200: OkResponse;
};

export type RemoveMcpServerResponse = RemoveMcpServerResponses[keyof RemoveMcpServerResponses];

export type GetMcpToolsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/mcp/tools';
};

export type GetMcpToolsResponses = {
  /**
   * All tools from all connected MCP servers
   */
  200: Array<McpToolInfo>;
};

export type GetMcpToolsResponse = GetMcpToolsResponses[keyof GetMcpToolsResponses];

export type ListPluginToolsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/plugin-tools';
};

export type ListPluginToolsErrors = {
  500: ErrorResponse;
};

export type ListPluginToolsError = ListPluginToolsErrors[keyof ListPluginToolsErrors];

export type ListPluginToolsResponses = {
  /**
   * All declared plugin tools
   */
  200: Array<PluginToolInfo>;
};

export type ListPluginToolsResponse = ListPluginToolsResponses[keyof ListPluginToolsResponses];

export type CallPluginToolData = {
  body: PluginToolCallRequest;
  path: {
    /**
     * Fully-qualified tool name `<plugin_id>.<name>`
     */
    fq_name: string;
  };
  query?: never;
  url: '/api/plugin-tools/{fq_name}/call';
};

export type CallPluginToolErrors = {
  /**
   * Tool not registered or plugin not connected
   */
  404: ErrorResponse;
  500: ErrorResponse;
  /**
   * Plugin returned an error or did not respond
   */
  502: ErrorResponse;
};

export type CallPluginToolError = CallPluginToolErrors[keyof CallPluginToolErrors];

export type CallPluginToolResponses = {
  /**
   * Tool result
   */
  200: PluginToolCallResponse;
};

export type CallPluginToolResponse = CallPluginToolResponses[keyof CallPluginToolResponses];

export type ListPluginsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/plugins';
};

export type ListPluginsErrors = {
  500: ErrorResponse;
};

export type ListPluginsError = ListPluginsErrors[keyof ListPluginsErrors];

export type ListPluginsResponses = {
  /**
   * All registered plugins
   */
  200: Array<PluginInfo>;
};

export type ListPluginsResponse = ListPluginsResponses[keyof ListPluginsResponses];

export type InstallPluginData = {
  body: PluginInstallRequest;
  path?: never;
  query?: never;
  url: '/api/plugins';
};

export type InstallPluginErrors = {
  400: ErrorResponse;
  500: ErrorResponse;
};

export type InstallPluginError = InstallPluginErrors[keyof InstallPluginErrors];

export type InstallPluginResponses = {
  /**
   * Plugin id that was installed
   */
  200: OkResponse;
};

export type InstallPluginResponse = InstallPluginResponses[keyof InstallPluginResponses];

export type RemovePluginData = {
  body?: never;
  path: {
    /**
     * Plugin ID
     */
    id: string;
  };
  query?: never;
  url: '/api/plugins/{id}';
};

export type RemovePluginErrors = {
  404: ErrorResponse;
  500: ErrorResponse;
};

export type RemovePluginError = RemovePluginErrors[keyof RemovePluginErrors];

export type RemovePluginResponses = {
  200: OkResponse;
};

export type RemovePluginResponse = RemovePluginResponses[keyof RemovePluginResponses];

export type ListPluginCredsData = {
  body?: never;
  path: {
    /**
     * Plugin ID
     */
    id: string;
  };
  query?: never;
  url: '/api/plugins/{id}/creds';
};

export type ListPluginCredsErrors = {
  404: ErrorResponse;
  500: ErrorResponse;
};

export type ListPluginCredsError = ListPluginCredsErrors[keyof ListPluginCredsErrors];

export type ListPluginCredsResponses = {
  /**
   * Credential keys for plugin (no values)
   */
  200: Array<CredInfo>;
};

export type ListPluginCredsResponse = ListPluginCredsResponses[keyof ListPluginCredsResponses];

export type SetPluginCredData = {
  body: SetCredRequest;
  path: {
    /**
     * Plugin ID
     */
    id: string;
  };
  query?: never;
  url: '/api/plugins/{id}/creds';
};

export type SetPluginCredErrors = {
  404: ErrorResponse;
  500: ErrorResponse;
};

export type SetPluginCredError = SetPluginCredErrors[keyof SetPluginCredErrors];

export type SetPluginCredResponses = {
  200: OkResponse;
};

export type SetPluginCredResponse = SetPluginCredResponses[keyof SetPluginCredResponses];

export type SyncPluginCredsData = {
  body?: never;
  path: {
    /**
     * Plugin ID
     */
    id: string;
  };
  query?: never;
  url: '/api/plugins/{id}/creds/sync';
};

export type SyncPluginCredsErrors = {
  404: ErrorResponse;
  500: ErrorResponse;
};

export type SyncPluginCredsError = SyncPluginCredsErrors[keyof SyncPluginCredsErrors];

export type SyncPluginCredsResponses = {
  /**
   * Number of credentials synced
   */
  200: OkResponse;
};

export type SyncPluginCredsResponse = SyncPluginCredsResponses[keyof SyncPluginCredsResponses];

export type DeletePluginCredData = {
  body?: never;
  path: {
    /**
     * Plugin ID
     */
    id: string;
    /**
     * Credential key
     */
    key: string;
  };
  query?: never;
  url: '/api/plugins/{id}/creds/{key}';
};

export type DeletePluginCredErrors = {
  404: ErrorResponse;
  500: ErrorResponse;
};

export type DeletePluginCredError = DeletePluginCredErrors[keyof DeletePluginCredErrors];

export type DeletePluginCredResponses = {
  200: OkResponse;
};

export type DeletePluginCredResponse = DeletePluginCredResponses[keyof DeletePluginCredResponses];

export type ListPluginDataData = {
  body?: never;
  path: {
    /**
     * Plugin ID
     */
    id: string;
  };
  query?: never;
  url: '/api/plugins/{id}/data';
};

export type ListPluginDataErrors = {
  500: ErrorResponse;
};

export type ListPluginDataError = ListPluginDataErrors[keyof ListPluginDataErrors];

export type ListPluginDataResponses = {
  /**
   * All data entries for plugin
   */
  200: Array<PluginDataEntry>;
};

export type ListPluginDataResponse = ListPluginDataResponses[keyof ListPluginDataResponses];

export type DeletePluginDataData = {
  body?: never;
  path: {
    /**
     * Plugin ID
     */
    id: string;
    /**
     * Data key
     */
    key: string;
  };
  query?: never;
  url: '/api/plugins/{id}/data/{key}';
};

export type DeletePluginDataErrors = {
  404: ErrorResponse;
  500: ErrorResponse;
};

export type DeletePluginDataError = DeletePluginDataErrors[keyof DeletePluginDataErrors];

export type DeletePluginDataResponses = {
  200: OkResponse;
};

export type DeletePluginDataResponse = DeletePluginDataResponses[keyof DeletePluginDataResponses];

export type GetPluginDataData = {
  body?: never;
  path: {
    /**
     * Plugin ID
     */
    id: string;
    /**
     * Data key
     */
    key: string;
  };
  query?: never;
  url: '/api/plugins/{id}/data/{key}';
};

export type GetPluginDataErrors = {
  404: ErrorResponse;
  500: ErrorResponse;
};

export type GetPluginDataError = GetPluginDataErrors[keyof GetPluginDataErrors];

export type GetPluginDataResponses = {
  /**
   * Data entry
   */
  200: PluginDataEntry;
};

export type GetPluginDataResponse = GetPluginDataResponses[keyof GetPluginDataResponses];

export type SetPluginDataData = {
  body: SetPluginDataRequest;
  path: {
    /**
     * Plugin ID
     */
    id: string;
    /**
     * Data key
     */
    key: string;
  };
  query?: never;
  url: '/api/plugins/{id}/data/{key}';
};

export type SetPluginDataErrors = {
  500: ErrorResponse;
};

export type SetPluginDataError = SetPluginDataErrors[keyof SetPluginDataErrors];

export type SetPluginDataResponses = {
  200: OkResponse;
};

export type SetPluginDataResponse = SetPluginDataResponses[keyof SetPluginDataResponses];

export type DisablePluginData = {
  body?: never;
  path: {
    /**
     * Plugin ID
     */
    id: string;
  };
  query?: never;
  url: '/api/plugins/{id}/disable';
};

export type DisablePluginErrors = {
  404: ErrorResponse;
  500: ErrorResponse;
};

export type DisablePluginError = DisablePluginErrors[keyof DisablePluginErrors];

export type DisablePluginResponses = {
  200: OkResponse;
};

export type DisablePluginResponse = DisablePluginResponses[keyof DisablePluginResponses];

export type EnablePluginData = {
  body?: never;
  path: {
    /**
     * Plugin ID
     */
    id: string;
  };
  query?: never;
  url: '/api/plugins/{id}/enable';
};

export type EnablePluginErrors = {
  404: ErrorResponse;
  500: ErrorResponse;
};

export type EnablePluginError = EnablePluginErrors[keyof EnablePluginErrors];

export type EnablePluginResponses = {
  200: OkResponse;
};

export type EnablePluginResponse = EnablePluginResponses[keyof EnablePluginResponses];

export type GetPluginHealthData = {
  body?: never;
  path: {
    /**
     * Plugin ID
     */
    id: string;
  };
  query?: never;
  url: '/api/plugins/{id}/health';
};

export type GetPluginHealthErrors = {
  404: ErrorResponse;
  502: ErrorResponse;
};

export type GetPluginHealthError = GetPluginHealthErrors[keyof GetPluginHealthErrors];

export type GetPluginHealthResponses = {
  /**
   * Plugin health status
   */
  200: unknown;
};

export type GetHealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/rebuy/health/local';
};

export type GetHealthErrors = {
  /**
   * rebuy MCP unavailable
   */
  503: ErrorResponse;
};

export type GetHealthError = GetHealthErrors[keyof GetHealthErrors];

export type GetHealthResponses = {
  /**
   * All service health checks
   */
  200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetSchemaData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/schema';
};

export type GetSchemaErrors = {
  /**
   * No databases configured
   */
  404: ErrorResponse;
  /**
   * All DB connections failed
   */
  500: ErrorResponse;
};

export type GetSchemaError = GetSchemaErrors[keyof GetSchemaErrors];

export type GetSchemaResponses = {
  /**
   * Database schema tabs
   */
  200: SchemaResponse;
};

export type GetSchemaResponse = GetSchemaResponses[keyof GetSchemaResponses];

export type ListSchemaDatabasesData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/schema/databases';
};

export type ListSchemaDatabasesErrors = {
  500: ErrorResponse;
};

export type ListSchemaDatabasesError = ListSchemaDatabasesErrors[keyof ListSchemaDatabasesErrors];

export type ListSchemaDatabasesResponses = {
  /**
   * All registered schema databases
   */
  200: Array<SchemaDbInfo>;
};

export type ListSchemaDatabasesResponse =
  ListSchemaDatabasesResponses[keyof ListSchemaDatabasesResponses];

export type AddSchemaDatabaseData = {
  body: SchemaDbAddRequest;
  path?: never;
  query?: never;
  url: '/api/schema/databases';
};

export type AddSchemaDatabaseErrors = {
  500: ErrorResponse;
};

export type AddSchemaDatabaseError = AddSchemaDatabaseErrors[keyof AddSchemaDatabaseErrors];

export type AddSchemaDatabaseResponses = {
  200: OkResponse;
};

export type AddSchemaDatabaseResponse =
  AddSchemaDatabaseResponses[keyof AddSchemaDatabaseResponses];

export type RemoveSchemaDatabaseData = {
  body?: never;
  path: {
    /**
     * Database name
     */
    name: string;
  };
  query?: never;
  url: '/api/schema/databases/{name}';
};

export type RemoveSchemaDatabaseErrors = {
  404: ErrorResponse;
  500: ErrorResponse;
};

export type RemoveSchemaDatabaseError =
  RemoveSchemaDatabaseErrors[keyof RemoveSchemaDatabaseErrors];

export type RemoveSchemaDatabaseResponses = {
  200: OkResponse;
};

export type RemoveSchemaDatabaseResponse =
  RemoveSchemaDatabaseResponses[keyof RemoveSchemaDatabaseResponses];

export type GetSchemaDomainsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/schema/domains';
};

export type GetSchemaDomainsResponses = {
  /**
   * All domain definitions from all configured databases
   */
  200: unknown;
};

export type SearchDocsData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Search query
     */
    q?: string;
    /**
     * Limit search to a specific root (orca/rebuy)
     */
    root?: string;
  };
  url: '/api/search';
};

export type SearchDocsResponses = {
  /**
   * Search results
   */
  200: Array<SearchResult>;
};

export type SearchDocsResponse = SearchDocsResponses[keyof SearchDocsResponses];

export type ListSpecsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/specs';
};

export type ListSpecsResponses = {
  /**
   * All registered external specs
   */
  200: Array<SpecMeta>;
};

export type ListSpecsResponse = ListSpecsResponses[keyof ListSpecsResponses];

export type ListDbSpecsData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/specs/db';
};

export type ListDbSpecsResponses = {
  /**
   * All URL-registered specs from orca.db
   */
  200: Array<SpecInfo>;
};

export type ListDbSpecsResponse = ListDbSpecsResponses[keyof ListDbSpecsResponses];

export type RegisterSpecData = {
  body: SpecRegisterRequest;
  path?: never;
  query?: never;
  url: '/api/specs/register';
};

export type RegisterSpecErrors = {
  /**
   * Bad request
   */
  400: ErrorResponse;
  /**
   * Failed to fetch spec from URL
   */
  502: ErrorResponse;
};

export type RegisterSpecError = RegisterSpecErrors[keyof RegisterSpecErrors];

export type RegisterSpecResponses = {
  /**
   * Spec fetched and stored
   */
  200: SpecInfo;
};

export type RegisterSpecResponse = RegisterSpecResponses[keyof RegisterSpecResponses];

export type SyncMcpSpecsData = {
  body?: never;
  path: {
    /**
     * MCP server name (e.g. rebuy-cli)
     */
    server: string;
  };
  query?: never;
  url: '/api/specs/sync-mcp/{server}';
};

export type SyncMcpSpecsResponses = {
  /**
   * Sync result
   */
  200: OkResponse;
};

export type SyncMcpSpecsResponse = SyncMcpSpecsResponses[keyof SyncMcpSpecsResponses];

export type RefreshSpecData = {
  body?: never;
  path: {
    /**
     * Spec name to refresh
     */
    name: string;
  };
  query?: never;
  url: '/api/specs/{name}/refresh';
};

export type RefreshSpecErrors = {
  /**
   * Spec not found or has no URL
   */
  404: ErrorResponse;
  /**
   * Failed to fetch spec from URL
   */
  502: ErrorResponse;
};

export type RefreshSpecError = RefreshSpecErrors[keyof RefreshSpecErrors];

export type RefreshSpecResponses = {
  /**
   * Spec refreshed from stored URL
   */
  200: SpecInfo;
};

export type RefreshSpecResponse = RefreshSpecResponses[keyof RefreshSpecResponses];

export type UnregisterSpecData = {
  body?: never;
  path: {
    /**
     * Spec name to unregister
     */
    name: string;
  };
  query?: never;
  url: '/api/specs/{name}/unregister';
};

export type UnregisterSpecErrors = {
  /**
   * Spec not found
   */
  404: ErrorResponse;
};

export type UnregisterSpecError = UnregisterSpecErrors[keyof UnregisterSpecErrors];

export type UnregisterSpecResponses = {
  /**
   * Spec removed from DB
   */
  200: OkResponse;
};

export type UnregisterSpecResponse = UnregisterSpecResponses[keyof UnregisterSpecResponses];

export type GetSpecData = {
  body?: never;
  path: {
    /**
     * Repository name (e.g. admin-api)
     */
    repo: string;
  };
  query?: {
    /**
     * Response format: json (default) or yaml
     */
    format?: string;
    /**
     * Set true to receive Content-Disposition: attachment
     */
    download?: boolean;
  };
  url: '/api/specs/{repo}';
};

export type GetSpecErrors = {
  /**
   * Invalid repo name
   */
  400: ErrorResponse;
  /**
   * Spec not found
   */
  404: ErrorResponse;
  /**
   * Invalid spec JSON
   */
  500: ErrorResponse;
};

export type GetSpecError = GetSpecErrors[keyof GetSpecErrors];

export type GetSpecResponses = {
  /**
   * Full OpenAPI spec for the repo
   */
  200: unknown;
};

export type DownloadSpecData = {
  body?: never;
  path: {
    /**
     * Repository name (e.g. admin-api)
     */
    repo: string;
  };
  query?: {
    /**
     * json (default) or yaml
     */
    format?: string;
  };
  url: '/api/specs/{repo}/download';
};

export type DownloadSpecErrors = {
  /**
   * Invalid repo name
   */
  400: ErrorResponse;
  /**
   * Spec not found
   */
  404: ErrorResponse;
  /**
   * Invalid spec JSON or YAML conversion failed
   */
  500: ErrorResponse;
};

export type DownloadSpecError = DownloadSpecErrors[keyof DownloadSpecErrors];

export type DownloadSpecResponses = {
  /**
   * OpenAPI spec file download
   */
  200: unknown;
};

export type GetSpecGraphqlData = {
  body?: never;
  path: {
    /**
     * Repository name (e.g. admin-api)
     */
    repo: string;
  };
  query?: {
    /**
     * Set true to receive Content-Disposition: attachment
     */
    download?: boolean;
  };
  url: '/api/specs/{repo}/graphql';
};

export type GetSpecGraphqlErrors = {
  /**
   * Invalid repo name
   */
  400: ErrorResponse;
  /**
   * Schema not found
   */
  404: ErrorResponse;
};

export type GetSpecGraphqlError = GetSpecGraphqlErrors[keyof GetSpecGraphqlErrors];

export type GetSpecGraphqlResponses = {
  /**
   * GraphQL SDL schema for the repo
   */
  200: unknown;
};

export type DownloadGraphqlData = {
  body?: never;
  path: {
    /**
     * Repository name (e.g. admin-api)
     */
    repo: string;
  };
  query?: {
    /**
     * sdl (default) or introspection
     */
    format?: string;
  };
  url: '/api/specs/{repo}/graphql/download';
};

export type DownloadGraphqlErrors = {
  /**
   * Invalid repo name
   */
  400: ErrorResponse;
  /**
   * Schema not found
   */
  404: ErrorResponse;
};

export type DownloadGraphqlError = DownloadGraphqlErrors[keyof DownloadGraphqlErrors];

export type DownloadGraphqlResponses = {
  /**
   * GraphQL schema download
   */
  200: unknown;
};

export type GetSpecGraphqlInfoData = {
  body?: never;
  path: {
    /**
     * Repository name (e.g. admin-api)
     */
    repo: string;
  };
  query?: never;
  url: '/api/specs/{repo}/graphql/info';
};

export type GetSpecGraphqlInfoErrors = {
  /**
   * Invalid repo name
   */
  400: ErrorResponse;
  /**
   * GraphQL schema not found
   */
  404: ErrorResponse;
  /**
   * SDL parse error
   */
  422: ErrorResponse;
};

export type GetSpecGraphqlInfoError = GetSpecGraphqlInfoErrors[keyof GetSpecGraphqlInfoErrors];

export type GetSpecGraphqlInfoResponses = {
  /**
   * Parsed GraphQL schema — types, queries, mutations, subscriptions
   */
  200: GraphQlInfo;
};

export type GetSpecGraphqlInfoResponse =
  GetSpecGraphqlInfoResponses[keyof GetSpecGraphqlInfoResponses];

export type ProxyGraphqlData = {
  body: GraphqlProxyRequest;
  path: {
    /**
     * Repository name (e.g. shopify-admin)
     */
    repo: string;
  };
  query?: never;
  url: '/api/specs/{repo}/graphql/proxy';
};

export type ProxyGraphqlErrors = {
  /**
   * Invalid repo name or request body
   */
  400: ErrorResponse;
  /**
   * Upstream request failed
   */
  502: ErrorResponse;
};

export type ProxyGraphqlError = ProxyGraphqlErrors[keyof ProxyGraphqlErrors];

export type ProxyGraphqlResponses = {
  /**
   * GraphQL response JSON from the upstream shop
   */
  200: unknown;
};

export type GetSpecPublicData = {
  body?: never;
  path: {
    /**
     * Repository name (e.g. admin-api)
     */
    repo: string;
  };
  query?: {
    /**
     * Response format: json (default) or yaml
     */
    format?: string;
    /**
     * Set true to receive Content-Disposition: attachment
     */
    download?: boolean;
  };
  url: '/api/specs/{repo}/public';
};

export type GetSpecPublicErrors = {
  /**
   * Invalid repo name
   */
  400: ErrorResponse;
  /**
   * Spec not found
   */
  404: ErrorResponse;
  /**
   * Invalid spec JSON
   */
  500: ErrorResponse;
};

export type GetSpecPublicError = GetSpecPublicErrors[keyof GetSpecPublicErrors];

export type GetSpecPublicResponses = {
  /**
   * Public-tagged operations only
   */
  200: unknown;
};

export type SystemActionHandlerData = {
  body: SystemActionRequest;
  path?: never;
  query?: never;
  url: '/api/system/action';
};

export type SystemActionHandlerErrors = {
  /**
   * Bad request
   */
  400: ErrorResponse;
  /**
   * Error
   */
  500: ErrorResponse;
};

export type SystemActionHandlerError = SystemActionHandlerErrors[keyof SystemActionHandlerErrors];

export type SystemActionHandlerResponses = {
  /**
   * Action result
   */
  200: SystemActionResponse;
};

export type SystemActionHandlerResponse =
  SystemActionHandlerResponses[keyof SystemActionHandlerResponses];

export type SystemDevSyncHandlerData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/system/dev-sync';
};

export type SystemDevSyncHandlerErrors = {
  /**
   * Not in dev mode
   */
  409: ErrorResponse;
  /**
   * Error
   */
  500: ErrorResponse;
};

export type SystemDevSyncHandlerError =
  SystemDevSyncHandlerErrors[keyof SystemDevSyncHandlerErrors];

export type SystemDevSyncHandlerResponses = {
  /**
   * Sync result
   */
  200: SystemDevSyncResponse;
};

export type SystemDevSyncHandlerResponse =
  SystemDevSyncHandlerResponses[keyof SystemDevSyncHandlerResponses];

export type SystemStatusHandlerData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/api/system/status';
};

export type SystemStatusHandlerErrors = {
  /**
   * Error
   */
  500: ErrorResponse;
};

export type SystemStatusHandlerError = SystemStatusHandlerErrors[keyof SystemStatusHandlerErrors];

export type SystemStatusHandlerResponses = {
  /**
   * Installation status
   */
  200: unknown;
};

export type RunTestsData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Test suite to run: rust | frontend | e2e | all
     */
    suite: string;
  };
  url: '/api/tests/run';
};

export type RunTestsErrors = {
  /**
   * Runner error
   */
  500: ErrorResponse;
};

export type RunTestsError = RunTestsErrors[keyof RunTestsErrors];

export type RunTestsResponses = {
  /**
   * Test run result
   */
  200: TestRunResponse;
};

export type RunTestsResponse = RunTestsResponses[keyof RunTestsResponses];

export type GetTreeData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Skip compaction — return raw filesystem tree
     */
    raw?: boolean;
  };
  url: '/api/tree';
};

export type GetTreeErrors = {
  /**
   * Error
   */
  500: ErrorResponse;
};

export type GetTreeError = GetTreeErrors[keyof GetTreeErrors];

export type GetTreeResponses = {
  /**
   * Document tree indexed by root name
   */
  200: unknown;
};
