// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zAdvisorySeverity = z.enum(['critical', 'high', 'medium', 'low', 'none']);

export const zAgentBackendOverrideEntry = z.object({
  agent: z.string(),
  backend: z.string(),
});

export const zAgentEntry = z.object({
  description: z.string(),
  name: z.string(),
});

export const zApiTokenSummary = z.object({
  created_at: z.string(),
  expires_at: z.string().nullish(),
  id: z.string(),
  last_used_at: z.string().nullish(),
  name: z.string(),
  role: z.string(),
});

export const zAuthErrorResponse = z.object({
  error: z.string(),
});

export const zAuthProviderStatus = z.object({
  configured: z.boolean(),
  identity: z.string().nullish(),
  provider: z.string(),
});

export const zBackendInfo = z.object({
  kind: z.string(),
  supports_store: z.boolean(),
});

export const zCertInfo = z.object({
  cn: z.string(),
  days_remaining: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  expires_at: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  fingerprint: z.string(),
  issued_at: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
});

export const zChangePasswordOk = z.object({
  ok: z.boolean(),
});

export const zChangePasswordRequest = z.object({
  current_password: z.string(),
  new_password: z.string(),
});

export const zComponentStatus = z.object({
  installed: z.boolean(),
  path: z.string(),
});

export const zConfigRowOut = z.object({
  host_owner: z.string(),
  id: z.string(),
  is_replica: z.boolean(),
  json: z.string(),
  name: z.string(),
  noun: z.string(),
  updated_at: z.string(),
  updated_by: z.string(),
});

export const zConfluenceSearchQuery = z.object({
  cql: z.string().nullish(),
  limit: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
});

export const zCredInfo = z.object({
  key: z.string(),
  synced: z.boolean(),
  updatedAt: z.string(),
});

export const zCtx7Response = z.object({
  content: z.string(),
  libraryId: z.string(),
  title: z.string(),
  topic: z.string().nullish(),
});

export const zDbSpecRow = z.object({
  cachedAt: z.string().nullish(),
  enabled: z.boolean(),
  name: z.string(),
  pathCount: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  sourceMcp: z.string().nullish(),
  url: z.string().nullish(),
});

export const zDenyAdvisory = z.object({
  id: z.string(),
  package: z.string(),
  severity: zAdvisorySeverity,
  title: z.string(),
  url: z.string().nullish(),
  version: z.string(),
});

export const zDependencyKind = z.enum(['normal', 'dev', 'build']);

export const zDocNodeKind = z.enum(['file', 'dir']);

export const zDocRootEntry = z.object({
  docCount: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
  exists: z.boolean(),
  name: z.string(),
  path: z.string(),
});

export const zDocRootRegEntry = z.object({
  description: z.string().nullish(),
  enabled: z.boolean(),
  name: z.string(),
  path: z.string(),
});

export const zDocSearchMatch = z.object({
  line: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
  text: z.string(),
});

export const zDocSearchHit = z.object({
  matches: z.array(zDocSearchMatch),
  path: z.string(),
  root: z.string(),
});

export const zDocTreeNode = z.object({
  children: z.array(z.lazy((): any => zDocTreeNode)).nullish(),
  name: z.string(),
  order: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  path: z.string(),
  type: zDocNodeKind,
});

export const zDocRootTreeEntry = z.object({
  nodes: z.array(zDocTreeNode),
  root: z.string(),
});

export const zDockerActionRequest = z.object({
  action: z.string(),
  projectPath: z.string(),
  service: z.string().nullish(),
  tail: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
});

export const zDockerActionResponse = z.object({
  composeFile: z.string().nullish(),
  output: z.string(),
});

/**
 * Live CPU/memory stats for one running container.
 */
export const zDockerContainerStats = z.object({
  block_read_bytes: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    }),
  block_write_bytes: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    }),
  cpu_percent: z.number(),
  id: z.string(),
  mem_limit_mb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    }),
  mem_usage_mb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    }),
  name: z.string(),
  net_rx_bytes: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    }),
  net_tx_bytes: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    }),
});

export const zDockerEngineKind = z.enum(['colima', 'desktop', 'none']);

export const zDockerRuntimeAddRequest = z.object({
  host: z.string().nullish(),
  name: z.string(),
  socketPath: z.string().nullish(),
  url: z.string().nullish(),
});

export const zDockerRuntimeEntry = z.object({
  enabled: z.boolean(),
  host: z.string().nullish(),
  name: z.string(),
  socketPath: z.string().nullish(),
  url: z.string().nullish(),
});

export const zDockerRuntimeInfo = z.object({
  enabled: z.boolean(),
  host: z.string().nullish(),
  name: z.string(),
  socketPath: z.string().nullish(),
  url: z.string().nullish(),
});

export const zDockerService = z.object({
  health: z.string(),
  name: z.string(),
  ports: z.array(z.string()),
  running: z.boolean(),
  state: z.string(),
});

export const zDockerServiceRow = z.object({
  health: z.string(),
  name: z.string(),
  ports: z.array(z.string()),
  running: z.boolean(),
  state: z.string(),
});

export const zDockerLogProject = z.object({
  path: z.string(),
  project: z.string(),
  services: z.array(zDockerServiceRow),
});

export const zDockerServicesResponse = z.object({
  composeFile: z.string().nullish(),
  services: z.array(zDockerService),
});

export const zDoctorEntry = z.object({
  category: z.string(),
  message: z.string(),
  status: z.string(),
});

export const zErrorResponse = z.object({
  error: z.string(),
});

/**
 * `exclusiveMinimum`/`exclusiveMaximum`: numeric in draft-06+, boolean in draft-4.
 */
export const zExclusiveLimit = z.union([z.number(), z.boolean()]);

export const zFsEntry = z.object({
  name: z.string(),
  path: z.string(),
});

export const zFsBrowseResponse = z.object({
  entries: z.array(zFsEntry),
  parent: z.string().nullish(),
  path: z.string(),
  unrestrictedEnabled: z.boolean(),
});

/**
 * One GPU detected on the host.
 */
export const zGpuInfo = z.object({
  driver_install_hint: z.string().nullish(),
  driver_status: z.string().nullish(),
  name: z.string(),
  temperature_c: z.number().nullish(),
  utilization_percent: z.number().nullish(),
  vendor: z.string(),
  vram_total_mb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  vram_used_mb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
});

export const zGraphQlEnum = z.object({
  description: z.string().nullish(),
  name: z.string(),
  values: z.array(z.string()),
});

export const zGraphQlField = z.object({
  description: z.string().nullish(),
  name: z.string(),
  required: z.boolean(),
  typeName: z.string(),
});

export const zGraphQlOperation = z.object({
  args: z.array(zGraphQlField),
  deprecated: z.boolean(),
  description: z.string().nullish(),
  name: z.string(),
  returns: z.string(),
});

export const zGraphQlType = z.object({
  description: z.string().nullish(),
  fields: z.array(zGraphQlField),
  name: z.string(),
});

export const zGraphQlInfo = z.object({
  enums: z.array(zGraphQlEnum),
  inputs: z.array(zGraphQlType),
  mutations: z.array(zGraphQlOperation),
  queries: z.array(zGraphQlOperation),
  repo: z.string(),
  subscriptions: z.array(zGraphQlOperation),
  types: z.array(zGraphQlType),
});

export const zGraphqlDownloadQuery = z.object({
  format: z.string().nullish(),
});

export const zGraphqlProxyRequest = z.object({
  operationName: z.string().nullish(),
  query: z.string(),
  shop: z.string(),
  token: z.string(),
  variables: z.unknown().optional(),
});

export const zHealthCheck = z.object({
  label: z.string(),
  ok: z.boolean(),
  output: z.string(),
  tool: z.string(),
});

export const zHealthResponse = z.object({
  checks: z.array(zHealthCheck),
  timestamp: z.string(),
});

export const zHostChannel = z.object({
  detected_at: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  key: z.string(),
  source: z.string(),
  value: z.string(),
});

/**
 * Primitive JSON Schema instance types.
 */
export const zInstanceType = z.enum([
  'null',
  'boolean',
  'object',
  'array',
  'number',
  'integer',
  'string',
]);

export const zJiraIssuesQuery = z.object({
  jql: z.string().nullish(),
  maxResults: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
});

export const zJobStatus = z.object({
  job_name: z.string(),
  last_run_duration_ms: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  last_run_error: z.string().nullish(),
  last_run_finished: z.string().nullish(),
  last_run_ok: z.boolean().nullish(),
  last_run_started: z.string().nullish(),
});

/**
 * A JSON-typed literal usable as `default`, `const`, or an `enum` entry.
 *
 * Closed over JSON's six primitive kinds plus recursion. No `Value` leak.
 */
export const zJsonLiteral = z
  .union([
    z.boolean(),
    z.number(),
    z.string(),
    z.array(z.lazy((): any => zJsonLiteral)),
    z.record(
      z.string(),
      z.lazy((): any => zJsonLiteral),
    ),
  ])
  .nullable();

export const zLlmProviderAddRequest = z.object({
  kind: z.string().nullish(),
  name: z.string(),
  url: z.string(),
});

export const zLlmProviderInfo = z.object({
  enabled: z.boolean(),
  kind: z.string(),
  name: z.string(),
  reachable: z.boolean().nullish(),
  url: z.string(),
});

export const zLogMatchEntry = z.object({
  agent: z.string().nullish(),
  contentPreview: z.string(),
  important: z.boolean(),
  role: z.string(),
  session: z.string(),
});

export const zMapRequest = z.object({
  external_tool: z.string(),
  name: z.string(),
  orca_tool: z.string(),
});

export const zMappingEntry = z.object({
  confidence: z.number().nullish(),
  enabled: z.boolean(),
  external_tool: z.string(),
  match_type: z.string(),
  mcp_name: z.string(),
  orca_tool: z.string(),
});

export const zMappingRow = z.object({
  confidence: z.number().nullish(),
  enabled: z.boolean(),
  external_tool: z.string(),
  match_type: z.string(),
  mcp_name: z.string(),
  orca_tool: z.string(),
});

export const zMcpContent = z.object({
  text: z.string(),
  type: z.string(),
});

export const zMcpRegistration = z.object({
  registered: z.boolean(),
});

export const zMcpRunRequest = z.object({
  arguments: z.unknown().optional(),
  name: z.string(),
  server: z.string(),
});

export const zMcpRunResponse = z.object({
  content: z.array(zMcpContent),
  isError: z.boolean().nullish(),
});

export const zMcpServerAddRequest = z.object({
  args: z.array(z.string()).optional(),
  command: z.string(),
  env: z.record(z.string(), z.string()).optional(),
  name: z.string(),
});

export const zMcpServerEntry = z.object({
  args: z.array(z.string()),
  command: z.string(),
  enabled: z.boolean(),
  env: z.record(z.string(), z.string()),
  name: z.string(),
});

export const zMcpServerInfo = z.object({
  args: z.array(z.string()),
  command: z.string(),
  enabled: z.boolean(),
  env: z.record(z.string(), z.string()),
  name: z.string(),
});

export const zMcpToolInfo = z.object({
  description: z.string(),
  inputSchema: z.unknown(),
  name: z.string(),
  server: z.string(),
});

export const zMeOk = z.object({
  role: z.string(),
  user_id: z.string(),
  username: z.string(),
});

export const zMemoryFile = z.object({
  content: z.string(),
  name: z.string(),
});

export const zMpcStatus = z.object({
  registered: z.boolean(),
});

export const zNetIfaceDto = z.object({
  ipv4: z.array(z.string()).optional(),
  ipv6: z.array(z.string()).optional(),
  loopback: z.boolean().optional().default(false),
  mac: z.string().nullish(),
  name: z.string(),
});

export const zNodeType = z.enum(['file', 'dir']);

export const zOkResponse = z.object({
  ok: z.boolean(),
});

export const zPathExists = z.object({
  exists: z.boolean(),
  path: z.string(),
});

export const zPathInitialized = z.object({
  initialized: z.boolean(),
  path: z.string(),
});

export const zPathInstalled = z.object({
  installed: z.boolean(),
  path: z.string(),
});

export const zPathLinked = z.object({
  linked: z.boolean(),
  path: z.string(),
});

export const zPkiCertEntry = z.object({
  cert_path: z.string(),
  plugin_id: z.string(),
});

export const zPluginCredEntry = z.object({
  key: z.string(),
  synced: z.boolean(),
  updatedAt: z.string(),
});

export const zPluginDataEntry = z.object({
  key: z.string(),
  updatedAt: z.string(),
  value: z.record(z.string(), z.unknown()),
});

export const zPluginEntry = z.object({
  enabled: z.boolean(),
  id: z.string(),
  mcpCommand: z.string().nullish(),
  mode: z.string(),
  tier: z.string(),
});

export const zPluginInfo = z.object({
  description: z.string(),
  enabled: z.boolean(),
  id: z.string(),
  mcpCommand: z.string().nullish(),
  mode: z.string(),
  navLinks: z.array(z.unknown()),
  tier: z.string(),
});

export const zPluginInstallRequest = z.object({
  instanceId: z.string().nullish(),
  manifest: z.string(),
});

export const zPluginToolCallRequest = z.object({
  arguments: z.unknown(),
  timeoutSecs: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
});

export const zPluginToolCallResponse = z.object({
  result: z.unknown(),
});

export const zPluginToolInfo = z.object({
  connected: z.boolean(),
  description: z.string(),
  fqName: z.string(),
  inputSchema: z.unknown(),
  name: z.string(),
  pluginId: z.string(),
  sensitivity: z.string(),
});

export const zPodDiscoveryRowDto = z.object({
  addr: z.string(),
  can_invite: z.boolean(),
  first_seen_at: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  hostname: z.string(),
  last_seen_at: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  peer_id: z.string().nullish(),
  port: z.int().gte(0).lte(65535),
  pubkey_fp: z.string(),
  state: z.string(),
});

export const zPodPeerAddressDto = z.object({
  kind: z.string(),
  last_seen_at: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  source: z.string(),
  value: z.string(),
});

export const zPodPendingOfferDto = z.object({
  created_at: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  direction: z.string(),
  expires_at: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  inviter_peer_id: z.string().nullish(),
  offer_id: z.string(),
  peer_addr: z.string(),
  peer_hostname: z.string(),
  peer_port: z.int().gte(0).lte(65535),
  peer_pubkey_fp: z.string(),
  pod_id: z.string().nullish(),
  ttl_secs: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
});

export const zPrQuery = z.object({
  slug: z.string(),
  workspace: z.string(),
});

export const zProfileShareEntry = z.object({
  role: z.string(),
  user_id: z.string(),
});

export const zProfileSummary = z.object({
  id: z.string(),
  is_active: z.boolean(),
  name: z.string(),
  owner_user_id: z.string(),
});

export const zProgressRequest = z.object({
  page: z.string(),
});

export const zProgressResponse = z.object({
  page: z.string().nullish(),
});

export const zProviderDto = z.object({
  created_at: z.string(),
  enabled: z.boolean(),
  kind: z.string(),
  name: z.string(),
  url: z.string(),
});

export const zRepoInfo = z.object({
  remote: z.string(),
  slug: z.string(),
  workspace: z.string(),
});

export const zScheduleEntry = z.object({
  cron: z.string(),
  host_owner: z.string(),
  is_replica: z.boolean(),
  job: z.string(),
  name: z.string(),
  next_run: z.string().nullish(),
});

export const zSchemaColumn = z.object({
  extra: z.string().optional(),
  fk_target: z.string().nullish(),
  key: z.string().optional(),
  name: z.string(),
  nullable: z.boolean().optional(),
  type: z.string(),
});

export const zSchemaDbAddRequest = z.object({
  container: z.string().nullish(),
  database: z.string(),
  domainsFile: z.string().nullish(),
  driver: z.string().optional(),
  host: z.string().nullish(),
  name: z.string(),
  password: z.string().optional(),
  port: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
  user: z.string().optional(),
});

export const zSchemaDbEntry = z.object({
  container: z.string().nullish(),
  database: z.string(),
  domainsFile: z.string().nullish(),
  driver: z.string(),
  enabled: z.boolean(),
  host: z.string().nullish(),
  name: z.string(),
  port: z.int().gte(0).lte(65535).nullish(),
  user: z.string(),
});

export const zSchemaDbInfo = z.object({
  container: z.string().nullish(),
  database: z.string(),
  domainsFile: z.string().nullish(),
  driver: z.string(),
  enabled: z.boolean(),
  host: z.string().nullish(),
  name: z.string(),
  port: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
  user: z.string(),
});

export const zSchemaDomain = z.object({
  color: z.string(),
  group: z.string().optional(),
  key: z.string(),
  label: z.string(),
  subgroup: z.string().optional(),
  tables: z.array(z.string()),
});

export const zSchemaForeignKey = z.object({
  column: z.string(),
  refColumn: z.string().nullish(),
  refTable: z.string(),
  table: z.string(),
});

export const zSchemaTableInfo = z.object({
  comment: z.string(),
  name: z.string(),
});

export const zSchemaTab = z.object({
  columns: z.record(z.string(), z.array(zSchemaColumn)),
  domains: z.array(zSchemaDomain),
  foreignKeys: z.array(zSchemaForeignKey),
  tables: z.array(zSchemaTableInfo),
  title: z.string(),
});

export const zSchemaResponse = z.object({
  errors: z.array(z.string()).nullish(),
  showTabs: z.boolean(),
  tabs: z.array(zSchemaTab),
});

/**
 * `type` may be a single instance type or an array of them.
 */
export const zSchemaType = z.union([zInstanceType, z.array(zInstanceType)]);

export const zSearchResult = z.object({
  matches: z.array(z.string()),
  path: z.string(),
  root: z.string(),
});

export const zSecretEntry = z.object({
  backend: z.string(),
  description: z.string().nullish(),
  name: z.string(),
  ref_path: z.string(),
  updated_at: z.string(),
});

export const zServiceState = z.object({
  health: z.string().nullish(),
  name: z.string(),
  ports: z.array(z.string()),
  state: z.string(),
});

export const zProjectServices = z.object({
  path: z.string(),
  project: z.string(),
  services: z.array(zServiceState),
});

export const zSessionOk = z.object({
  role: z.string(),
  user_id: z.string(),
  username: z.string(),
});

export const zSetCredRequest = z.object({
  key: z.string(),
  value: z.string(),
});

export const zSetPluginDataRequest = z.object({
  value: z.record(z.string(), z.unknown()),
});

export const zSigninRequest = z.object({
  password: z.string(),
  username: z.string(),
});

export const zSignupRequest = z.object({
  password: z.string(),
  username: z.string(),
});

export const zSignupStatus = z.object({
  allowed: z.boolean(),
  reason: z.string(),
});

export const zSpecDownloadQuery = z.object({
  format: z.string().nullish(),
});

export const zSpecFiles = z.object({
  full: z.string().nullish(),
  public: z.string().nullish(),
});

export const zSpecFilesPresence = z.object({
  full: z.boolean(),
  public: z.boolean(),
});

export const zSpecInfo = z.object({
  cachedAt: z.string().nullish(),
  enabled: z.boolean(),
  name: z.string(),
  pathCount: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
  sourceMcp: z.string().nullish(),
  url: z.string().nullish(),
});

export const zSpecMeta = z.object({
  baseUrl: z.string().nullish(),
  capturedAt: z.string().nullish(),
  description: z.string().nullish(),
  files: zSpecFiles.nullish(),
  notes: z.string().nullish(),
  pathCount: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
  project: z.string(),
  repo: z.string(),
  source: z.string(),
});

export const zSpecMetaRow = z.object({
  baseUrl: z.string().nullish(),
  capturedAt: z.string().nullish(),
  files: zSpecFilesPresence,
  hasGraphql: z.boolean(),
  namespace: z.string(),
  pathCount: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  project: z.string(),
  repo: z.string(),
  source: z.string(),
  sourceMcp: z.string().nullish(),
});

export const zSpecQuery = z.object({
  download: z.boolean().nullish(),
  format: z.string().nullish(),
});

export const zSpecRegisterRequest = z.object({
  name: z.string(),
  url: z.string(),
});

export const zSyncToolsServerEntry = z.object({
  added: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
  error: z.string().nullish(),
  server: z.string(),
  skipped: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
});

export const zSystemActionRequest = z.object({
  action: z.string(),
});

export const zSystemActionResponse = z.object({
  done: z.array(z.string()),
  errors: z.array(z.string()),
  ok: z.boolean(),
  skipped: z.array(z.string()),
});

/**
 * Cross-platform OS / hardware / process / network snapshot. Every field
 * is optional so the same shape works on macOS, Linux, and (eventually)
 * Windows — a collector failure leaves the field `None` rather than
 * breaking the whole report.
 */
export const zSystemInfoReport = z.object({
  arch: z.string().nullish(),
  boot_time_unix: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  cpu_logical: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  cpu_model: z.string().nullish(),
  cpu_physical: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  cpu_usage_percent: z.number().nullish(),
  detected_capabilities: z.array(z.string()).optional(),
  distro: z.string().nullish(),
  dmi_product: z.string().nullish(),
  dmi_vendor: z.string().nullish(),
  docker_present: z.boolean().nullish(),
  fqdn: z.string().nullish(),
  gpus: z.array(zGpuInfo).optional(),
  hostname: z.string().nullish(),
  interfaces: z.array(zNetIfaceDto).optional(),
  kernel_version: z.string().nullish(),
  load_avg_1: z.number().nullish(),
  load_avg_15: z.number().nullish(),
  load_avg_5: z.number().nullish(),
  mem_available_mb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  mem_total_mb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  mem_used_mb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  orca_dir: z.string().nullish(),
  orca_fs_avail_gb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  orca_fs_total_gb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  os_name: z.string().nullish(),
  os_version: z.string().nullish(),
  pod_paired_count: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  pod_peer_count: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  primary_ipv4: z.string().nullish(),
  primary_ipv6: z.string().nullish(),
  process_pid: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  process_rss_mb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  process_started_at_unix: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  process_threads: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  process_uptime_secs: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  proxmox_role: z.string().nullish(),
  self_secure: z.boolean().nullish(),
  snapshot_at_unix: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  swap_total_mb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  swap_used_mb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  system_type: z.string().nullish(),
  system_uptime_secs: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  virtualization: z.string().nullish(),
});

export const zHostStatusRowDto = z.object({
  peer_id: z.string(),
  received_at_unix: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  snapshot_at_unix: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  source: z.string(),
  system: zSystemInfoReport.nullish(),
});

export const zPodPeerDto = z.object({
  addr: z.string(),
  addresses: z.array(zPodPeerAddressDto).optional().default([]),
  channel: z.string().nullish(),
  frontend: z.string().nullish(),
  hostname: z.string(),
  last_seen_at: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  latency_ms: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  local: z.boolean().optional().default(false),
  local_secure: z.boolean(),
  mode: z.string().nullish(),
  peer_id: z.string(),
  peer_secure: z.boolean(),
  pinned_to: z.string().nullish(),
  port: z.int().gte(0).lte(65535),
  probe_error: z.string().nullish(),
  reachable: z.boolean().nullish(),
  status: z.string(),
  system: zSystemInfoReport.nullish(),
  target: z.string().nullish(),
  update_available: z.boolean().nullish(),
  update_latest: z.string().nullish(),
  version: z.string().nullish(),
});

export const zSystemStatusResponse = z.object({
  agents: zComponentStatus,
  binary: zComponentStatus,
  claude_md: zComponentStatus,
  mcp: zMpcStatus,
  vault: zComponentStatus,
});

export const zToolStatus = z.union([
  z.literal('ok'),
  z.literal('not_installed'),
  z.literal('errored'),
]);

export const zDenyReport = z.object({
  advisories: z.array(zDenyAdvisory),
  error: z.string().nullish(),
  status: zToolStatus,
});

export const zTransitionBody = z.object({
  transitionId: z.string(),
});

export const zTreeNode = z.object({
  children: z.array(z.lazy((): any => zTreeNode)).nullish(),
  name: z.string(),
  order: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
  path: z.string(),
  type: zNodeType,
});

export const zUnusedDependency = z.object({
  crate_name: z.string(),
  dependency: z.string(),
  kind: zDependencyKind,
});

export const zMacheteReport = z.object({
  error: z.string().nullish(),
  findings: z.array(zUnusedDependency),
  status: zToolStatus,
});

export const zUdepsReport = z.object({
  error: z.string().nullish(),
  findings: z.array(zUnusedDependency),
  status: zToolStatus,
});

/**
 * `additionalProperties` is either a bool gate or a nested schema.
 */
export const zAdditionalProperties = z.union([z.boolean(), z.lazy((): any => zJsonSchemaNode)]);

/**
 * `dependencies` (draft-07) — either a list of required keys or a sub-schema.
 */
export const zDependency = z.union([z.array(z.string()), z.lazy((): any => zJsonSchemaNode)]);

/**
 * `items` (draft-07) is either a single schema or a tuple of schemas. In
 * 2020-12 the tuple form is `prefixItems` instead — kept separately below.
 */
export const zItems = z.union([
  z.lazy((): any => zJsonSchemaNode),
  z.array(z.lazy((): any => zJsonSchemaNode)),
]);

/**
 * A JSON Schema node. Either the boolean shorthand or an object schema.
 */
export const zJsonSchemaNode = z.union([
  z.object({
    Bool: z.boolean(),
  }),
  z.object({
    Object: z.lazy((): any => zSchemaObject),
  }),
]);

export const zMcpToolEntry = z.object({
  description: z.string(),
  inputSchema: zJsonSchemaNode,
  name: z.string(),
  server: z.string(),
});

/**
 * A JSON Schema object. Every keyword is optional; unknown keywords are
 * captured into `extensions` (typed, recursive — never `Value`).
 */
export const zSchemaObject = z.object({
  additional_properties: zAdditionalProperties.nullish(),
  all_of: z.array(zJsonSchemaNode).nullish(),
  anchor: z.string().nullish(),
  any_of: z.array(zJsonSchemaNode).nullish(),
  comment: z.string().nullish(),
  const: zJsonLiteral.nullish(),
  contains: zJsonSchemaNode.nullish(),
  content_encoding: z.string().nullish(),
  content_media_type: z.string().nullish(),
  default: zJsonLiteral.nullish(),
  definitions: z.record(z.string(), zJsonSchemaNode).nullish(),
  defs: z.record(z.string(), zJsonSchemaNode).nullish(),
  dependencies: z.record(z.string(), zDependency).nullish(),
  dependent_required: z.record(z.string(), z.array(z.string())).nullish(),
  dependent_schemas: z.record(z.string(), zJsonSchemaNode).nullish(),
  deprecated: z.boolean().nullish(),
  description: z.string().nullish(),
  dynamic_ref: z.string().nullish(),
  else: zJsonSchemaNode.nullish(),
  enum: z.array(zJsonLiteral).nullish(),
  examples: z.array(zJsonLiteral).nullish(),
  exclusive_maximum: zExclusiveLimit.nullish(),
  exclusive_minimum: zExclusiveLimit.nullish(),
  extensions: z.record(z.string(), zJsonSchemaNode),
  format: z.string().nullish(),
  id: z.string().nullish(),
  if: zJsonSchemaNode.nullish(),
  items: zItems.nullish(),
  max_contains: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  max_items: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  max_length: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  max_properties: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  maximum: z.number().nullish(),
  min_contains: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  min_items: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  min_length: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  min_properties: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  minimum: z.number().nullish(),
  multiple_of: z.number().nullish(),
  not: zJsonSchemaNode.nullish(),
  one_of: z.array(zJsonSchemaNode).nullish(),
  pattern: z.string().nullish(),
  pattern_properties: z.record(z.string(), zJsonSchemaNode).nullish(),
  prefix_items: z.array(zJsonSchemaNode).nullish(),
  properties: z.record(z.string(), zJsonSchemaNode).nullish(),
  property_names: zJsonSchemaNode.nullish(),
  read_only: z.boolean().nullish(),
  reference: z.string().nullish(),
  required: z.array(z.string()).nullish(),
  schema_uri: z.string().nullish(),
  then: zJsonSchemaNode.nullish(),
  title: z.string().nullish(),
  type: zSchemaType.nullish(),
  unevaluated_items: zAdditionalProperties.nullish(),
  unevaluated_properties: zAdditionalProperties.nullish(),
  unique_items: z.boolean().nullish(),
  write_only: z.boolean().nullish(),
});

export const zAuthChangePasswordBody = zChangePasswordRequest;

/**
 * Password changed
 */
export const zAuthChangePasswordResponse = zChangePasswordOk;

/**
 * Current identity
 */
export const zAuthMeResponse = zMeOk;

export const zAuthSigninBody = zSigninRequest;

/**
 * Signed in; session cookie set
 */
export const zAuthSigninResponse = zSessionOk;

export const zAuthSignupBody = zSignupRequest;

/**
 * Account created; session cookie set
 */
export const zAuthSignupResponse = zSessionOk;

/**
 * Whether sign-up is currently allowed
 */
export const zAuthSignupStatusResponse = zSignupStatus;

export const zListBitbucketPrsQuery = z.object({
  workspace: z.string(),
  slug: z.string(),
});

/**
 * Bitbucket repos found under REBUY_ROOT
 */
export const zListBitbucketReposResponse = z.array(zRepoInfo);

export const zSearchConfluenceQuery = z.object({
  cql: z.string().optional(),
  limit: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .optional(),
});

export const zGetLibraryDocsQuery = z.object({
  q: z.string(),
  topic: z.string().optional(),
});

/**
 * Library documentation
 */
export const zGetLibraryDocsResponse = zCtx7Response;

export const zGetDocQuery = z.object({
  root: z.string(),
  path: z.string(),
  format: z.string().optional(),
});

export const zRunDockerActionBody = zDockerActionRequest;

/**
 * Action output
 */
export const zRunDockerActionResponse = zDockerActionResponse;

/**
 * All registered Docker runtimes
 */
export const zListDockerRuntimesResponse = z.array(zDockerRuntimeInfo);

export const zAddDockerRuntimeBody = zDockerRuntimeAddRequest;

export const zAddDockerRuntimeResponse = zOkResponse;

export const zRemoveDockerRuntimePath = z.object({
  name: z.string(),
});

export const zRemoveDockerRuntimeResponse = zOkResponse;

export const zGetDockerServicesQuery = z.object({
  path: z.string(),
});

/**
 * Compose file path and service list
 */
export const zGetDockerServicesResponse = zDockerServicesResponse;

/**
 * Registered LLM backends
 */
export const zListEnginesResponse = z.array(zLlmProviderInfo);

export const zAddEngineBody = zLlmProviderAddRequest;

export const zAddEngineResponse = zOkResponse;

export const zRemoveEnginePath = z.object({
  name: z.string(),
});

export const zRemoveEngineResponse = zOkResponse;

export const zDisableEnginePath = z.object({
  name: z.string(),
});

export const zDisableEngineResponse = zOkResponse;

export const zEnableEnginePath = z.object({
  name: z.string(),
});

export const zEnableEngineResponse = zOkResponse;

export const zFsBrowseQuery = z.object({
  path: z.string().optional(),
  allowAll: z.boolean().optional(),
});

export const zFsBrowseResponse2 = zFsBrowseResponse;

export const zListGithubReposQuery = z.object({
  type: z.string().optional(),
  sort: z.string().optional(),
  per_page: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .optional(),
});

export const zListGithubIssuesPath = z.object({
  owner: z.string(),
  repo: z.string(),
});

export const zListGithubIssuesQuery = z.object({
  state: z.string().optional(),
  per_page: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .optional(),
});

export const zListGithubPrsPath = z.object({
  owner: z.string(),
  repo: z.string(),
});

export const zListGithubPrsQuery = z.object({
  state: z.string().optional(),
  per_page: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .optional(),
});

export const zListJiraIssuesQuery = z.object({
  jql: z.string().optional(),
  maxResults: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .optional(),
});

export const zGetJiraTransitionsPath = z.object({
  key: z.string(),
});

export const zTransitionJiraIssueBody = zTransitionBody;

export const zTransitionJiraIssuePath = z.object({
  key: z.string(),
});

export const zTransitionJiraIssueResponse = zOkResponse;

/**
 * Last visited learning page
 */
export const zGetLearningProgressResponse = zProgressResponse;

export const zSaveLearningProgressBody = zProgressRequest;

export const zListMcpMappingsQuery = z.object({
  name: z.string().optional(),
});

export const zListMcpMappingsResponse = z.array(zMappingRow);

export const zCreateMcpMappingBody = zMapRequest;

export const zCreateMcpMappingResponse = zOkResponse;

export const zDeleteMcpMappingPath = z.object({
  orca_tool: z.string(),
});

export const zDeleteMcpMappingResponse = zOkResponse;

export const zRunMcpToolBody = zMcpRunRequest;

/**
 * Tool result
 */
export const zRunMcpToolResponse = zMcpRunResponse;

/**
 * All registered MCP servers
 */
export const zListMcpServersResponse = z.array(zMcpServerInfo);

export const zAddMcpServerBody = zMcpServerAddRequest;

export const zAddMcpServerResponse = zOkResponse;

export const zRemoveMcpServerPath = z.object({
  name: z.string(),
});

export const zRemoveMcpServerResponse = zOkResponse;

/**
 * All tools from all connected MCP servers
 */
export const zGetMcpToolsResponse = z.array(zMcpToolInfo);

/**
 * All declared plugin tools
 */
export const zListPluginToolsResponse = z.array(zPluginToolInfo);

export const zCallPluginToolBody = zPluginToolCallRequest;

export const zCallPluginToolPath = z.object({
  fq_name: z.string(),
});

/**
 * Tool result
 */
export const zCallPluginToolResponse = zPluginToolCallResponse;

/**
 * All registered plugins
 */
export const zListPluginsResponse = z.array(zPluginInfo);

export const zInstallPluginBody = zPluginInstallRequest;

/**
 * Plugin id that was installed
 */
export const zInstallPluginResponse = zOkResponse;

export const zRemovePluginPath = z.object({
  id: z.string(),
});

export const zRemovePluginResponse = zOkResponse;

export const zListPluginCredsPath = z.object({
  id: z.string(),
});

/**
 * Credential keys for plugin (no values)
 */
export const zListPluginCredsResponse = z.array(zCredInfo);

export const zSetPluginCredBody = zSetCredRequest;

export const zSetPluginCredPath = z.object({
  id: z.string(),
});

export const zSetPluginCredResponse = zOkResponse;

export const zSyncPluginCredsPath = z.object({
  id: z.string(),
});

/**
 * Number of credentials synced
 */
export const zSyncPluginCredsResponse = zOkResponse;

export const zDeletePluginCredPath = z.object({
  id: z.string(),
  key: z.string(),
});

export const zDeletePluginCredResponse = zOkResponse;

export const zListPluginDataPath = z.object({
  id: z.string(),
});

/**
 * All data entries for plugin
 */
export const zListPluginDataResponse = z.array(zPluginDataEntry);

export const zDeletePluginDataPath = z.object({
  id: z.string(),
  key: z.string(),
});

export const zDeletePluginDataResponse = zOkResponse;

export const zGetPluginDataPath = z.object({
  id: z.string(),
  key: z.string(),
});

/**
 * Data entry
 */
export const zGetPluginDataResponse = zPluginDataEntry;

export const zSetPluginDataBody = zSetPluginDataRequest;

export const zSetPluginDataPath = z.object({
  id: z.string(),
  key: z.string(),
});

export const zSetPluginDataResponse = zOkResponse;

export const zDisablePluginPath = z.object({
  id: z.string(),
});

export const zDisablePluginResponse = zOkResponse;

export const zEnablePluginPath = z.object({
  id: z.string(),
});

export const zEnablePluginResponse = zOkResponse;

export const zGetPluginHealthPath = z.object({
  id: z.string(),
});

/**
 * All service health checks
 */
export const zGetHealthResponse = zHealthResponse;

/**
 * Database schema tabs
 */
export const zGetSchemaResponse = zSchemaResponse;

/**
 * All registered schema databases
 */
export const zListSchemaDatabasesResponse = z.array(zSchemaDbInfo);

export const zAddSchemaDatabaseBody = zSchemaDbAddRequest;

export const zAddSchemaDatabaseResponse = zOkResponse;

export const zRemoveSchemaDatabasePath = z.object({
  name: z.string(),
});

export const zRemoveSchemaDatabaseResponse = zOkResponse;

export const zSearchDocsQuery = z.object({
  q: z.string().optional(),
  root: z.string().optional(),
});

/**
 * Search results
 */
export const zSearchDocsResponse = z.array(zSearchResult);

/**
 * All registered external specs
 */
export const zListSpecsResponse = z.array(zSpecMeta);

/**
 * All URL-registered specs from orca.db
 */
export const zListDbSpecsResponse = z.array(zSpecInfo);

export const zRegisterSpecBody = zSpecRegisterRequest;

/**
 * Spec fetched and stored
 */
export const zRegisterSpecResponse = zSpecInfo;

export const zSyncMcpSpecsPath = z.object({
  server: z.string(),
});

/**
 * Sync result
 */
export const zSyncMcpSpecsResponse = zOkResponse;

export const zRefreshSpecPath = z.object({
  name: z.string(),
});

/**
 * Spec refreshed from stored URL
 */
export const zRefreshSpecResponse = zSpecInfo;

export const zUnregisterSpecPath = z.object({
  name: z.string(),
});

/**
 * Spec removed from DB
 */
export const zUnregisterSpecResponse = zOkResponse;

export const zGetSpecPath = z.object({
  repo: z.string(),
});

export const zGetSpecQuery = z.object({
  format: z.string().optional(),
  download: z.boolean().optional(),
});

export const zDownloadSpecPath = z.object({
  repo: z.string(),
});

export const zDownloadSpecQuery = z.object({
  format: z.string().optional(),
});

export const zGetSpecGraphqlPath = z.object({
  repo: z.string(),
});

export const zGetSpecGraphqlQuery = z.object({
  download: z.boolean().optional(),
});

export const zDownloadGraphqlPath = z.object({
  repo: z.string(),
});

export const zDownloadGraphqlQuery = z.object({
  format: z.string().optional(),
});

export const zGetSpecGraphqlInfoPath = z.object({
  repo: z.string(),
});

/**
 * Parsed GraphQL schema — types, queries, mutations, subscriptions
 */
export const zGetSpecGraphqlInfoResponse = zGraphQlInfo;

export const zProxyGraphqlBody = zGraphqlProxyRequest;

export const zProxyGraphqlPath = z.object({
  repo: z.string(),
});

export const zGetSpecPublicPath = z.object({
  repo: z.string(),
});

export const zGetSpecPublicQuery = z.object({
  format: z.string().optional(),
  download: z.boolean().optional(),
});

export const zSystemActionHandlerBody = zSystemActionRequest;

/**
 * Action result
 */
export const zSystemActionHandlerResponse = zSystemActionResponse;

/**
 * GetDockerEngineArgs
 */
export const zDockerEngineDetailBody = z.record(z.string(), z.unknown());

/**
 * DockerEngineStatus
 *
 * Tool result
 */
export const zDockerEngineDetailResponse = z.object({
  engine: zDockerEngineKind,
  running: z.boolean(),
});

/**
 * StartDockerEngineArgs
 */
export const zDockerEngineUpdateBody = z.record(z.string(), z.unknown());

/**
 * StartDockerEngineOutput
 *
 * Tool result
 */
export const zDockerEngineUpdateResponse = z.object({
  output: z.string(),
});

/**
 * AddDockerRuntimeArgs
 */
export const zDockerRuntimeCreateBody = z.object({
  host: z.string().nullish(),
  name: z.string(),
  socketPath: z.string().nullish(),
  url: z.string().nullish(),
});

/**
 * DockerRuntimeMutationResult
 *
 * Tool result
 */
export const zDockerRuntimeCreateResponse = z.object({
  changed: z.boolean(),
  name: z.string(),
});

/**
 * RemoveDockerRuntimeArgs
 */
export const zDockerRuntimeDeleteBody = z.object({
  name: z.string(),
});

/**
 * DockerRuntimeMutationResult
 *
 * Tool result
 */
export const zDockerRuntimeDeleteResponse = z.object({
  changed: z.boolean(),
  name: z.string(),
});

/**
 * ListDockerRuntimesArgs
 */
export const zDockerRuntimeListBody = z.record(z.string(), z.unknown());

/**
 * ListDockerRuntimesOutput
 *
 * Tool result
 */
export const zDockerRuntimeListResponse = z.object({
  runtimes: z.array(zDockerRuntimeEntry),
});

/**
 * GetLogsArgs
 */
export const zDockerServiceDetailBody = z.object({
  project: z.string(),
  service: z.string().nullish(),
  tail: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
});

/**
 * GetLogsOutput
 *
 * Tool result
 */
export const zDockerServiceDetailResponse = z.object({
  output: z.string(),
});

/**
 * GetDockerServicesArgs
 */
export const zDockerServiceListBody = z.object({
  path: z.string(),
});

/**
 * DockerServicesView
 *
 * Tool result
 */
export const zDockerServiceListResponse = z.object({
  composeFile: z.string().nullish(),
  services: z.array(zDockerServiceRow),
});

/**
 * GetLogServicesArgs
 */
export const zDockerServiceListLogsBody = z.record(z.string(), z.unknown());

/**
 * GetLogServicesOutput
 *
 * Tool result
 */
export const zDockerServiceListLogsResponse = z.object({
  projects: z.array(zDockerLogProject),
});

/**
 * DockerStatsArgs
 */
export const zDockerServiceListStatsBody = z.record(z.string(), z.unknown());

/**
 * DockerStatsOutput
 *
 * Tool result
 */
export const zDockerServiceListStatsResponse = z.object({
  containers: z.array(zDockerContainerStats),
});

/**
 * RunDockerActionArgs
 */
export const zDockerServiceUpdateBody = z.object({
  action: z.string(),
  projectPath: z.string(),
  service: z.string().nullish(),
  tail: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
});

/**
 * DockerActionResult
 *
 * Tool result
 */
export const zDockerServiceUpdateResponse = z.object({
  composeFile: z.string().nullish(),
  output: z.string(),
});

/**
 * ProfileCreateArgs
 */
export const zNamespaceCreateBody = z.object({
  description: z.string().nullish(),
  name: z.string(),
});

/**
 * ProfileDetail
 *
 * Tool result
 */
export const zNamespaceCreateResponse = z.object({
  access: z.string(),
  description: z.string().nullish(),
  id: z.string(),
  name: z.string(),
  owner_user_id: z.string(),
  root: z.string(),
});

/**
 * ProfileCurrentArgs
 */
export const zNamespaceCurrentBody = z.record(z.string(), z.unknown());

/**
 * ProfileCurrentReport
 *
 * Tool result
 */
export const zNamespaceCurrentResponse = z.object({
  active: zProfileSummary.nullish(),
});

/**
 * ProfileSpecArgs
 */
export const zNamespaceDeleteBody = z.object({
  spec: z.string(),
});

/**
 * ProfileMutationResult
 *
 * Tool result
 */
export const zNamespaceDeleteResponse = z.object({
  changed: z.boolean(),
  id: z.string(),
  name: z.string(),
});

/**
 * GetFullTreeArgs
 */
export const zNamespaceDocFullTreeBody = z.object({
  raw: z.boolean().nullish(),
});

/**
 * GetFullTreeOutput
 *
 * Tool result
 */
export const zNamespaceDocFullTreeResponse = z.object({
  roots: z.array(zDocRootTreeEntry),
});

/**
 * ListCommandsArgs
 */
export const zNamespaceDocListCommandsBody = z.record(z.string(), z.unknown());

/**
 * ListCommandsOutput
 *
 * Tool result
 */
export const zNamespaceDocListCommandsResponse = z.object({
  commands: z.array(z.string()),
});

/**
 * ListRootsArgs
 */
export const zNamespaceDocListRootsBody = z.record(z.string(), z.unknown());

/**
 * ListRootsOutput
 *
 * Tool result
 */
export const zNamespaceDocListRootsResponse = z.object({
  roots: z.array(zDocRootEntry),
});

/**
 * DocIgnorePatternArgs
 */
export const zNamespaceDocPatternCreateBody = z.object({
  pattern: z.string(),
});

/**
 * DocIgnorePatternMutationResult
 *
 * Tool result
 */
export const zNamespaceDocPatternCreateResponse = z.object({
  changed: z.boolean(),
  pattern: z.string(),
});

/**
 * DocIgnorePatternArgs
 */
export const zNamespaceDocPatternDeleteBody = z.object({
  pattern: z.string(),
});

/**
 * DocIgnorePatternMutationResult
 *
 * Tool result
 */
export const zNamespaceDocPatternDeleteResponse = z.object({
  changed: z.boolean(),
  pattern: z.string(),
});

/**
 * ListDocIgnorePatternsArgs
 */
export const zNamespaceDocPatternListBody = z.record(z.string(), z.unknown());

/**
 * ListDocIgnorePatternsOutput
 *
 * Tool result
 */
export const zNamespaceDocPatternListResponse = z.object({
  patterns: z.array(z.string()),
});

/**
 * ReadDocArgs
 */
export const zNamespaceDocReadBody = z.object({
  format: z.string().nullish(),
  path: z.string(),
  root: z.string(),
});

/**
 * ReadDocOutput
 *
 * Tool result
 */
export const zNamespaceDocReadResponse = z.object({
  content: z.string(),
  path: z.string(),
  root: z.string(),
});

/**
 * AddDocRootArgs
 */
export const zNamespaceDocRootCreateBody = z.object({
  description: z.string().nullish(),
  name: z.string(),
  path: z.string(),
});

/**
 * DocRootMutationResult
 *
 * Tool result
 */
export const zNamespaceDocRootCreateResponse = z.object({
  changed: z.boolean(),
  name: z.string(),
});

/**
 * RemoveDocRootArgs
 */
export const zNamespaceDocRootDeleteBody = z.object({
  name: z.string(),
});

/**
 * DocRootMutationResult
 *
 * Tool result
 */
export const zNamespaceDocRootDeleteResponse = z.object({
  changed: z.boolean(),
  name: z.string(),
});

/**
 * ListDocRootsArgs
 */
export const zNamespaceDocRootListBody = z.record(z.string(), z.unknown());

/**
 * ListDocRootsOutput
 *
 * Tool result
 */
export const zNamespaceDocRootListResponse = z.object({
  roots: z.array(zDocRootRegEntry),
});

/**
 * SearchDocsArgs
 */
export const zNamespaceDocSearchBody = z.object({
  format: z.string().nullish(),
  query: z.string(),
  root: z.string().nullish(),
});

/**
 * SearchDocsOutput
 *
 * Tool result
 */
export const zNamespaceDocSearchResponse = z.object({
  enhancedSummary: z.string().nullish(),
  hits: z.array(zDocSearchHit),
  query: z.string(),
});

/**
 * GetTreeArgs
 */
export const zNamespaceDocTreeBody = z.object({
  path: z.string().nullish(),
  root: z.string(),
});

/**
 * GetTreeOutput
 *
 * Tool result
 */
export const zNamespaceDocTreeResponse = z.object({
  nodes: z.array(zDocTreeNode),
  path: z.string().nullish(),
  root: z.string(),
});

/**
 * ProfileListArgs
 */
export const zNamespaceListBody = z.record(z.string(), z.unknown());

/**
 * ProfileListReport
 *
 * Tool result
 */
export const zNamespaceListResponse = z.object({
  profiles: z.array(zProfileSummary),
});

/**
 * EmptyArgs
 */
export const zNamespaceProjectListBody = z.record(z.string(), z.unknown());

/**
 * ProjectsListReport
 *
 * Tool result
 */
export const zNamespaceProjectListResponse = z.object({
  projects: z.array(z.string()),
});

/**
 * AddSchemaArgs
 */
export const zNamespaceSchemaCreateBody = z.object({
  container: z.string().nullish(),
  database: z.string(),
  domainsFile: z.string().nullish(),
  host: z.string().nullish(),
  name: z.string(),
  password: z.string(),
  port: z.int().gte(0).lte(65535).nullish(),
  user: z.string(),
});

/**
 * SchemaMutationResult
 *
 * Tool result
 */
export const zNamespaceSchemaCreateResponse = z.object({
  changed: z.boolean(),
  name: z.string(),
});

/**
 * RemoveSchemaArgs
 */
export const zNamespaceSchemaDeleteBody = z.object({
  name: z.string(),
});

/**
 * SchemaMutationResult
 *
 * Tool result
 */
export const zNamespaceSchemaDeleteResponse = z.object({
  changed: z.boolean(),
  name: z.string(),
});

/**
 * ListSchemasArgs
 */
export const zNamespaceSchemaListBody = z.record(z.string(), z.unknown());

/**
 * ListSchemasOutput
 *
 * Tool result
 */
export const zNamespaceSchemaListResponse = z.object({
  schemas: z.array(zSchemaDbEntry),
});

/**
 * GetSchemaArgs
 */
export const zNamespaceSchemaViewDetailBody = z.record(z.string(), z.unknown());

/**
 * GetSchemaOutput
 *
 * Tool result
 */
export const zNamespaceSchemaViewDetailResponse = z.object({
  errors: z.array(z.string()).nullish(),
  showTabs: z.boolean(),
  tabs: z.array(zSchemaTab),
});

/**
 * GetSchemaDomainsArgs
 */
export const zNamespaceSchemaViewListBody = z.record(z.string(), z.unknown());

/**
 * GetSchemaDomainsOutput
 *
 * Tool result
 */
export const zNamespaceSchemaViewListResponse = z.object({
  domains: z.array(zSchemaDomain),
});

/**
 * ProfileShareArgs
 */
export const zNamespaceShareCreateBody = z.object({
  role: z.string(),
  spec: z.string(),
  user: z.string(),
});

/**
 * ProfileMutationResult
 *
 * Tool result
 */
export const zNamespaceShareCreateResponse = z.object({
  changed: z.boolean(),
  id: z.string(),
  name: z.string(),
});

/**
 * ProfileUnshareArgs
 */
export const zNamespaceShareDeleteBody = z.object({
  spec: z.string(),
  user: z.string(),
});

/**
 * ProfileMutationResult
 *
 * Tool result
 */
export const zNamespaceShareDeleteResponse = z.object({
  changed: z.boolean(),
  id: z.string(),
  name: z.string(),
});

/**
 * ProfileSpecArgs
 */
export const zNamespaceShareListBody = z.object({
  spec: z.string(),
});

/**
 * ProfileSharesReport
 *
 * Tool result
 */
export const zNamespaceShareListResponse = z.object({
  profile_id: z.string(),
  shares: z.array(zProfileShareEntry),
});

/**
 * ProfileShowArgs
 */
export const zNamespaceShowBody = z.object({
  spec: z.string().nullish(),
});

/**
 * ProfileDetail
 *
 * Tool result
 */
export const zNamespaceShowResponse = z.object({
  access: z.string(),
  description: z.string().nullish(),
  id: z.string(),
  name: z.string(),
  owner_user_id: z.string(),
  root: z.string(),
});

/**
 * RegisterSpecArgs
 */
export const zNamespaceSpecCreateBody = z.object({
  name: z.string(),
  url: z.string(),
});

/**
 * RegisterSpecResult
 *
 * Tool result
 */
export const zNamespaceSpecCreateResponse = z.object({
  cachedAt: z.string().nullish(),
  enabled: z.boolean(),
  name: z.string(),
  pathCount: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  sourceMcp: z.string().nullish(),
  url: z.string().nullish(),
});

/**
 * UnregisterSpecArgs
 */
export const zNamespaceSpecDeleteBody = z.object({
  name: z.string(),
});

/**
 * UnregisterSpecOutput
 *
 * Tool result
 */
export const zNamespaceSpecDeleteResponse = z.object({
  removed: z.boolean(),
});

/**
 * SpecDetailArgs
 */
export const zNamespaceSpecDetailBody = z.record(z.string(), z.unknown());

/**
 * SpecDetailReport
 *
 * Tool result
 */
export const zNamespaceSpecDetailResponse = z.object({
  spec: z.string(),
});

/**
 * GetSpecGraphqlInfoArgs
 */
export const zNamespaceSpecGraphqlDetailBody = z.object({
  repo: z.string(),
});

/**
 * GraphQlInfoData
 *
 * Tool result
 */
export const zNamespaceSpecGraphqlDetailResponse = z.object({
  enums: z.array(zGraphQlEnum),
  inputs: z.array(zGraphQlType),
  mutations: z.array(zGraphQlOperation),
  queries: z.array(zGraphQlOperation),
  repo: z.string(),
  subscriptions: z.array(zGraphQlOperation),
  types: z.array(zGraphQlType),
});

/**
 * ProxyGraphqlArgs
 *
 * `variables` is opaque — GraphQL variable maps are free-form per operation.
 */
export const zNamespaceSpecGraphqlUpdateBody = z.object({
  operation_name: z.string().nullish(),
  query: z.string(),
  repo: z.string(),
  shop: z.string(),
  token: z.string(),
  variables: z.unknown().optional(),
});

/**
 * GraphqlProxyResult
 *
 * `body` is opaque — GraphQL response shapes vary per query and are not owned by orca.
 */
export const zNamespaceSpecGraphqlUpdateResponse = z.object({
  body: z.unknown(),
  status: z.int().gte(0).lte(65535),
});

/**
 * ListSpecsArgs
 */
export const zNamespaceSpecListBody = z.record(z.string(), z.unknown());

/**
 * ListSpecsOutput
 *
 * Tool result
 */
export const zNamespaceSpecListResponse = z.object({
  specs: z.array(zSpecMetaRow),
});

/**
 * ListDbSpecsArgs
 */
export const zNamespaceSpecListDbBody = z.record(z.string(), z.unknown());

/**
 * ListDbSpecsOutput
 *
 * Tool result
 */
export const zNamespaceSpecListDbResponse = z.object({
  specs: z.array(zDbSpecRow),
});

/**
 * RefreshSpecArgs
 */
export const zNamespaceSpecRefreshBody = z.object({
  name: z.string(),
});

/**
 * RegisterSpecResult
 *
 * Tool result
 */
export const zNamespaceSpecRefreshResponse = z.object({
  cachedAt: z.string().nullish(),
  enabled: z.boolean(),
  name: z.string(),
  pathCount: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  sourceMcp: z.string().nullish(),
  url: z.string().nullish(),
});

/**
 * SyncMcpSpecsArgs
 */
export const zNamespaceSpecSyncMcpBody = z.object({
  server: z.string(),
});

/**
 * SyncMcpSpecsResult
 *
 * Tool result
 */
export const zNamespaceSpecSyncMcpResponse = z.object({
  errors: z.array(z.string()),
  server: z.string(),
  synced: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
});

/**
 * ProfileSpecArgs
 */
export const zNamespaceUseBody = z.object({
  spec: z.string(),
});

/**
 * ProfileMutationResult
 *
 * Tool result
 */
export const zNamespaceUseResponse = z.object({
  changed: z.boolean(),
  id: z.string(),
  name: z.string(),
});

/**
 * ClearArgs
 */
export const zSystemAgentBackendClearKeyBody = z.record(z.string(), z.unknown());

/**
 * ApiKeyMutationResult
 *
 * Outcome of a mutation against the encrypted API-key slot.
 */
export const zSystemAgentBackendClearKeyResponse = z.object({
  masked: z.string().nullish(),
  message: z.string(),
  present: z.boolean(),
});

/**
 * AgentBackendStatusArgs
 */
export const zSystemAgentBackendDetailBody = z.record(z.string(), z.unknown());

/**
 * AgentBackendStatusOutput
 *
 * Tool result
 */
export const zSystemAgentBackendDetailResponse = z.object({
  api_key_in_db: z.boolean(),
  api_key_masked: z.string().nullish(),
  mode: z.string(),
  overrides: z.array(zAgentBackendOverrideEntry),
  use_server_anthropic: z.boolean(),
});

/**
 * OverrideArgs
 */
export const zSystemAgentBackendOverrideBody = z.object({
  agent: z.string(),
  backend: z.string(),
});

/**
 * OverrideResult
 *
 * Tool result
 */
export const zSystemAgentBackendOverrideResponse = z.object({
  agent: z.string(),
  backend: z.string().nullish(),
  cleared: z.boolean(),
});

/**
 * SetArgs
 */
export const zSystemAgentBackendSetKeyBody = z.object({
  key: z.string(),
});

/**
 * ApiKeyMutationResult
 *
 * Outcome of a mutation against the encrypted API-key slot.
 */
export const zSystemAgentBackendSetKeyResponse = z.object({
  masked: z.string().nullish(),
  message: z.string(),
  present: z.boolean(),
});

/**
 * SetModeArgs
 */
export const zSystemAgentBackendSetModeBody = z.object({
  mode: z.string(),
});

/**
 * SetModeResult
 *
 * Tool result
 */
export const zSystemAgentBackendSetModeResponse = z.object({
  mode: z.string(),
});

/**
 * UseServerAnthropicArgs
 */
export const zSystemAgentBackendUseServerAnthropicBody = z.object({
  enabled: z.boolean(),
});

/**
 * UseServerAnthropicResult
 *
 * Tool result
 */
export const zSystemAgentBackendUseServerAnthropicResponse = z.object({
  enabled: z.boolean(),
});

/**
 * GetAgentArgs
 */
export const zSystemAgentGetBody = z.object({
  name: z.string(),
});

/**
 * GetAgentOutput
 *
 * Tool result
 */
export const zSystemAgentGetResponse = z.object({
  name: z.string(),
  prompt: z.string(),
});

/**
 * GetConfigArgs
 */
export const zSystemAgentGetConfigBody = z.object({
  name: z.string().nullish(),
});

/**
 * GetConfigOutput
 *
 * Tool result
 */
export const zSystemAgentGetConfigResponse = z.object({
  available: z.array(z.string()),
  content: z.string().nullish(),
  name: z.string().nullish(),
});

/**
 * GetContextArgs
 */
export const zSystemAgentGetContextBody = z.object({
  project: z.string(),
});

/**
 * GetContextOutput
 *
 * Tool result
 */
export const zSystemAgentGetContextResponse = z.object({
  exists: z.boolean(),
  files: z.array(zMemoryFile),
  index: z.string().nullish(),
  project: z.string(),
});

/**
 * ListAgentsArgs
 */
export const zSystemAgentListBody = z.record(z.string(), z.unknown());

/**
 * ListAgentsOutput
 *
 * Tool result
 */
export const zSystemAgentListResponse = z.object({
  agents: z.array(zAgentEntry),
});

/**
 * SearchLogsArgs
 */
export const zSystemAgentSearchLogsBody = z.object({
  query: z.string(),
});

/**
 * SearchLogsOutput
 *
 * Tool result
 */
export const zSystemAgentSearchLogsResponse = z.object({
  enhancedSummary: z.string().nullish(),
  matches: z.array(zLogMatchEntry),
  query: z.string(),
});

/**
 * AuthLoginArgs
 */
export const zSystemAuthSessionCreateBody = z.object({
  key: z.string().nullish(),
  provider: z.string(),
});

/**
 * AuthLoginOutput
 *
 * Tool result
 */
export const zSystemAuthSessionCreateResponse = z.object({
  identity: z.string().nullish(),
  provider: z.string(),
  stored: z.boolean(),
});

/**
 * AuthLogoutArgs
 */
export const zSystemAuthSessionDeleteBody = z.object({
  provider: z.string(),
});

/**
 * AuthLogoutOutput
 *
 * Tool result
 */
export const zSystemAuthSessionDeleteResponse = z.object({
  provider: z.string(),
  removed: z.boolean(),
});

/**
 * AuthStatusArgs
 */
export const zSystemAuthSessionDetailBody = z.record(z.string(), z.unknown());

/**
 * AuthStatusReport
 *
 * Tool result
 */
export const zSystemAuthSessionDetailResponse = z.object({
  providers: z.array(zAuthProviderStatus),
});

/**
 * TokenCreateArgs
 */
export const zSystemAuthTokenCreateBody = z.object({
  expires_in_days: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  name: z.string(),
  role: z.string(),
});

/**
 * TokenCreateOutput
 *
 * Tool result
 */
export const zSystemAuthTokenCreateResponse = z.object({
  id: z.string(),
  name: z.string(),
  token: z.string(),
});

/**
 * TokenRevokeArgs
 */
export const zSystemAuthTokenDeleteBody = z.object({
  id: z.string(),
});

/**
 * TokenRevokeOutput
 *
 * Tool result
 */
export const zSystemAuthTokenDeleteResponse = z.object({
  revoked: z.boolean(),
});

/**
 * TokenListArgs
 */
export const zSystemAuthTokenListBody = z.record(z.string(), z.unknown());

/**
 * TokenListOutput
 *
 * Tool result
 */
export const zSystemAuthTokenListResponse = z.object({
  tokens: z.array(zApiTokenSummary),
});

/**
 * ConfigDeleteArgs
 */
export const zSystemConfigDeleteBody = z.object({
  host: z.string().nullish(),
  name: z.string(),
  noun: z.string(),
});

/**
 * ConfigDeleteOutput
 *
 * Tool result
 */
export const zSystemConfigDeleteResponse = z.object({
  removed: z.boolean(),
});

/**
 * ConfigGetArgs
 */
export const zSystemConfigGetBody = z.object({
  name: z.string(),
  noun: z.string(),
});

/**
 * ConfigGetOutput
 *
 * Tool result
 */
export const zSystemConfigGetResponse = z.object({
  row: zConfigRowOut.nullish(),
});

/**
 * ConfigListArgs
 */
export const zSystemConfigListBody = z.object({
  host: z.string().nullish(),
  noun: z.string().nullish(),
});

/**
 * ConfigListOutput
 *
 * Tool result
 */
export const zSystemConfigListResponse = z.object({
  rows: z.array(zConfigRowOut),
});

/**
 * ConfigSetArgs
 */
export const zSystemConfigSetBody = z.object({
  host: z.string().nullish(),
  json: z.string(),
  name: z.string(),
  noun: z.string(),
});

/**
 * ConfigSetOutput
 *
 * Tool result
 */
export const zSystemConfigSetResponse = z.object({
  created: z.boolean(),
  row: zConfigRowOut,
});

/**
 * EmptyArgs
 */
export const zSystemCreateBody = z.record(z.string(), z.unknown());

/**
 * InstallReport
 *
 * Tool result
 */
export const zSystemCreateResponse = z.object({
  done: z.array(z.string()),
  errors: z.array(z.string()),
  skipped: z.array(z.string()),
});

/**
 * DbStatusArgs
 */
export const zSystemDbDetailBody = z.record(z.string(), z.unknown());

/**
 * DbStatusReport
 *
 * Tool result
 */
export const zSystemDbDetailResponse = z.object({
  current: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  pending: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
  total: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
});

/**
 * DbLifecycleUpdateArgs
 */
export const zSystemDbLifecycleUpdateBody = z.object({
  action: z.string(),
});

/**
 * DbMigrateReport
 *
 * Tool result
 */
export const zSystemDbLifecycleUpdateResponse = z.object({
  after: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  applied: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
  before: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  direction: z.string(),
});

/**
 * EmptyArgs
 */
export const zSystemDeleteBody = z.record(z.string(), z.unknown());

/**
 * InstallReport
 *
 * Tool result
 */
export const zSystemDeleteResponse = z.object({
  done: z.array(z.string()),
  errors: z.array(z.string()),
  skipped: z.array(z.string()),
});

/**
 * SystemStatusArgs
 */
export const zSystemDetailBody = z.record(z.string(), z.unknown());

/**
 * SystemStatusReport
 *
 * Tool result
 */
export const zSystemDetailResponse = z.object({
  agents: zPathLinked,
  binary: zPathInstalled,
  channel: z.string().nullish(),
  claude_md: zPathLinked,
  frontend: z.string(),
  mcp: zMcpRegistration,
  mode: z.string().nullish(),
  pinned_to: z.string().nullish(),
  pki: zPathInitialized,
  system: zSystemInfoReport.nullish(),
  target: z.string(),
  vault: zPathExists,
  version: z.string(),
});

/**
 * DoctorArgs
 */
export const zSystemDiagnosticListBody = z.record(z.string(), z.unknown());

/**
 * DoctorReport
 *
 * Tool result
 */
export const zSystemDiagnosticListResponse = z.object({
  entries: z.array(zDoctorEntry),
});

/**
 * AddArgs
 */
export const zSystemEngineCreateBody = z.object({
  kind: z.string().optional().default(''),
  name: z.string(),
  url: z.string(),
});

/**
 * EngineOpResult
 *
 * Outcome of a mutation (add/remove/enable/disable).
 */
export const zSystemEngineCreateResponse = z.object({
  message: z.string(),
});

/**
 * NameArgs
 */
export const zSystemEngineDeleteBody = z.object({
  name: z.string(),
});

/**
 * EngineOpResult
 *
 * Outcome of a mutation (add/remove/enable/disable).
 */
export const zSystemEngineDeleteResponse = z.object({
  message: z.string(),
});

/**
 * EmptyArgs
 */
export const zSystemEngineListBody = z.record(z.string(), z.unknown());

/**
 * ProviderList
 *
 * Newtype wrapping `Vec<ProviderDto>` so it crosses the WASM boundary with a
 * real TS array type (`ProviderDto[]`) instead of `any`.
 */
export const zSystemEngineListResponse = z.array(zProviderDto);

/**
 * UpdateArgs
 */
export const zSystemEngineUpdateBody = z.object({
  enabled: z.boolean(),
  name: z.string(),
});

/**
 * EngineOpResult
 *
 * Outcome of a mutation (add/remove/enable/disable).
 */
export const zSystemEngineUpdateResponse = z.object({
  message: z.string(),
});

/**
 * HealthArgs
 */
export const zSystemHealthBody = z.record(z.string(), z.unknown());

/**
 * HealthOutput
 *
 * Tool result
 */
export const zSystemHealthResponse = z.object({
  ok: z.boolean(),
});

/**
 * EmptyArgs
 */
export const zSystemHostDetailBody = z.record(z.string(), z.unknown());

/**
 * HostInfoOutput
 *
 * Tool result
 */
export const zSystemHostDetailResponse = z.object({
  channels: z.array(zHostChannel),
  display_name: z.string(),
  machine_id: z.string(),
});

/**
 * EmptyArgs
 */
export const zSystemHostRefreshBody = z.record(z.string(), z.unknown());

/**
 * HostRefreshOutput
 *
 * Tool result
 */
export const zSystemHostRefreshResponse = z.object({
  channels: z.array(zHostChannel),
});

/**
 * HostSetArgs
 */
export const zSystemHostSetBody = z.object({
  key: z.string(),
  value: z.string(),
});

/**
 * HostSetOutput
 *
 * Tool result
 */
export const zSystemHostSetResponse = z.object({
  key: z.string(),
  value: z.string(),
});

/**
 * HostStatusDetailArgs
 */
export const zSystemHostStatusDetailBody = z.object({
  limit: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  peer_id: z.string(),
  since_unix: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
});

/**
 * Array_of_HostStatusRowDto
 *
 * Tool result
 */
export const zSystemHostStatusDetailResponse = z.array(zHostStatusRowDto);

/**
 * HostStatusRowsArgs
 */
export const zSystemHostStatusListBody = z.record(z.string(), z.unknown());

/**
 * Array_of_HostStatusRowDto
 *
 * Tool result
 */
export const zSystemHostStatusListResponse = z.array(zHostStatusRowDto);

/**
 * GetServiceLogsArgs
 */
export const zSystemInfraServiceDetailBody = z.object({
  project: z.string(),
  service: z.string(),
  tail: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
});

/**
 * GetServiceLogsOutput
 *
 * Tool result
 */
export const zSystemInfraServiceDetailResponse = z.object({
  output: z.string(),
  project: z.string(),
  service: z.string(),
});

/**
 * ListServicesArgs
 */
export const zSystemInfraServiceListBody = z.record(z.string(), z.unknown());

/**
 * ListServicesOutput
 *
 * Tool result
 */
export const zSystemInfraServiceListResponse = z.object({
  projects: z.array(zProjectServices),
});

/**
 * RunTestsArgs
 */
export const zSystemInfraTestCreateBody = z.object({
  suite: z.string().nullish(),
});

/**
 * RunTestsOutput
 *
 * Tool result
 */
export const zSystemInfraTestCreateResponse = z.object({
  duration_ms: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    }),
  exit_code: z
    .int()
    .min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' })
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
  failed: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
  output: z.string(),
  passed: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
  suite: z.string(),
});

/**
 * AddMcpServerArgs
 */
export const zSystemMcpCreateBody = z.object({
  args: z.array(z.string()).nullish(),
  command: z.string(),
  env: z.record(z.string(), z.string()).nullish(),
  name: z.string(),
});

/**
 * McpServerMutationResult
 *
 * Tool result
 */
export const zSystemMcpCreateResponse = z.object({
  changed: z.boolean(),
  name: z.string(),
});

/**
 * RemoveMcpServerArgs
 */
export const zSystemMcpDeleteBody = z.object({
  name: z.string(),
});

/**
 * McpServerMutationResult
 *
 * Tool result
 */
export const zSystemMcpDeleteResponse = z.object({
  changed: z.boolean(),
  name: z.string(),
});

/**
 * RunMcpToolArgs
 */
export const zSystemMcpFederationRunBody = z.object({
  args: z.record(z.string(), z.unknown()).nullish().default(null),
  server: z.string(),
  tool: z.string(),
});

/**
 * RunMcpToolOutput
 *
 * Tool result
 */
export const zSystemMcpFederationRunResponse = z.object({
  content: z.array(zMcpContent),
  isError: z.boolean(),
});

/**
 * ListMcpServersArgs
 */
export const zSystemMcpListBody = z.record(z.string(), z.unknown());

/**
 * ListMcpServersOutput
 *
 * Tool result
 */
export const zSystemMcpListResponse = z.object({
  servers: z.array(zMcpServerEntry),
});

/**
 * MapToolArgs
 */
export const zSystemMcpMappingCreateBody = z.object({
  external_tool: z.string(),
  name: z.string(),
  orca_tool: z.string(),
});

/**
 * MapToolResult
 *
 * Tool result
 */
export const zSystemMcpMappingCreateResponse = z.object({
  external_tool: z.string(),
  mcp_name: z.string(),
  orca_tool: z.string(),
});

/**
 * UnmapToolArgs
 */
export const zSystemMcpMappingDeleteBody = z.object({
  orca_tool: z.string(),
});

/**
 * UnmapToolResult
 *
 * Tool result
 */
export const zSystemMcpMappingDeleteResponse = z.object({
  changed: z.boolean(),
  orca_tool: z.string(),
});

/**
 * ListToolMappingsArgs
 */
export const zSystemMcpMappingListBody = z.object({
  name: z.string().nullish(),
});

/**
 * ListToolMappingsOutput
 *
 * Tool result
 */
export const zSystemMcpMappingListResponse = z.object({
  mappings: z.array(zMappingEntry),
});

/**
 * SyncToolsArgs
 */
export const zSystemMcpSyncBody = z.object({
  all: z.boolean().nullish(),
  name: z.string().nullish(),
  threshold: z.number().nullish(),
});

/**
 * SyncToolsOutput
 *
 * Tool result
 */
export const zSystemMcpSyncResponse = z.object({
  results: z.array(zSyncToolsServerEntry),
});

/**
 * PeerCreateArgs
 */
export const zSystemPeerCreateBody = z.object({
  action: z.string(),
  addr: z.string().nullish(),
  code: z.string().nullish(),
  port: z.int().gte(0).lte(65535).nullish(),
});

/**
 * PeerCreateOutput
 *
 * Unified output for all three pairing roles. Only the fields relevant to
 * the chosen `action` are populated; the rest are omitted.
 */
export const zSystemPeerCreateResponse = z.object({
  action: z.string(),
  expires_at: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  inviter_addr: z.string().nullish(),
  inviter_hostname: z.string().nullish(),
  inviter_peer_id: z.string().nullish(),
  inviter_port: z.int().gte(0).lte(65535).nullish(),
  joiner_addr: z.string().nullish(),
  joiner_hostname: z.string().nullish(),
  joiner_port: z.int().gte(0).lte(65535).nullish(),
  joiner_pubkey_fp: z.string().nullish(),
  offer_id: z.string().nullish(),
  pairing_code: z.string().nullish(),
  pod_id: z.string().nullish(),
  self_secure: z.boolean().nullish(),
});

/**
 * PodLeaveArgs
 */
export const zSystemPeerDeleteBody = z.object({
  peer_id: z.string(),
});

/**
 * PodLeaveOutput
 *
 * Tool result
 */
export const zSystemPeerDeleteResponse = z.object({
  notify_result: z.string(),
  peer_id: z.string(),
  rows_removed: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
});

/**
 * PodPingArgs
 */
export const zSystemPeerDetailBody = z.object({
  peer_id: z.string(),
});

/**
 * PodPingOutput
 *
 * Tool result
 */
export const zSystemPeerDetailResponse = z.object({
  error: z.string().nullish(),
  hostname: z.string().nullish(),
  latency_ms: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
  ok: z.boolean(),
  peer_id: z.string().nullish(),
  version: z.string().nullish(),
});

/**
 * EmptyArgs
 */
export const zSystemPeerDiscoveryListBody = z.record(z.string(), z.unknown());

/**
 * Array_of_PodDiscoveryRowDto
 *
 * Tool result
 */
export const zSystemPeerDiscoveryListResponse = z.array(zPodDiscoveryRowDto);

/**
 * EmptyArgs
 */
export const zSystemPeerHandshakeListBody = z.record(z.string(), z.unknown());

/**
 * Array_of_PodPendingOfferDto
 *
 * Tool result
 */
export const zSystemPeerHandshakeListResponse = z.array(zPodPendingOfferDto);

/**
 * EmptyArgs
 */
export const zSystemPeerListBody = z.record(z.string(), z.unknown());

/**
 * Array_of_PodPeerDto
 *
 * Tool result
 */
export const zSystemPeerListResponse = z.array(zPodPeerDto);

/**
 * PodTrustArgs
 */
export const zSystemPeerUpdateBody = z.object({
  on: z.boolean(),
  peer_id: z.string(),
  push: z.boolean().optional().default(false),
});

/**
 * PodTrustOutput
 *
 * Tool result
 */
export const zSystemPeerUpdateResponse = z.object({
  local_secure: z.boolean(),
  mutual: z.boolean(),
  notify_result: z.string(),
  peer_id: z.string(),
  peer_secure: z.boolean(),
});

/**
 * PkiCaInitArgs
 */
export const zSystemPkiCaCreateBody = z.record(z.string(), z.unknown());

/**
 * PkiInitReport
 *
 * Tool result
 */
export const zSystemPkiCaCreateResponse = z.object({
  ca_path: z.string(),
  created: z.boolean(),
  server_cert_path: z.string(),
});

/**
 * PkiCertIssueArgs
 */
export const zSystemPkiCertCreateBody = z.object({
  capability: z.string().optional().default('general'),
  plugin_id: z.string(),
});

/**
 * PkiCertReport
 *
 * Tool result
 */
export const zSystemPkiCertCreateResponse = z.object({
  capability: z.string(),
  cert_path: z.string(),
  key_path: z.string(),
  plugin_id: z.string(),
});

/**
 * PkiListArgs
 */
export const zSystemPkiListBody = z.record(z.string(), z.unknown());

/**
 * PkiListReport
 *
 * Tool result
 */
export const zSystemPkiListResponse = z.object({
  certs: z.array(zPkiCertEntry),
});

/**
 * AddPluginArgs
 */
export const zSystemPluginCreateBody = z.object({
  instance_id: z.string().nullish(),
  manifest: z.string(),
});

/**
 * AddPluginOutput
 *
 * Tool result
 */
export const zSystemPluginCreateResponse = z.object({
  id: z.string(),
});

/**
 * SetPluginCredArgs
 */
export const zSystemPluginCredCreateBody = z.object({
  key: z.string(),
  plugin: z.string(),
  value: z.string(),
});

/**
 * PluginCredMutationResult
 *
 * Tool result
 */
export const zSystemPluginCredCreateResponse = z.object({
  changed: z.boolean(),
  key: z.string(),
  plugin: z.string(),
});

/**
 * RemovePluginCredArgs
 */
export const zSystemPluginCredDeleteBody = z.object({
  key: z.string(),
  plugin: z.string(),
});

/**
 * PluginCredMutationResult
 *
 * Tool result
 */
export const zSystemPluginCredDeleteResponse = z.object({
  changed: z.boolean(),
  key: z.string(),
  plugin: z.string(),
});

/**
 * ListPluginCredsArgs
 */
export const zSystemPluginCredListBody = z.object({
  plugin: z.string(),
});

/**
 * ListPluginCredsOutput
 *
 * Tool result
 */
export const zSystemPluginCredListResponse = z.object({
  credentials: z.array(zPluginCredEntry),
  plugin: z.string(),
});

/**
 * SyncPluginCredsArgs
 */
export const zSystemPluginCredSyncBody = z.object({
  plugin: z.string(),
});

/**
 * SyncPluginCredsOutput
 *
 * Tool result
 */
export const zSystemPluginCredSyncResponse = z.object({
  plugin: z.string(),
});

/**
 * GetPluginDataArgs
 */
export const zSystemPluginDataGetBody = z.object({
  key: z.string(),
  plugin: z.string(),
});

/**
 * GetPluginDataOutput
 *
 * Tool result
 */
export const zSystemPluginDataGetResponse = z.object({
  value: z.unknown(),
});

/**
 * SetPluginDataArgs
 */
export const zSystemPluginDataSetBody = z.object({
  key: z.string(),
  plugin: z.string(),
  value: z.unknown(),
});

/**
 * SetPluginDataOutput
 *
 * Tool result
 */
export const zSystemPluginDataSetResponse = z.object({
  ok: z.boolean(),
});

/**
 * PluginIdArgs
 */
export const zSystemPluginDeleteBody = z.object({
  id: z.string(),
});

/**
 * PluginMutationResult
 *
 * Tool result
 */
export const zSystemPluginDeleteResponse = z.object({
  changed: z.boolean(),
  id: z.string(),
});

/**
 * ListPluginsArgs
 */
export const zSystemPluginListBody = z.object({
  workspace: z.string().nullish(),
});

/**
 * ListPluginsOutput
 *
 * Tool result
 */
export const zSystemPluginListResponse = z.object({
  plugins: z.array(zPluginEntry),
});

/**
 * UpdatePluginArgs
 */
export const zSystemPluginUpdateBody = z.object({
  enabled: z.boolean(),
  id: z.string(),
});

/**
 * PluginMutationResult
 *
 * Tool result
 */
export const zSystemPluginUpdateResponse = z.object({
  changed: z.boolean(),
  id: z.string(),
});

/**
 * EmptyArgs
 */
export const zSystemPodDetailBody = z.record(z.string(), z.unknown());

/**
 * PodCertStatusOutput
 *
 * Tool result
 */
export const zSystemPodDetailResponse = z.object({
  bootstrap: zCertInfo.nullish(),
  ca_previous: zCertInfo.nullish(),
  founder: z.boolean(),
  leaf_client: zCertInfo.nullish(),
  leaf_server: zCertInfo.nullish(),
  member: z.boolean(),
  mesh_ca: zCertInfo.nullish(),
  self_secure: z.boolean().optional().default(false),
});

/**
 * PodUpdateArgs
 */
export const zSystemPodUpdateBody = z.object({
  peer_id: z.string().nullish(),
  self_secure: z.boolean().nullish(),
});

/**
 * PodUpdateOutput
 *
 * Tool result
 */
export const zSystemPodUpdateResponse = z.object({
  self_secure: z.boolean(),
});

/**
 * ScheduleListArgs
 */
export const zSystemScheduleListBody = z.object({
  host: z.string().nullish(),
});

/**
 * ScheduleListOutput
 *
 * Tool result
 */
export const zSystemScheduleListResponse = z.object({
  schedules: z.array(zScheduleEntry),
});

/**
 * ScheduleRunArgs
 */
export const zSystemScheduleRunBody = z.object({
  name: z.string(),
});

/**
 * ScheduleRunOutput
 *
 * Tool result
 */
export const zSystemScheduleRunResponse = z.object({
  duration_ms: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  error: z.string().nullish(),
  job: z.string(),
  ok: z.boolean(),
});

/**
 * ScheduleStatusArgs
 */
export const zSystemScheduleStatusBody = z.object({
  job: z.string().nullish(),
});

/**
 * ScheduleStatusOutput
 *
 * Tool result
 */
export const zSystemScheduleStatusResponse = z.object({
  jobs: z.array(zJobStatus),
});

/**
 * SecretBackendsArgs
 */
export const zSystemSecretBackendsBody = z.record(z.string(), z.unknown());

/**
 * SecretBackendsReport
 *
 * Tool result
 */
export const zSystemSecretBackendsResponse = z.object({
  backends: z.array(zBackendInfo),
});

/**
 * SecretDeleteArgs
 */
export const zSystemSecretDeleteBody = z.object({
  name: z.string(),
});

/**
 * SecretDeleteReport
 *
 * Tool result
 */
export const zSystemSecretDeleteResponse = z.object({
  name: z.string(),
  removed: z.boolean(),
});

/**
 * SecretGetArgs
 */
export const zSystemSecretDetailBody = z.object({
  name: z.string(),
});

/**
 * SecretGetReport
 *
 * Tool result
 */
export const zSystemSecretDetailResponse = z.object({
  backend: z.string(),
  name: z.string(),
  value: z.string(),
});

/**
 * SecretListArgs
 */
export const zSystemSecretListBody = z.record(z.string(), z.unknown());

/**
 * SecretListReport
 *
 * Tool result
 */
export const zSystemSecretListResponse = z.object({
  secrets: z.array(zSecretEntry),
});

/**
 * SecretSetArgs
 */
export const zSystemSecretSetBody = z.object({
  backend: z.string().optional().default('inline'),
  description: z.string().nullish(),
  name: z.string(),
  peer_id: z.string().nullish(),
  ref_path: z.string().nullish(),
  value: z.string().nullish(),
});

/**
 * SecretMutationReport
 *
 * Tool result
 */
export const zSystemSecretSetResponse = z.object({
  backend: z.string(),
  created: z.boolean(),
  name: z.string(),
});

/**
 * SweepOrganizationArgs
 */
export const zSystemSweepOrganizationBody = z.object({
  workspace_root: z.string().nullish(),
});

/**
 * SweepOrganizationOutput
 *
 * Tool result
 */
export const zSystemSweepOrganizationResponse = z.object({
  deny: zDenyReport,
  duration_ms: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    }),
  machete: zMacheteReport,
  udeps: zUdepsReport,
  workspace_root: z.string(),
});

/**
 * SystemUpdateArgs
 */
export const zSystemUpdateBody = z.object({
  peer_id: z.string().nullish(),
  version: z.string().nullish(),
});

/**
 * InstallReport
 *
 * Tool result
 */
export const zSystemUpdateResponse = z.object({
  done: z.array(z.string()),
  errors: z.array(z.string()),
  skipped: z.array(z.string()),
});

export const zGetTreeQuery = z.object({
  raw: z.boolean().optional(),
});

/**
 * ListMcpToolsArgs
 */
export const zSystemMcpFederationListToolsBody = z.record(z.string(), z.unknown());

/**
 * ListMcpToolsOutput
 *
 * Tool result
 */
export const zSystemMcpFederationListToolsResponse = z.object({
  tools: z.array(zMcpToolEntry),
});
