// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zAgentBackendOverrideEntry = z.object({
  agent: z.string(),
  backend: z.string(),
});

export const zAgentEntry = z.object({
  description: z.string(),
  name: z.string(),
});

export const zApiTokenSummary = z.object({
  created_at: z.string(),
  expires_at: z.string().nullish(),
  id: z.string(),
  last_used_at: z.string().nullish(),
  name: z.string(),
  role: z.string(),
});

export const zAuthErrorResponse = z.object({
  error: z.string(),
});

export const zAuthProviderStatus = z.object({
  configured: z.boolean(),
  identity: z.string().nullish(),
  provider: z.string(),
});

export const zBinaryStatus = z.object({
  installed: z.boolean(),
  path: z.string(),
});

export const zCertInfo = z.object({
  cn: z.string(),
  days_remaining: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  expires_at: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  fingerprint: z.string(),
  issued_at: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
});

export const zChangePasswordOk = z.object({
  ok: z.boolean(),
});

export const zChangePasswordRequest = z.object({
  current_password: z.string(),
  new_password: z.string(),
});

export const zClaudeMdStatus = z.object({
  linked: z.boolean(),
  path: z.string(),
});

export const zConfigRowOut = z.object({
  host_owner: z.string(),
  id: z.string(),
  is_replica: z.boolean(),
  json: z.string(),
  name: z.string(),
  noun: z.string(),
  updated_at: z.string(),
  updated_by: z.string(),
});

/**
 * Runtime snapshot of the orca daemon (pid/port/uptime + liveness).
 *
 * Surfaced as `system.detail.daemon`. The `version`, `mode`, and binary
 * path fields callers might expect already live on the parent
 * `SystemStatusReport` (sourced from the daemon state file) — don't
 * duplicate them here.
 */
export const zDaemonRuntimeStatus = z.object({
  pid: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  port: z.int().gte(0).lte(65535).nullish(),
  running: z.boolean(),
  uptime_seconds: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
});

export const zDockerContainerStats = z.object({
  block_read_bytes: z.coerce.bigint().gte(BigInt(0)).max(BigInt('18446744073709551615'), {
    error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
  }),
  block_write_bytes: z.coerce.bigint().gte(BigInt(0)).max(BigInt('18446744073709551615'), {
    error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
  }),
  cpu_percent: z.number(),
  id: z.string(),
  mem_limit_mb: z.coerce.bigint().gte(BigInt(0)).max(BigInt('18446744073709551615'), {
    error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
  }),
  mem_usage_mb: z.coerce.bigint().gte(BigInt(0)).max(BigInt('18446744073709551615'), {
    error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
  }),
  name: z.string(),
  net_rx_bytes: z.coerce.bigint().gte(BigInt(0)).max(BigInt('18446744073709551615'), {
    error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
  }),
  net_tx_bytes: z.coerce.bigint().gte(BigInt(0)).max(BigInt('18446744073709551615'), {
    error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
  }),
});

export const zDockerEngineKind = z.enum(['colima', 'desktop', 'none']);

export const zDockerEngineStatus = z.object({
  engine: zDockerEngineKind,
  running: z.boolean(),
});

export const zDockerRuntimeRow = z.object({
  enabled: z.boolean(),
  host: z.string().nullish(),
  name: z.string(),
  socketPath: z.string().nullish(),
  url: z.string().nullish(),
});

export const zDockerServiceRow = z.object({
  health: z.string(),
  name: z.string(),
  ports: z.array(z.string()),
  running: z.boolean(),
  state: z.string(),
});

export const zDockerProjectRow = z.object({
  path: z.string(),
  project: z.string(),
  services: z.array(zDockerServiceRow),
});

export const zDoctorEntry = z.object({
  category: z.string(),
  message: z.string(),
  status: z.string(),
});

/**
 * `exclusiveMinimum`/`exclusiveMaximum`: numeric in draft-06+, boolean in draft-4.
 */
export const zExclusiveLimit = z.union([z.number(), z.boolean()]);

export const zFsNodeKind = z.enum(['file', 'dir']);

export const zFsEntry = z.object({
  name: z.string(),
  path: z.string(),
  size: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  type: zFsNodeKind,
});

export const zFsRootEntry = z.object({
  description: z.string().nullish(),
  enabled: z.boolean(),
  exists: z.boolean(),
  file_count: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
  name: z.string(),
  path: z.string(),
});

export const zFsSearchMatch = z.object({
  line: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
  text: z.string(),
});

export const zFsSearchHit = z.object({
  matches: z.array(zFsSearchMatch),
  path: z.string(),
  root: z.string(),
});

export const zFsTreeNode = z.object({
  children: z.array(z.lazy((): any => zFsTreeNode)).nullish(),
  name: z.string(),
  order: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  path: z.string(),
  type: zFsNodeKind,
});

/**
 * One GPU detected on the host.
 */
export const zGpuInfo = z.object({
  driver_install_hint: z.string().nullish(),
  driver_status: z.string().nullish(),
  name: z.string(),
  temperature_c: z.number().nullish(),
  utilization_percent: z.number().nullish(),
  vendor: z.string(),
  vram_total_mb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  vram_used_mb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
});

export const zHostChannel = z.object({
  detected_at: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  key: z.string(),
  source: z.string(),
  value: z.string(),
});

/**
 * Primitive JSON Schema instance types.
 */
export const zInstanceType = z.enum([
  'null',
  'boolean',
  'object',
  'array',
  'number',
  'integer',
  'string',
]);

export const zJobStatus = z.object({
  job_name: z.string(),
  last_run_duration_ms: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  last_run_error: z.string().nullish(),
  last_run_finished: z.string().nullish(),
  last_run_ok: z.boolean().nullish(),
  last_run_started: z.string().nullish(),
});

/**
 * A JSON-typed literal usable as `default`, `const`, or an `enum` entry.
 *
 * Closed over JSON's six primitive kinds plus recursion. No `Value` leak.
 */
export const zJsonLiteral = z
  .union([
    z.boolean(),
    z.number(),
    z.string(),
    z.array(z.lazy((): any => zJsonLiteral)),
    z.record(
      z.string(),
      z.lazy((): any => zJsonLiteral),
    ),
  ])
  .nullable();

export const zMappingEntry = z.object({
  confidence: z.number().nullish(),
  enabled: z.boolean(),
  external_tool: z.string(),
  match_type: z.string(),
  mcp_name: z.string(),
  orca_tool: z.string(),
});

export const zMcpContent = z.object({
  data: z.string().nullish(),
  mimeType: z.string().nullish(),
  text: z.string().nullish(),
  type: z.string(),
});

export const zMcpServerRow = z.object({
  args: z.array(z.string()),
  command: z.string(),
  enabled: z.boolean(),
  env: z.record(z.string(), z.string()),
  mappings: z.array(zMappingEntry),
  name: z.string(),
});

export const zMcpStatus = z.object({
  registered: z.boolean(),
});

export const zMeOk = z.object({
  role: z.string(),
  user_id: z.string(),
  username: z.string(),
});

export const zNamespaceShareEntry = z.object({
  role: z.string(),
  user_id: z.string(),
});

export const zNamespaceSummary = z.object({
  id: z.string(),
  is_active: z.boolean(),
  name: z.string(),
  owner_user_id: z.string(),
});

export const zNetIfaceDto = z.object({
  ipv4: z.array(z.string()).optional(),
  ipv6: z.array(z.string()).optional(),
  loopback: z.boolean().optional().default(false),
  mac: z.string().nullish(),
  name: z.string(),
});

export const zPackageFormat = z.union([
  z.literal('deb'),
  z.literal('rpm'),
  z.literal('apk'),
  z.literal('pkgbuild'),
  z.literal('pkg'),
  z.literal('homebrew'),
  z.literal('plg'),
]);

/**
 * Per-peer outcome of a single sync (push or pull). `pod sync` returns these
 * directly so operators see exactly what happened.
 */
export const zPeerSyncReport = z.object({
  duration_ms: z.coerce.bigint().gte(BigInt(0)).max(BigInt('18446744073709551615'), {
    error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
  }),
  error: z.string().nullish(),
  hostname: z.string(),
  merged: z.int().gte(0),
  peer_id: z.string(),
  skip_reason: z.string().nullish(),
  status: z.string(),
});

export const zPendingRestart = z.object({
  age_secs: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .optional()
    .default(BigInt(0)),
  target: z.string().optional().default(''),
});

export const zPkiCertEntry = z.object({
  cert_path: z.string(),
  plugin_id: z.string(),
});

export const zPkiKind = z.enum(['ca', 'cert']);

export const zPkiStatus = z.object({
  initialized: z.boolean(),
  path: z.string(),
});

export const zPluginCredEntry = z.object({
  key: z.string(),
  synced: z.boolean(),
  updatedAt: z.string(),
});

export const zPluginRow = z.object({
  credentials: z.array(zPluginCredEntry),
  dataKeys: z.array(z.string()),
  enabled: z.boolean(),
  id: z.string(),
  tier: z.string(),
});

export const zPodDiscoveryRowDto = z.object({
  addr: z.string(),
  can_invite: z.boolean(),
  discovery_state: z.string(),
  first_seen_at: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  hostname: z.string(),
  last_seen_at: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  peer_id: z.string().nullish(),
  port: z.int().gte(0).lte(65535),
  pubkey_fp: z.string(),
});

export const zPodForgetNotice = z.object({
  peer_id: z.string(),
  result: z.string(),
});

export const zPodLeaveSelfResult = z.object({
  notify_result: z.string(),
  peer_id: z.string(),
});

export const zPodPeerAddressDto = z.object({
  kind: z.string(),
  last_seen_at: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  source: z.string(),
  value: z.string(),
});

export const zPodPendingOfferDto = z.object({
  created_at: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  direction: z.string(),
  expires_at: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  inviter_peer_id: z.string().nullish(),
  offer_id: z.string(),
  peer_addr: z.string(),
  peer_hostname: z.string(),
  peer_port: z.int().gte(0).lte(65535),
  peer_pubkey_fp: z.string(),
  pod_id: z.string().nullish(),
  ttl_secs: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
});

export const zScheduleEntry = z.object({
  cron: z.string(),
  host_owner: z.string(),
  is_replica: z.boolean(),
  job: z.string(),
  name: z.string(),
  next_run: z.string().nullish(),
});

/**
 * `type` may be a single instance type or an array of them.
 */
export const zSchemaType = z.union([zInstanceType, z.array(zInstanceType)]);

export const zSecretEntry = z.object({
  backend: z.string(),
  description: z.string().nullish(),
  name: z.string(),
  ref_path: z.string(),
  updated_at: z.string(),
});

export const zSessionOk = z.object({
  role: z.string(),
  user_id: z.string(),
  username: z.string(),
});

export const zSigninRequest = z.object({
  password: z.string(),
  username: z.string(),
});

export const zSignupRequest = z.object({
  password: z.string(),
  username: z.string(),
});

export const zSignupStatus = z.object({
  allowed: z.boolean(),
  reason: z.string(),
});

/**
 * Storage footprint snapshot — surfaces orca.db and log-dir sizes so
 * operators can spot bloat. Per project_db_size_and_retention: orca.db
 * stays small, logs go to files with size+retention.
 */
export const zStorageReport = z.object({
  db_path: z.string(),
  db_size_bytes: z.coerce.bigint().gte(BigInt(0)).max(BigInt('18446744073709551615'), {
    error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
  }),
  last_retention_sweep_at: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  logs_dir_bytes: z.coerce.bigint().gte(BigInt(0)).max(BigInt('18446744073709551615'), {
    error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
  }),
  logs_dir_path: z.string(),
});

export const zSyncToolsServerEntry = z.object({
  added: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
  error: z.string().nullish(),
  server: z.string(),
  skipped: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
});

export const zSyncToolsOutput = z.object({
  results: z.array(zSyncToolsServerEntry),
});

/**
 * One child entity a host claims to run. The inference layer matches each
 * claim's `macs` against other peers' `interfaces[].mac` to derive
 * `parent_peer_id`.
 */
export const zTopologyClaim = z.object({
  id: z.string(),
  kind: z.string(),
  macs: z.array(z.string()).optional(),
  name: z.string(),
  provider: z.string(),
  provider_instance: z.string(),
});

/**
 * Cross-platform OS / hardware / process / network snapshot. Every field
 * is optional so the same shape works on macOS, Linux, and (eventually)
 * Windows — a collector failure leaves the field `None` rather than
 * breaking the whole report.
 */
export const zSystemInfoReport = z.object({
  arch: z.string().nullish(),
  boot_time_unix: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  claims: z.array(zTopologyClaim).optional(),
  cpu_logical: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  cpu_model: z.string().nullish(),
  cpu_physical: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  cpu_usage_percent: z.number().nullish(),
  detected_capabilities: z.array(z.string()).optional(),
  distro: z.string().nullish(),
  dmi_product: z.string().nullish(),
  dmi_vendor: z.string().nullish(),
  docker_present: z.boolean().nullish(),
  fqdn: z.string().nullish(),
  gpus: z.array(zGpuInfo).optional(),
  hostname: z.string().nullish(),
  interfaces: z.array(zNetIfaceDto).optional(),
  kernel_version: z.string().nullish(),
  load_avg_1: z.number().nullish(),
  load_avg_15: z.number().nullish(),
  load_avg_5: z.number().nullish(),
  mem_available_mb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  mem_total_mb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  mem_used_mb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  mesh_listening: z.boolean().nullish(),
  mesh_port: z.int().gte(0).lte(65535).nullish(),
  orca_dir: z.string().nullish(),
  orca_fs_avail_gb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  orca_fs_total_gb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  os_name: z.string().nullish(),
  os_version: z.string().nullish(),
  parent_kind: z.string().nullish(),
  parent_peer_id: z.string().nullish(),
  pod_paired_count: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  pod_peer_count: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  primary_ipv4: z.string().nullish(),
  primary_ipv6: z.string().nullish(),
  process_pid: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  process_rss_mb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  process_started_at_unix: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  process_threads: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  process_uptime_secs: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  proxmox_role: z.string().nullish(),
  self_secure: z.boolean().nullish(),
  snapshot_at_unix: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
  swap_total_mb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  swap_used_mb: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  system_type: z.string().nullish(),
  system_uptime_secs: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  virtualization: z.string().nullish(),
});

export const zHostStatusRowDto = z.object({
  peer_id: z.string(),
  received_at_unix: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  snapshot_at_unix: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  source: z.string(),
  system: zSystemInfoReport.nullish(),
});

export const zPodPeerDto = z.object({
  addr: z.string(),
  addresses: z.array(zPodPeerAddressDto).optional().default([]),
  channel: z.string().nullish(),
  frontend: z.string().nullish(),
  hostname: z.string(),
  last_seen_at: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  latency_ms: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  local: z.boolean().optional().default(false),
  local_secure: z.boolean(),
  mode: z.string().nullish(),
  peer_id: z.string(),
  peer_secure: z.boolean(),
  pinned_to: z.string().nullish(),
  port: z.int().gte(0).lte(65535),
  probe_error: z.string().nullish(),
  reachable: z.boolean().nullish(),
  status: z.string(),
  system: zSystemInfoReport.nullish(),
  target: z.string().nullish(),
  update_available: z.boolean().nullish(),
  update_checked_secs: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  update_latest: z.string().nullish(),
  version: z.string().nullish(),
});

/**
 * Unified pod-membership view. Every row carries a `state` discriminant so
 * callers see joined members, in-flight handshakes, and mDNS-discovered
 * candidates in one shape. Replaces the previous trio of `system.peer.list`,
 * `system.peer.discovery.list`, and `system.peer.handshake.list` (2026-05-28
 * consolidation — see project_pod_peer_system_consolidation.md).
 */
export const zPodMember = z.union([zPodPeerDto, zPodPendingOfferDto, zPodDiscoveryRowDto]);

export const zVaultStatus = z.object({
  exists: z.boolean(),
  path: z.string(),
});

/**
 * Single entry in the version-picker list. Tag is the GitHub release tag
 * (with or without `v` prefix as returned by GitHub); `is_current` is true
 * when the tag matches the running binary's `CURRENT_VERSION`.
 */
export const zVersionEntry = z.object({
  is_current: z.boolean().optional().default(false),
  prerelease: z.boolean().optional().default(false),
  published_at: z.string().nullish().default(null),
  tag: z.string().optional().default(''),
});

/**
 * `additionalProperties` is either a bool gate or a nested schema.
 */
export const zAdditionalProperties = z.union([z.boolean(), z.lazy((): any => zJsonSchemaNode)]);

/**
 * `dependencies` (draft-07) — either a list of required keys or a sub-schema.
 */
export const zDependency = z.union([z.array(z.string()), z.lazy((): any => zJsonSchemaNode)]);

/**
 * `items` (draft-07) is either a single schema or a tuple of schemas. In
 * 2020-12 the tuple form is `prefixItems` instead — kept separately below.
 */
export const zItems = z.union([
  z.lazy((): any => zJsonSchemaNode),
  z.array(z.lazy((): any => zJsonSchemaNode)),
]);

/**
 * A JSON Schema node. Either the boolean shorthand or an object schema.
 */
export const zJsonSchemaNode = z.union([
  z.object({
    Bool: z.boolean(),
  }),
  z.object({
    Object: z.lazy((): any => zSchemaObject),
  }),
]);

export const zMcpToolEntry = z.object({
  description: z.string(),
  inputSchema: zJsonSchemaNode,
  name: z.string(),
  server: z.string(),
});

/**
 * A JSON Schema object. Every keyword is optional; unknown keywords are
 * captured into `extensions` (typed, recursive — never `Value`).
 */
export const zSchemaObject = z.object({
  additional_properties: zAdditionalProperties.nullish(),
  all_of: z.array(zJsonSchemaNode).nullish(),
  anchor: z.string().nullish(),
  any_of: z.array(zJsonSchemaNode).nullish(),
  comment: z.string().nullish(),
  const: zJsonLiteral.nullish(),
  contains: zJsonSchemaNode.nullish(),
  content_encoding: z.string().nullish(),
  content_media_type: z.string().nullish(),
  default: zJsonLiteral.nullish(),
  definitions: z.record(z.string(), zJsonSchemaNode).nullish(),
  defs: z.record(z.string(), zJsonSchemaNode).nullish(),
  dependencies: z.record(z.string(), zDependency).nullish(),
  dependent_required: z.record(z.string(), z.array(z.string())).nullish(),
  dependent_schemas: z.record(z.string(), zJsonSchemaNode).nullish(),
  deprecated: z.boolean().nullish(),
  description: z.string().nullish(),
  dynamic_ref: z.string().nullish(),
  else: zJsonSchemaNode.nullish(),
  enum: z.array(zJsonLiteral).nullish(),
  examples: z.array(zJsonLiteral).nullish(),
  exclusive_maximum: zExclusiveLimit.nullish(),
  exclusive_minimum: zExclusiveLimit.nullish(),
  extensions: z.record(z.string(), zJsonSchemaNode),
  format: z.string().nullish(),
  id: z.string().nullish(),
  if: zJsonSchemaNode.nullish(),
  items: zItems.nullish(),
  max_contains: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  max_items: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  max_length: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  max_properties: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  maximum: z.number().nullish(),
  min_contains: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  min_items: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  min_length: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  min_properties: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('18446744073709551615'), {
      error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
    })
    .nullish(),
  minimum: z.number().nullish(),
  multiple_of: z.number().nullish(),
  not: zJsonSchemaNode.nullish(),
  one_of: z.array(zJsonSchemaNode).nullish(),
  pattern: z.string().nullish(),
  pattern_properties: z.record(z.string(), zJsonSchemaNode).nullish(),
  prefix_items: z.array(zJsonSchemaNode).nullish(),
  properties: z.record(z.string(), zJsonSchemaNode).nullish(),
  property_names: zJsonSchemaNode.nullish(),
  read_only: z.boolean().nullish(),
  reference: z.string().nullish(),
  required: z.array(z.string()).nullish(),
  schema_uri: z.string().nullish(),
  then: zJsonSchemaNode.nullish(),
  title: z.string().nullish(),
  type: zSchemaType.nullish(),
  unevaluated_items: zAdditionalProperties.nullish(),
  unevaluated_properties: zAdditionalProperties.nullish(),
  unique_items: z.boolean().nullish(),
  write_only: z.boolean().nullish(),
});

export const zAuthChangePasswordBody = zChangePasswordRequest;

/**
 * Password changed
 */
export const zAuthChangePasswordResponse = zChangePasswordOk;

/**
 * Current identity
 */
export const zAuthMeResponse = zMeOk;

export const zAuthSigninBody = zSigninRequest;

/**
 * Signed in; session cookie set
 */
export const zAuthSigninResponse = zSessionOk;

export const zAuthSignupBody = zSignupRequest;

/**
 * Account created; session cookie set
 */
export const zAuthSignupResponse = zSessionOk;

/**
 * Whether sign-up is currently allowed
 */
export const zAuthSignupStatusResponse = zSignupStatus;

/**
 * AgentBackendDetailArgs
 */
export const zAgentBackendDetailBody = z.record(z.string(), z.unknown());

/**
 * AgentBackendStatusOutput
 *
 * Tool result
 */
export const zAgentBackendDetailResponse = z.object({
  api_key_in_db: z.boolean(),
  api_key_masked: z.string().nullish(),
  mode: z.string(),
  overrides: z.array(zAgentBackendOverrideEntry),
  use_server_anthropic: z.boolean(),
});

/**
 * AgentBackendUpdateArgs
 *
 * [MUTATES STATE] Update one or more agent-backend settings: mode, API key,
 * per-agent override, server-side Anthropic toggle. All fields optional;
 * only the supplied fields are applied. Returns the fresh full status.
 */
export const zAgentBackendUpdateBody = z.object({
  api_key: z.string().nullish().default(null),
  clear_api_key: z.boolean().optional().default(false),
  mode: z.string().nullish().default(null),
  override_agent: z.string().nullish().default(null),
  override_backend: z.string().nullish().default(null),
  use_server_anthropic: z.boolean().nullish().default(null),
});

/**
 * AgentBackendStatusOutput
 *
 * Tool result
 */
export const zAgentBackendUpdateResponse = z.object({
  api_key_in_db: z.boolean(),
  api_key_masked: z.string().nullish(),
  mode: z.string(),
  overrides: z.array(zAgentBackendOverrideEntry),
  use_server_anthropic: z.boolean(),
});

/**
 * GetAgentArgs
 */
export const zAgentGetBody = z.object({
  name: z.string(),
});

/**
 * GetAgentOutput
 *
 * Tool result
 */
export const zAgentGetResponse = z.object({
  name: z.string(),
  prompt: z.string(),
});

/**
 * ListAgentsArgs
 */
export const zAgentListBody = z.record(z.string(), z.unknown());

/**
 * ListAgentsOutput
 *
 * Tool result
 */
export const zAgentListResponse = z.object({
  agents: z.array(zAgentEntry),
});

/**
 * AgentRunArgs
 */
export const zAgentRunBody = z.object({
  agent: z.string().optional().default('wolf'),
  prompt: z.string(),
});

/**
 * AgentRunOutput
 *
 * Tool result
 */
export const zAgentRunResponse = z.object({
  delegated: z.boolean(),
  output: z.string(),
});

/**
 * LoginArgs
 */
export const zAuthLoginBody = z.object({
  password: z.string(),
  username: z.string(),
});

/**
 * LoginOutput
 *
 * Tool result
 */
export const zAuthLoginResponse = z.object({
  expires_at: z.string(),
  role: z.string(),
  user_id: z.string(),
  username: z.string(),
});

/**
 * LogoutArgs
 */
export const zAuthLogoutBody = z.record(z.string(), z.unknown());

/**
 * LogoutOutput
 *
 * Tool result
 */
export const zAuthLogoutResponse = z.object({
  revoked: z.boolean(),
});

/**
 * AuthLoginArgs
 */
export const zAuthSessionCreateBody = z.object({
  key: z.string().nullish(),
  provider: z.string(),
});

/**
 * AuthLoginOutput
 *
 * Tool result
 */
export const zAuthSessionCreateResponse = z.object({
  identity: z.string().nullish(),
  provider: z.string(),
  stored: z.boolean(),
});

/**
 * AuthLogoutArgs
 */
export const zAuthSessionDeleteBody = z.object({
  provider: z.string(),
});

/**
 * AuthLogoutOutput
 *
 * Tool result
 */
export const zAuthSessionDeleteResponse = z.object({
  provider: z.string(),
  removed: z.boolean(),
});

/**
 * AuthStatusArgs
 */
export const zAuthSessionDetailBody = z.record(z.string(), z.unknown());

/**
 * AuthStatusReport
 *
 * Tool result
 */
export const zAuthSessionDetailResponse = z.object({
  providers: z.array(zAuthProviderStatus),
});

/**
 * TokenCreateArgs
 */
export const zAuthTokenCreateBody = z.object({
  expires_in_days: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  name: z.string(),
  role: z.string(),
});

/**
 * TokenCreateOutput
 *
 * Tool result
 */
export const zAuthTokenCreateResponse = z.object({
  id: z.string(),
  name: z.string(),
  token: z.string(),
});

/**
 * TokenRevokeArgs
 */
export const zAuthTokenDeleteBody = z.object({
  id: z.string(),
});

/**
 * TokenRevokeOutput
 *
 * Tool result
 */
export const zAuthTokenDeleteResponse = z.object({
  revoked: z.boolean(),
});

/**
 * TokenListArgs
 */
export const zAuthTokenListBody = z.record(z.string(), z.unknown());

/**
 * TokenListOutput
 *
 * Tool result
 */
export const zAuthTokenListResponse = z.object({
  tokens: z.array(zApiTokenSummary),
});

/**
 * ConfigDeleteArgs
 */
export const zConfigDeleteBody = z.object({
  host: z.string().nullish(),
  name: z.string(),
  noun: z.string(),
});

/**
 * ConfigDeleteOutput
 *
 * Tool result
 */
export const zConfigDeleteResponse = z.object({
  removed: z.boolean(),
});

/**
 * ConfigGetArgs
 */
export const zConfigGetBody = z.object({
  name: z.string(),
  noun: z.string(),
});

/**
 * ConfigGetOutput
 *
 * Tool result
 */
export const zConfigGetResponse = z.object({
  row: zConfigRowOut.nullish(),
});

/**
 * ConfigListArgs
 */
export const zConfigListBody = z.object({
  host: z.string().nullish(),
  noun: z.string().nullish(),
});

/**
 * ConfigListOutput
 *
 * Tool result
 */
export const zConfigListResponse = z.object({
  rows: z.array(zConfigRowOut),
});

/**
 * ConfigSetArgs
 */
export const zConfigSetBody = z.object({
  host: z.string().nullish(),
  json: z.string(),
  name: z.string(),
  noun: z.string(),
});

/**
 * ConfigSetOutput
 *
 * Tool result
 */
export const zConfigSetResponse = z.object({
  created: z.boolean(),
  row: zConfigRowOut,
});

/**
 * DbStatusArgs
 */
export const zDbDetailBody = z.record(z.string(), z.unknown());

/**
 * DbStatusReport
 *
 * Tool result
 */
export const zDbDetailResponse = z.object({
  current: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  pending: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
  total: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
});

/**
 * DbUpdateArgs
 */
export const zDbUpdateBody = z.object({
  action: z.string(),
});

/**
 * DbMigrateReport
 *
 * Tool result
 */
export const zDbUpdateResponse = z.object({
  after: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  applied: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
  before: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  direction: z.string(),
});

/**
 * DockerDeleteArgs
 */
export const zDockerDeleteBody = z.object({
  runtime: z.string(),
});

/**
 * DockerDeleteOutput
 *
 * Tool result
 */
export const zDockerDeleteResponse = z.object({
  changed: z.boolean(),
  name: z.string(),
});

/**
 * DockerDetailArgs
 */
export const zDockerDetailBody = z.object({
  path: z.string(),
  service: z.string().nullish().default(null),
  tail: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish()
    .default(null),
});

/**
 * DockerDetailOutput
 *
 * Tool result
 */
export const zDockerDetailResponse = z.object({
  composeFile: z.string().nullish(),
  logs: z.string(),
  services: z.array(zDockerServiceRow),
  stats: z.array(zDockerContainerStats),
});

/**
 * DockerListArgs
 */
export const zDockerListBody = z.object({
  path: z.string().nullish().default(null),
  root: z.string().nullish().default(null),
});

/**
 * DockerListOutput
 *
 * Tool result
 */
export const zDockerListResponse = z.object({
  composeFile: z.string().nullish(),
  engine: zDockerEngineStatus.optional().default({ engine: 'none', running: false }),
  projects: z.array(zDockerProjectRow).optional(),
  runtimes: z.array(zDockerRuntimeRow).optional().default([]),
  services: z.array(zDockerServiceRow).optional(),
});

/**
 * DockerUpdateArgs
 */
export const zDockerUpdateBody = z.object({
  action: z.string().nullish().default(null),
  engineStart: z.boolean().optional().default(false),
  host: z.string().nullish().default(null),
  path: z.string().nullish().default(null),
  runtimeName: z.string().nullish().default(null),
  service: z.string().nullish().default(null),
  socketPath: z.string().nullish().default(null),
  tail: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish()
    .default(null),
  url: z.string().nullish().default(null),
});

/**
 * DockerUpdateOutput
 *
 * Tool result
 */
export const zDockerUpdateResponse = z.object({
  applied: z.array(z.string()).optional().default([]),
  composeFile: z.string().nullish(),
  output: z.string().optional(),
});

/**
 * FsDeleteArgs
 */
export const zFilesDeleteBody = z.object({
  path: z.string().nullish().default(null),
  removeIgnorePattern: z.string().nullish().default(null),
  unregisterRoot: z.string().nullish().default(null),
});

/**
 * FsDeleteOutput
 *
 * Tool result
 */
export const zFilesDeleteResponse = z.object({
  applied: z.array(z.string()).optional().default([]),
});

/**
 * FsListArgs
 */
export const zFilesListBody = z.object({
  path: z.string().optional().default(''),
  root: z.string().nullish(),
});

/**
 * FsListOutput
 *
 * Tool result
 */
export const zFilesListResponse = z.object({
  entries: z.array(zFsEntry).optional(),
  ignorePatterns: z.array(z.string()).optional(),
  roots: z.array(zFsRootEntry).optional(),
});

/**
 * FsReadArgs
 */
export const zFilesReadBody = z.object({
  format: z.string().nullish(),
  path: z.string(),
  root: z.string().nullish(),
});

/**
 * FsReadOutput
 *
 * Tool result
 */
export const zFilesReadResponse = z.object({
  content: z.string(),
  path: z.string(),
  root: z.string().nullish(),
});

/**
 * FsSearchArgs
 */
export const zFilesSearchBody = z.object({
  query: z.string(),
  root: z.string().nullish(),
});

/**
 * FsSearchOutput
 *
 * Tool result
 */
export const zFilesSearchResponse = z.object({
  hits: z.array(zFsSearchHit),
  query: z.string(),
});

/**
 * FsStatArgs
 */
export const zFilesStatBody = z.object({
  path: z.string(),
  root: z.string().nullish(),
});

/**
 * FsStatOutput
 *
 * Tool result
 */
export const zFilesStatResponse = z.object({
  exists: z.boolean(),
  name: z.string(),
  path: z.string(),
  size: z.coerce.bigint().gte(BigInt(0)).max(BigInt('18446744073709551615'), {
    error: 'Invalid value: Expected uint64 to be <= 18446744073709551615',
  }),
  type: zFsNodeKind,
});

/**
 * FsTreeArgs
 */
export const zFilesTreeBody = z.object({
  path: z.string().optional().default(''),
  raw: z.boolean().nullish(),
  root: z.string().nullish(),
});

/**
 * FsTreeOutput
 *
 * Tool result
 */
export const zFilesTreeResponse = z.object({
  nodes: z.array(zFsTreeNode),
});

/**
 * FsUpdateArgs
 */
export const zFilesUpdateBody = z.object({
  addIgnorePattern: z.string().nullish().default(null),
  content: z.string().nullish().default(null),
  path: z.string().nullish().default(null),
  registerRootDescription: z.string().nullish().default(null),
  registerRootName: z.string().nullish().default(null),
  registerRootPath: z.string().nullish().default(null),
});

/**
 * FsUpdateOutput
 *
 * Tool result
 */
export const zFilesUpdateResponse = z.object({
  applied: z.array(z.string()).optional().default([]),
});

/**
 * McpDeleteArgs
 */
export const zMcpDeleteBody = z.object({
  name: z.string(),
});

/**
 * McpDeleteOutput
 *
 * Tool result
 */
export const zMcpDeleteResponse = z.object({
  changed: z.boolean(),
  name: z.string(),
});

/**
 * McpListArgs
 */
export const zMcpListBody = z.record(z.string(), z.unknown());

/**
 * McpListOutput
 *
 * Tool result
 */
export const zMcpListResponse = z.object({
  servers: z.array(zMcpServerRow),
});

/**
 * McpRunArgs
 */
export const zMcpRunBody = z.object({
  args: z.record(z.string(), z.unknown()).nullish().default(null),
  server: z.string(),
  tool: z.string(),
});

/**
 * McpRunOutput
 *
 * Tool result
 */
export const zMcpRunResponse = z.object({
  content: z.array(zMcpContent),
  isError: z.boolean(),
  structuredContent: z.unknown().optional(),
});

/**
 * McpUpdateArgs
 */
export const zMcpUpdateBody = z.object({
  args: z.array(z.string()).nullish().default(null),
  command: z.string().nullish().default(null),
  env: z.record(z.string(), z.string()).nullish().default(null),
  mapExternalTool: z.string().nullish().default(null),
  mapOrcaTool: z.string().nullish().default(null),
  name: z.string().nullish().default(null),
  sync: z.boolean().optional().default(false),
  syncAll: z.boolean().optional().default(false),
  syncThreshold: z.number().nullish().default(null),
  unmapOrcaTool: z.string().nullish().default(null),
});

/**
 * McpUpdateOutput
 *
 * Tool result
 */
export const zMcpUpdateResponse = z.object({
  applied: z.array(z.string()).optional().default([]),
  sync: zSyncToolsOutput.nullish(),
});

/**
 * NamespaceShareArgs
 */
export const zNamespaceAccessCreateBody = z.object({
  role: z.string(),
  spec: z.string(),
  user: z.string(),
});

/**
 * NamespaceMutationResult
 *
 * Tool result
 */
export const zNamespaceAccessCreateResponse = z.object({
  changed: z.boolean(),
  id: z.string(),
  name: z.string(),
});

/**
 * NamespaceUnshareArgs
 */
export const zNamespaceAccessDeleteBody = z.object({
  spec: z.string(),
  user: z.string(),
});

/**
 * NamespaceMutationResult
 *
 * Tool result
 */
export const zNamespaceAccessDeleteResponse = z.object({
  changed: z.boolean(),
  id: z.string(),
  name: z.string(),
});

/**
 * NamespaceSpecArgs
 */
export const zNamespaceAccessListBody = z.object({
  spec: z.string(),
});

/**
 * NamespaceSharesReport
 *
 * Tool result
 */
export const zNamespaceAccessListResponse = z.object({
  namespace_id: z.string(),
  shares: z.array(zNamespaceShareEntry),
});

/**
 * NamespaceCreateArgs
 */
export const zNamespaceCreateBody = z.object({
  description: z.string().nullish(),
  name: z.string(),
});

/**
 * NamespaceDetail
 *
 * Tool result
 */
export const zNamespaceCreateResponse = z.object({
  access: z.string(),
  description: z.string().nullish(),
  id: z.string(),
  name: z.string(),
  owner_user_id: z.string(),
  root: z.string(),
});

/**
 * NamespaceSpecArgs
 */
export const zNamespaceDeleteBody = z.object({
  spec: z.string(),
});

/**
 * NamespaceMutationResult
 *
 * Tool result
 */
export const zNamespaceDeleteResponse = z.object({
  changed: z.boolean(),
  id: z.string(),
  name: z.string(),
});

/**
 * NamespaceShowArgs
 */
export const zNamespaceDetailBody = z.object({
  spec: z.string().nullish(),
});

/**
 * NamespaceDetail
 *
 * Tool result
 */
export const zNamespaceDetailResponse = z.object({
  access: z.string(),
  description: z.string().nullish(),
  id: z.string(),
  name: z.string(),
  owner_user_id: z.string(),
  root: z.string(),
});

/**
 * NamespaceListArgs
 */
export const zNamespaceListBody = z.record(z.string(), z.unknown());

/**
 * NamespaceListReport
 *
 * Tool result
 */
export const zNamespaceListResponse = z.object({
  namespaces: z.array(zNamespaceSummary),
});

/**
 * NamespaceSpecArgs
 */
export const zNamespaceUseBody = z.object({
  spec: z.string(),
});

/**
 * NamespaceMutationResult
 *
 * Tool result
 */
export const zNamespaceUseResponse = z.object({
  changed: z.boolean(),
  id: z.string(),
  name: z.string(),
});

/**
 * PkiCreateArgs
 */
export const zPkiCreateBody = z.object({
  capability: z.string().nullish().default(null),
  kind: zPkiKind.optional().default('ca'),
  plugin_id: z.string().nullish().default(null),
});

/**
 * PkiCreateOutput
 *
 * Tool result
 */
export const zPkiCreateResponse = z.object({
  caPath: z.string().optional(),
  capability: z.string().optional(),
  certPath: z.string().optional(),
  created: z.boolean().optional().default(false),
  keyPath: z.string().optional(),
  pluginId: z.string().optional(),
  serverCertPath: z.string().optional(),
});

/**
 * PkiListArgs
 */
export const zPkiListBody = z.record(z.string(), z.unknown());

/**
 * PkiListOutput
 *
 * Tool result
 */
export const zPkiListResponse = z.object({
  certs: z.array(zPkiCertEntry),
});

/**
 * PluginDeleteArgs
 */
export const zPluginDeleteBody = z.object({
  credKey: z.string().nullish(),
  dataKey: z.string().nullish(),
  id: z.string(),
});

/**
 * PluginDeleteOutput
 *
 * Tool result
 */
export const zPluginDeleteResponse = z.object({
  applied: z.array(z.string()).optional().default([]),
  id: z.string().optional().default(''),
});

/**
 * PluginDetailArgs
 */
export const zPluginDetailBody = z.object({
  data_key: z.string().nullish(),
  id: z.string(),
});

/**
 * PluginDetailOutput
 *
 * Tool result
 */
export const zPluginDetailResponse = z.object({
  dataValue: z.unknown().optional(),
  plugin: zPluginRow,
});

/**
 * PluginListArgs
 */
export const zPluginListBody = z.object({
  tier: z.string().nullish().default(null),
});

/**
 * PluginListOutput
 *
 * Tool result
 */
export const zPluginListResponse = z.object({
  plugins: z.array(zPluginRow),
});

/**
 * PluginUpdateArgs
 */
export const zPluginUpdateBody = z.object({
  credKey: z.string().nullish().default(null),
  credSync: z.boolean().optional().default(false),
  credValue: z.string().nullish().default(null),
  dataKey: z.string().nullish().default(null),
  dataValue: z.unknown().optional().default(null),
  enabled: z.boolean().nullish().default(null),
  id: z.string().nullish().default(null),
  instanceId: z.string().nullish().default(null),
  manifest: z.string().nullish().default(null),
});

/**
 * PluginUpdateOutput
 *
 * Tool result
 */
export const zPluginUpdateResponse = z.object({
  applied: z.array(z.string()).optional().default([]),
  installedId: z.string().nullish(),
});

/**
 * EmptyArgs
 */
export const zPodDetailBody = z.record(z.string(), z.unknown());

/**
 * PodCertStatusOutput
 *
 * Tool result
 */
export const zPodDetailResponse = z.object({
  bootstrap: zCertInfo.nullish(),
  ca_previous: zCertInfo.nullish(),
  founder: z.boolean(),
  leaf_client: zCertInfo.nullish(),
  leaf_server: zCertInfo.nullish(),
  member: z.boolean(),
  mesh_ca: zCertInfo.nullish(),
  self_secure: z.boolean().optional().default(false),
});

/**
 * PodForgetArgs
 */
export const zPodForgetBody = z.object({
  peer_id: z.string(),
});

/**
 * PodForgetOutput
 *
 * Tool result
 */
export const zPodForgetResponse = z.object({
  notified: z.array(zPodForgetNotice),
  peer_id: z.string(),
  rows_removed: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
});

/**
 * HostStatusDetailArgs
 */
export const zPodHistoryBody = z.object({
  limit: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' })
    .nullish(),
  peer_id: z.string(),
  since_unix: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
});

/**
 * Array_of_HostStatusRowDto
 *
 * Tool result
 */
export const zPodHistoryResponse = z.array(zHostStatusRowDto);

/**
 * PodJoinArgs
 */
export const zPodJoinBody = z.object({
  action: z.string(),
  addr: z.string().nullish(),
  code: z.string().nullish(),
  port: z.int().gte(0).lte(65535).nullish(),
});

/**
 * PodJoinOutput
 *
 * Output for `pod.join`, tagged by the pairing `action`. Each variant carries
 * exactly the fields its role produces — no cross-variant `Option` soup.
 */
export const zPodJoinResponse = z.union([
  z.object({
    action: z.literal('invite'),
    expires_at: z.coerce
      .bigint()
      .min(BigInt('-9223372036854775808'), {
        error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
      })
      .max(BigInt('9223372036854775807'), {
        error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
      }),
    joiner_addr: z.string(),
    joiner_hostname: z.string(),
    joiner_port: z.int().gte(0).lte(65535),
    joiner_pubkey_fp: z.string(),
    offer_id: z.string(),
    pairing_code: z.string(),
  }),
  z.object({
    action: z.literal('join'),
    inviter_addr: z.string(),
    inviter_port: z.int().gte(0).lte(65535),
    pairing_code: z.string(),
  }),
  z.object({
    action: z.literal('accept'),
    inviter_addr: z.string(),
    inviter_hostname: z.string(),
    inviter_peer_id: z.string(),
    inviter_port: z.int().gte(0).lte(65535),
    pod_id: z.string(),
    self_secure: z.boolean(),
  }),
]);

/**
 * PodLeaveArgs
 */
export const zPodKickBody = z.object({
  peer_id: z.string(),
});

/**
 * PodLeaveOutput
 *
 * Tool result
 */
export const zPodKickResponse = z.object({
  notify_result: z.string(),
  peer_id: z.string(),
  rows_removed: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
});

/**
 * EmptyArgs
 */
export const zPodLeaveBody = z.record(z.string(), z.unknown());

/**
 * PodLeaveSelfOutput
 *
 * Tool result
 */
export const zPodLeaveResponse = z.object({
  peers: z.array(zPodLeaveSelfResult),
  rows_removed: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
});

/**
 * EmptyArgs
 */
export const zPodListBody = z.record(z.string(), z.unknown());

/**
 * PodListOutput
 *
 * Tool result
 */
export const zPodListResponse = z.object({
  members: z.array(zPodMember),
});

/**
 * PodPingArgs
 */
export const zPodPingBody = z.object({
  peer_id: z.string(),
});

/**
 * PodPingOutput
 *
 * Tool result
 */
export const zPodPingResponse = z.object({
  error: z.string().nullish(),
  hostname: z.string().nullish(),
  latency_ms: z
    .int()
    .gte(0)
    .max(4294967295, { error: 'Invalid value: Expected uint32 to be <= 4294967295' }),
  ok: z.boolean(),
  peer_id: z.string().nullish(),
  version: z.string().nullish(),
});

/**
 * PodRecoverArgs
 */
export const zPodRecoverBody = z.object({
  peer_id: z.string(),
});

/**
 * PodRecoverOutput
 *
 * Tool result
 */
export const zPodRecoverResponse = z.object({
  cleared: z.boolean(),
  peer_id: z.string(),
});

/**
 * PodSyncArgs
 */
export const zPodSyncBody = z.object({
  peer: z.string().nullish(),
});

/**
 * PodSyncOutput
 *
 * Tool result
 */
export const zPodSyncResponse = z.object({
  peers: z.array(zPeerSyncReport),
});

/**
 * PodTrustArgs
 */
export const zPodTrustBody = z.object({
  on: z.boolean(),
  peer_id: z.string(),
  push: z.boolean().optional().default(false),
});

/**
 * PodTrustOutput
 *
 * Tool result
 */
export const zPodTrustResponse = z.object({
  local_secure: z.boolean(),
  mutual: z.boolean(),
  notify_result: z.string(),
  peer_id: z.string(),
  peer_secure: z.boolean(),
});

/**
 * PodUpdateArgs
 */
export const zPodUpdateBody = z.object({
  peer_id: z.string().nullish(),
  self_secure: z.boolean().nullish(),
});

/**
 * PodUpdateOutput
 *
 * Tool result
 */
export const zPodUpdateResponse = z.object({
  self_secure: z.boolean(),
});

/**
 * ScheduleListArgs
 */
export const zScheduleListBody = z.object({
  host: z.string().nullish(),
});

/**
 * ScheduleListOutput
 *
 * Tool result
 */
export const zScheduleListResponse = z.object({
  schedules: z.array(zScheduleEntry),
});

/**
 * ScheduleRunArgs
 */
export const zScheduleRunBody = z.object({
  name: z.string(),
});

/**
 * ScheduleRunOutput
 *
 * Tool result
 */
export const zScheduleRunResponse = z.object({
  duration_ms: z.coerce
    .bigint()
    .min(BigInt('-9223372036854775808'), {
      error: 'Invalid value: Expected int64 to be >= -9223372036854775808',
    })
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  error: z.string().nullish(),
  job: z.string(),
  ok: z.boolean(),
});

/**
 * ScheduleStatusArgs
 */
export const zScheduleStatusBody = z.object({
  job: z.string().nullish(),
});

/**
 * ScheduleStatusOutput
 *
 * Tool result
 */
export const zScheduleStatusResponse = z.object({
  jobs: z.array(zJobStatus),
});

/**
 * SecretDeleteArgs
 */
export const zSecretsDeleteBody = z.object({
  name: z.string(),
});

/**
 * SecretDeleteReport
 *
 * Tool result
 */
export const zSecretsDeleteResponse = z.object({
  name: z.string(),
  removed: z.boolean(),
});

/**
 * SecretGetArgs
 */
export const zSecretsDetailBody = z.object({
  name: z.string(),
});

/**
 * SecretGetReport
 *
 * Tool result
 */
export const zSecretsDetailResponse = z.object({
  backend: z.string(),
  name: z.string(),
  value: z.string(),
});

/**
 * SecretListArgs
 */
export const zSecretsListBody = z.record(z.string(), z.unknown());

/**
 * SecretListReport
 *
 * Tool result
 */
export const zSecretsListResponse = z.object({
  secrets: z.array(zSecretEntry),
});

/**
 * SecretSetArgs
 */
export const zSecretsSetBody = z.object({
  backend: z.string().optional().default('inline'),
  description: z.string().nullish(),
  name: z.string(),
  ref_path: z.string().nullish(),
  value: z.string().nullish(),
});

/**
 * SecretMutationReport
 *
 * Tool result
 */
export const zSecretsSetResponse = z.object({
  backend: z.string(),
  created: z.boolean(),
  name: z.string(),
});

/**
 * SpecDetailArgs
 */
export const zSpecDetailBody = z.record(z.string(), z.unknown());

/**
 * SpecDetailReport
 *
 * Tool result
 */
export const zSpecDetailResponse = z.object({
  spec: z.string(),
});

/**
 * PackageBuildArgs
 */
export const zSystemBuildBody = z.object({
  arch: z.string().nullish(),
  binary: z.string().nullish(),
  codesign_identity: z.string().nullish(),
  format: zPackageFormat.nullish(),
  maintainer: z.string().optional().default('Orca <noreply@orca.local>'),
  out_dir: z.string().optional().default('.'),
  pkg_sign_identity: z.string().nullish(),
  plg_binary_url: z.string().nullish(),
  plg_url: z.string().nullish(),
});

/**
 * PackageBuildOutput
 *
 * Tool result
 */
export const zSystemBuildResponse = z.object({
  arch: z.string(),
  format: zPackageFormat,
  out_dir: z.string(),
  version: z.string(),
});

/**
 * EmptyArgs
 */
export const zSystemDeleteBody = z.record(z.string(), z.unknown());

/**
 * InstallReport
 *
 * Tool result
 */
export const zSystemDeleteResponse = z.object({
  done: z.array(z.string()),
  errors: z.array(z.string()),
  skipped: z.array(z.string()),
});

/**
 * SystemStatusArgs
 */
export const zSystemDetailBody = z.record(z.string(), z.unknown());

/**
 * SystemStatusReport
 *
 * Tool result
 */
export const zSystemDetailResponse = z.object({
  agents: zClaudeMdStatus,
  binary: zBinaryStatus,
  channel: z.string().nullish(),
  channels: z.array(zHostChannel),
  claude_md: zClaudeMdStatus,
  daemon: zDaemonRuntimeStatus,
  diagnostic: z.array(zDoctorEntry),
  display_name: z.string(),
  frontend: z.string(),
  machine_id: z.string(),
  mcp: zMcpStatus,
  mode: z.string().nullish(),
  pinned_to: z.string().nullish(),
  pki: zPkiStatus,
  storage: zStorageReport,
  system: zSystemInfoReport.nullish(),
  target: z.string(),
  vault: zVaultStatus,
  version: z.string(),
});

/**
 * SystemInstallArgs
 *
 * Args for [`system_install`]. Empty by default — does the user-level
 * install. Pass `service_user` (and optional `home_dir` / `admin_pubkey`)
 * to also provision a system service user with SSH access (Linux, root).
 */
export const zSystemInstallBody = z.object({
  admin_pubkey: z.string().nullish(),
  home_dir: z.string().nullish(),
  port: z.int().gte(0).lte(65535).nullish(),
  service_user: z.string().nullish(),
});

/**
 * InstallReport
 *
 * Tool result
 */
export const zSystemInstallResponse = z.object({
  done: z.array(z.string()),
  errors: z.array(z.string()),
  skipped: z.array(z.string()),
});

/**
 * SystemKillArgs
 */
export const zSystemKillBody = z.record(z.string(), z.unknown());

/**
 * SystemKillOutput
 *
 * Tool result
 */
export const zSystemKillResponse = z.object({
  killed_patterns: z.array(z.string()),
});

/**
 * FetchReleaseAssetArgs
 *
 * Args for [`system_fetch_release_asset`].
 */
export const zSystemServeReleaseBody = z.object({
  channel: z.string().nullish(),
  target: z.string(),
  version: z.string().nullish(),
});

/**
 * FetchReleaseAssetOutput
 *
 * Result of [`system_fetch_release_asset`]. `asset_b64` is base64-STANDARD
 * of the raw binary bytes; `sha256` is the hex digest the holder verified
 * against the release `.sha256` blob (callers MUST re-verify after decode
 * before swapping).
 */
export const zSystemServeReleaseResponse = z.object({
  asset_b64: z.string(),
  sha256: z.string(),
  version: z.string(),
});

/**
 * SystemUpdateArgs
 *
 * Args for [`system_update`]. Every field is optional; omit-all = read-only
 * state probe (returns current_version / channel / pinned_to / available_versions).
 *
 * One tool, many surfaces:
 * - orca binary: `channel`, `version`, `pin`, `unpin`, `dev_source`, `clear_dev_source`
 * - system identity: `hostname`, `fqdn`
 * - addressing overrides: `lan_v4`, `lan_v6`, `tailscale_v4`, `tailscale_v6`
 * - OS package upgrade: `os_packages`
 */
export const zSystemUpdateBody = z.object({
  channel: z.string().nullish(),
  clear_dev_source: z.boolean().optional().default(false),
  daemon: z.string().nullish(),
  dev_source: z.string().nullish(),
  fqdn: z.string().nullish(),
  hostname: z.string().nullish(),
  lan_v4: z.string().nullish(),
  lan_v6: z.string().nullish(),
  os_packages: z.boolean().optional().default(false),
  refresh_host: z.boolean().optional().default(false),
  tailscale_v4: z.string().nullish(),
  tailscale_v6: z.string().nullish(),
  version: z.string().nullish(),
});

/**
 * SystemUpdateOutput
 *
 * Result of a `system.update` call.
 *
 * Every field carries `#[serde(default)]` so a controller running rc.N can
 * decode a response from a peer running rc.N-1 even when the older peer
 * omits a field that was added later. Without this, a single missing field
 * would fail the entire decode and the controller would report failure for
 * a call that actually applied successfully on the peer. See
 * [[project-update-path-fix-plan-2026-06-01]] fix #1.
 */
export const zSystemUpdateResponse = z.object({
  addressing_set: z.array(z.string()).optional().default([]),
  applied: z.string().nullish().default(null),
  available_versions: z.array(zVersionEntry).optional().default([]),
  channel: z.string().optional().default(''),
  current_version: z.string().optional().default(''),
  dev_source: z.string().nullish().default(null),
  errors: z.array(z.string()).optional().default([]),
  fqdn: z.string().nullish().default(null),
  hostname: z.string().nullish().default(null),
  latest: z.string().nullish().default(null),
  notes: z.array(z.string()).optional().default([]),
  os_package_result: z.string().nullish().default(null),
  pending_restart: zPendingRestart.nullish().default(null),
  pinned_to: z.string().nullish().default(null),
});

/**
 * McpDetailArgs
 */
export const zMcpDetailBody = z.object({
  name: z.string().nullish().default(null),
});

/**
 * McpDetailOutput
 *
 * Tool result
 */
export const zMcpDetailResponse = z.object({
  server: zMcpServerRow.nullish(),
  tools: z.array(zMcpToolEntry).optional().default([]),
});
