// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zAuthErrorResponse = z.object({
  error: z.string(),
});

export const zComponentStatus = z.object({
  installed: z.boolean(),
  path: z.string(),
});

export const zConfluenceSearchQuery = z.object({
  cql: z.string().nullish(),
  limit: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
});

export const zCredInfo = z.object({
  key: z.string(),
  synced: z.boolean(),
  updatedAt: z.string(),
});

export const zCtx7Response = z.object({
  content: z.string(),
  libraryId: z.string(),
  title: z.string(),
  topic: z.string().nullish(),
});

export const zDockerActionRequest = z.object({
  action: z.string(),
  projectPath: z.string(),
  service: z.string().nullish(),
  tail: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
});

export const zDockerActionResponse = z.object({
  composeFile: z.string().nullish(),
  output: z.string(),
});

export const zDockerRuntimeAddRequest = z.object({
  host: z.string().nullish(),
  name: z.string(),
  socketPath: z.string().nullish(),
  url: z.string().nullish(),
});

export const zDockerRuntimeInfo = z.object({
  enabled: z.boolean(),
  host: z.string().nullish(),
  name: z.string(),
  socketPath: z.string().nullish(),
  url: z.string().nullish(),
});

export const zDockerService = z.object({
  health: z.string(),
  name: z.string(),
  ports: z.array(z.string()),
  running: z.boolean(),
  state: z.string(),
});

export const zDockerServicesResponse = z.object({
  composeFile: z.string().nullish(),
  services: z.array(zDockerService),
});

export const zErrorResponse = z.object({
  error: z.string(),
});

export const zFsEntry = z.object({
  name: z.string(),
  path: z.string(),
});

export const zFsBrowseResponse = z.object({
  entries: z.array(zFsEntry),
  parent: z.string().nullish(),
  path: z.string(),
  unrestrictedEnabled: z.boolean(),
});

export const zGraphQlEnum = z.object({
  description: z.string().nullish(),
  name: z.string(),
  values: z.array(z.string()),
});

export const zGraphQlField = z.object({
  description: z.string().nullish(),
  name: z.string(),
  required: z.boolean(),
  typeName: z.string(),
});

export const zGraphQlOperation = z.object({
  args: z.array(zGraphQlField),
  deprecated: z.boolean(),
  description: z.string().nullish(),
  name: z.string(),
  returns: z.string(),
});

export const zGraphQlType = z.object({
  description: z.string().nullish(),
  fields: z.array(zGraphQlField),
  name: z.string(),
});

export const zGraphQlInfo = z.object({
  enums: z.array(zGraphQlEnum),
  inputs: z.array(zGraphQlType),
  mutations: z.array(zGraphQlOperation),
  queries: z.array(zGraphQlOperation),
  repo: z.string(),
  subscriptions: z.array(zGraphQlOperation),
  types: z.array(zGraphQlType),
});

export const zGraphqlDownloadQuery = z.object({
  format: z.string().nullish(),
});

export const zGraphqlProxyRequest = z.object({
  operationName: z.string().nullish(),
  query: z.string(),
  shop: z.string(),
  token: z.string(),
  variables: z.unknown().optional(),
});

export const zHealthCheck = z.object({
  label: z.string(),
  ok: z.boolean(),
  output: z.string(),
  tool: z.string(),
});

export const zHealthResponse = z.object({
  checks: z.array(zHealthCheck),
  timestamp: z.string(),
});

export const zJiraIssuesQuery = z.object({
  jql: z.string().nullish(),
  maxResults: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
});

export const zLlmProviderAddRequest = z.object({
  kind: z.string().nullish(),
  name: z.string(),
  url: z.string(),
});

export const zLlmProviderInfo = z.object({
  enabled: z.boolean(),
  kind: z.string(),
  name: z.string(),
  reachable: z.boolean().nullish(),
  url: z.string(),
});

export const zLogService = z.object({
  health: z.string(),
  name: z.string(),
  ports: z.array(z.string()),
  running: z.boolean(),
  state: z.string(),
});

export const zLogProject = z.object({
  path: z.string(),
  project: z.string(),
  services: z.array(zLogService),
});

export const zLogServicesResponse = z.object({
  projects: z.array(zLogProject),
});

export const zLogsResponse = z.object({
  output: z.string(),
});

export const zMapRequest = z.object({
  external_tool: z.string(),
  name: z.string(),
  orca_tool: z.string(),
});

export const zMappingRow = z.object({
  confidence: z.number().nullish(),
  enabled: z.boolean(),
  external_tool: z.string(),
  match_type: z.string(),
  mcp_name: z.string(),
  orca_tool: z.string(),
});

export const zMcpContent = z.object({
  text: z.string(),
  type: z.string(),
});

export const zMcpRunRequest = z.object({
  arguments: z.unknown().optional(),
  name: z.string(),
  server: z.string(),
});

export const zMcpRunResponse = z.object({
  content: z.array(zMcpContent),
  isError: z.boolean().nullish(),
});

export const zMcpServerAddRequest = z.object({
  args: z.array(z.string()).optional(),
  command: z.string(),
  env: z.record(z.string(), z.string()).optional(),
  name: z.string(),
});

export const zMcpServerInfo = z.object({
  args: z.array(z.string()),
  command: z.string(),
  enabled: z.boolean(),
  env: z.record(z.string(), z.string()),
  name: z.string(),
});

export const zMcpToolInfo = z.object({
  description: z.string(),
  inputSchema: z.unknown(),
  name: z.string(),
  server: z.string(),
});

export const zMeOk = z.object({
  role: z.string(),
  user_id: z.string(),
  username: z.string(),
});

export const zMpcStatus = z.object({
  registered: z.boolean(),
});

export const zNodeType = z.enum(['file', 'dir']);

export const zOkResponse = z.object({
  ok: z.boolean(),
});

export const zPluginDataEntry = z.object({
  key: z.string(),
  updatedAt: z.string(),
  value: z.record(z.string(), z.unknown()),
});

export const zPluginInfo = z.object({
  description: z.string(),
  enabled: z.boolean(),
  id: z.string(),
  mcpCommand: z.string().nullish(),
  mode: z.string(),
  navLinks: z.array(z.unknown()),
  tier: z.string(),
});

export const zPluginInstallRequest = z.object({
  instanceId: z.string().nullish(),
  manifest: z.string(),
});

export const zPluginToolCallRequest = z.object({
  arguments: z.unknown(),
  timeoutSecs: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    })
    .nullish(),
});

export const zPluginToolCallResponse = z.object({
  result: z.unknown(),
});

export const zPluginToolInfo = z.object({
  connected: z.boolean(),
  description: z.string(),
  fqName: z.string(),
  inputSchema: z.unknown(),
  name: z.string(),
  pluginId: z.string(),
  sensitivity: z.string(),
});

export const zPrQuery = z.object({
  slug: z.string(),
  workspace: z.string(),
});

export const zProgressRequest = z.object({
  page: z.string(),
});

export const zProgressResponse = z.object({
  page: z.string().nullish(),
});

export const zRepoInfo = z.object({
  remote: z.string(),
  slug: z.string(),
  workspace: z.string(),
});

export const zSchemaColumn = z.object({
  extra: z.string().optional(),
  fk_target: z.string().nullish(),
  key: z.string().optional(),
  name: z.string(),
  nullable: z.boolean().optional(),
  type: z.string(),
});

export const zSchemaDbAddRequest = z.object({
  container: z.string().nullish(),
  database: z.string(),
  domainsFile: z.string().nullish(),
  driver: z.string().optional(),
  host: z.string().nullish(),
  name: z.string(),
  password: z.string().optional(),
  port: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
  user: z.string().optional(),
});

export const zSchemaDbInfo = z.object({
  container: z.string().nullish(),
  database: z.string(),
  domainsFile: z.string().nullish(),
  driver: z.string(),
  enabled: z.boolean(),
  host: z.string().nullish(),
  name: z.string(),
  port: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
  user: z.string(),
});

export const zSchemaDomain = z.object({
  color: z.string(),
  group: z.string().optional(),
  key: z.string(),
  label: z.string(),
  subgroup: z.string().optional(),
  tables: z.array(z.string()),
});

export const zSchemaForeignKey = z.object({
  column: z.string(),
  refColumn: z.string().nullish(),
  refTable: z.string(),
  table: z.string(),
});

export const zSchemaTableInfo = z.object({
  comment: z.string(),
  name: z.string(),
});

export const zSchemaTab = z.object({
  columns: z.record(z.string(), z.array(zSchemaColumn)),
  domains: z.array(zSchemaDomain),
  foreignKeys: z.array(zSchemaForeignKey),
  tables: z.array(zSchemaTableInfo),
  title: z.string(),
});

export const zSchemaResponse = z.object({
  errors: z.array(z.string()).nullish(),
  showTabs: z.boolean(),
  tabs: z.array(zSchemaTab),
});

export const zSearchResult = z.object({
  matches: z.array(z.string()),
  path: z.string(),
  root: z.string(),
});

export const zSessionOk = z.object({
  role: z.string(),
  user_id: z.string(),
  username: z.string(),
});

export const zSetCredRequest = z.object({
  key: z.string(),
  value: z.string(),
});

export const zSetPluginDataRequest = z.object({
  value: z.record(z.string(), z.unknown()),
});

export const zSigninRequest = z.object({
  password: z.string(),
  username: z.string(),
});

export const zSignupRequest = z.object({
  password: z.string(),
  username: z.string(),
});

export const zSignupStatus = z.object({
  allowed: z.boolean(),
  reason: z.string(),
});

export const zSpecDownloadQuery = z.object({
  format: z.string().nullish(),
});

export const zSpecFiles = z.object({
  full: z.string().nullish(),
  public: z.string().nullish(),
});

export const zSpecInfo = z.object({
  cachedAt: z.string().nullish(),
  enabled: z.boolean(),
  name: z.string(),
  pathCount: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
  sourceMcp: z.string().nullish(),
  url: z.string().nullish(),
});

export const zSpecMeta = z.object({
  baseUrl: z.string().nullish(),
  capturedAt: z.string().nullish(),
  description: z.string().nullish(),
  files: zSpecFiles.nullish(),
  notes: z.string().nullish(),
  pathCount: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
  project: z.string(),
  repo: z.string(),
  source: z.string(),
});

export const zSpecQuery = z.object({
  download: z.boolean().nullish(),
  format: z.string().nullish(),
});

export const zSpecRegisterRequest = z.object({
  name: z.string(),
  url: z.string(),
});

export const zSystemActionRequest = z.object({
  action: z.string(),
});

export const zSystemActionResponse = z.object({
  done: z.array(z.string()),
  errors: z.array(z.string()),
  ok: z.boolean(),
  skipped: z.array(z.string()),
});

export const zSystemDevSyncResponse = z.object({
  already_up_to_date: z.boolean(),
  commits_pulled: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
  detail: z.string(),
});

export const zSystemStatusResponse = z.object({
  agents: zComponentStatus,
  binary: zComponentStatus,
  claude_md: zComponentStatus,
  mcp: zMpcStatus,
  vault: zComponentStatus,
});

export const zTestRunQuery = z.object({
  suite: z.string(),
});

export const zTestRunResponse = z.object({
  duration_ms: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt('9223372036854775807'), {
      error: 'Invalid value: Expected int64 to be <= 9223372036854775807',
    }),
  exit_code: z
    .int()
    .min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' })
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
  failed: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
  output: z.string(),
  passed: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
  suite: z.string(),
});

export const zTransitionBody = z.object({
  transitionId: z.string(),
});

export const zTreeNode = z.object({
  children: z.array(z.lazy((): any => zTreeNode)).nullish(),
  name: z.string(),
  order: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .nullish(),
  path: z.string(),
  type: zNodeType,
});

/**
 * Current identity
 */
export const zAuthMeResponse = zMeOk;

export const zAuthSigninBody = zSigninRequest;

/**
 * Signed in; session cookie set
 */
export const zAuthSigninResponse = zSessionOk;

export const zAuthSignupBody = zSignupRequest;

/**
 * Account created; session cookie set
 */
export const zAuthSignupResponse = zSessionOk;

/**
 * Whether sign-up is currently allowed
 */
export const zAuthSignupStatusResponse = zSignupStatus;

export const zListBitbucketPrsQuery = z.object({
  workspace: z.string(),
  slug: z.string(),
});

/**
 * Bitbucket repos found under REBUY_ROOT
 */
export const zListBitbucketReposResponse = z.array(zRepoInfo);

export const zSearchConfluenceQuery = z.object({
  cql: z.string().optional(),
  limit: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .optional(),
});

export const zGetLibraryDocsQuery = z.object({
  q: z.string(),
  topic: z.string().optional(),
});

/**
 * Library documentation
 */
export const zGetLibraryDocsResponse = zCtx7Response;

export const zGetDocQuery = z.object({
  root: z.string(),
  path: z.string(),
  format: z.string().optional(),
});

export const zRunDockerActionBody = zDockerActionRequest;

/**
 * Action output
 */
export const zRunDockerActionResponse = zDockerActionResponse;

/**
 * All registered Docker runtimes
 */
export const zListDockerRuntimesResponse = z.array(zDockerRuntimeInfo);

export const zAddDockerRuntimeBody = zDockerRuntimeAddRequest;

export const zAddDockerRuntimeResponse = zOkResponse;

export const zRemoveDockerRuntimePath = z.object({
  name: z.string(),
});

export const zRemoveDockerRuntimeResponse = zOkResponse;

export const zGetDockerServicesQuery = z.object({
  path: z.string(),
});

/**
 * Compose file path and service list
 */
export const zGetDockerServicesResponse = zDockerServicesResponse;

/**
 * Registered LLM backends
 */
export const zListEnginesResponse = z.array(zLlmProviderInfo);

export const zAddEngineBody = zLlmProviderAddRequest;

export const zAddEngineResponse = zOkResponse;

export const zRemoveEnginePath = z.object({
  name: z.string(),
});

export const zRemoveEngineResponse = zOkResponse;

export const zDisableEnginePath = z.object({
  name: z.string(),
});

export const zDisableEngineResponse = zOkResponse;

export const zEnableEnginePath = z.object({
  name: z.string(),
});

export const zEnableEngineResponse = zOkResponse;

export const zFsBrowseQuery = z.object({
  path: z.string().optional(),
  allowAll: z.boolean().optional(),
});

export const zFsBrowseResponse2 = zFsBrowseResponse;

export const zListGithubReposQuery = z.object({
  type: z.string().optional(),
  sort: z.string().optional(),
  per_page: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .optional(),
});

export const zListGithubIssuesPath = z.object({
  owner: z.string(),
  repo: z.string(),
});

export const zListGithubIssuesQuery = z.object({
  state: z.string().optional(),
  per_page: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .optional(),
});

export const zListGithubPrsPath = z.object({
  owner: z.string(),
  repo: z.string(),
});

export const zListGithubPrsQuery = z.object({
  state: z.string().optional(),
  per_page: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .optional(),
});

export const zListJiraIssuesQuery = z.object({
  jql: z.string().optional(),
  maxResults: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .optional(),
});

export const zGetJiraTransitionsPath = z.object({
  key: z.string(),
});

export const zTransitionJiraIssueBody = zTransitionBody;

export const zTransitionJiraIssuePath = z.object({
  key: z.string(),
});

export const zTransitionJiraIssueResponse = zOkResponse;

/**
 * Last visited learning page
 */
export const zGetLearningProgressResponse = zProgressResponse;

export const zSaveLearningProgressBody = zProgressRequest;

export const zGetLogsQuery = z.object({
  project: z.string(),
  service: z.string().optional(),
  tail: z
    .int()
    .gte(0)
    .max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' })
    .optional(),
});

/**
 * Log output
 */
export const zGetLogsResponse = zLogsResponse;

/**
 * All Docker projects and their service states
 */
export const zGetLogServicesResponse = zLogServicesResponse;

export const zListMcpMappingsQuery = z.object({
  name: z.string().optional(),
});

export const zListMcpMappingsResponse = z.array(zMappingRow);

export const zCreateMcpMappingBody = zMapRequest;

export const zCreateMcpMappingResponse = zOkResponse;

export const zDeleteMcpMappingPath = z.object({
  orca_tool: z.string(),
});

export const zDeleteMcpMappingResponse = zOkResponse;

export const zRunMcpToolBody = zMcpRunRequest;

/**
 * Tool result
 */
export const zRunMcpToolResponse = zMcpRunResponse;

/**
 * All registered MCP servers
 */
export const zListMcpServersResponse = z.array(zMcpServerInfo);

export const zAddMcpServerBody = zMcpServerAddRequest;

export const zAddMcpServerResponse = zOkResponse;

export const zRemoveMcpServerPath = z.object({
  name: z.string(),
});

export const zRemoveMcpServerResponse = zOkResponse;

/**
 * All tools from all connected MCP servers
 */
export const zGetMcpToolsResponse = z.array(zMcpToolInfo);

/**
 * All declared plugin tools
 */
export const zListPluginToolsResponse = z.array(zPluginToolInfo);

export const zCallPluginToolBody = zPluginToolCallRequest;

export const zCallPluginToolPath = z.object({
  fq_name: z.string(),
});

/**
 * Tool result
 */
export const zCallPluginToolResponse = zPluginToolCallResponse;

/**
 * All registered plugins
 */
export const zListPluginsResponse = z.array(zPluginInfo);

export const zInstallPluginBody = zPluginInstallRequest;

/**
 * Plugin id that was installed
 */
export const zInstallPluginResponse = zOkResponse;

export const zRemovePluginPath = z.object({
  id: z.string(),
});

export const zRemovePluginResponse = zOkResponse;

export const zListPluginCredsPath = z.object({
  id: z.string(),
});

/**
 * Credential keys for plugin (no values)
 */
export const zListPluginCredsResponse = z.array(zCredInfo);

export const zSetPluginCredBody = zSetCredRequest;

export const zSetPluginCredPath = z.object({
  id: z.string(),
});

export const zSetPluginCredResponse = zOkResponse;

export const zSyncPluginCredsPath = z.object({
  id: z.string(),
});

/**
 * Number of credentials synced
 */
export const zSyncPluginCredsResponse = zOkResponse;

export const zDeletePluginCredPath = z.object({
  id: z.string(),
  key: z.string(),
});

export const zDeletePluginCredResponse = zOkResponse;

export const zListPluginDataPath = z.object({
  id: z.string(),
});

/**
 * All data entries for plugin
 */
export const zListPluginDataResponse = z.array(zPluginDataEntry);

export const zDeletePluginDataPath = z.object({
  id: z.string(),
  key: z.string(),
});

export const zDeletePluginDataResponse = zOkResponse;

export const zGetPluginDataPath = z.object({
  id: z.string(),
  key: z.string(),
});

/**
 * Data entry
 */
export const zGetPluginDataResponse = zPluginDataEntry;

export const zSetPluginDataBody = zSetPluginDataRequest;

export const zSetPluginDataPath = z.object({
  id: z.string(),
  key: z.string(),
});

export const zSetPluginDataResponse = zOkResponse;

export const zDisablePluginPath = z.object({
  id: z.string(),
});

export const zDisablePluginResponse = zOkResponse;

export const zEnablePluginPath = z.object({
  id: z.string(),
});

export const zEnablePluginResponse = zOkResponse;

export const zGetPluginHealthPath = z.object({
  id: z.string(),
});

/**
 * All service health checks
 */
export const zGetHealthResponse = zHealthResponse;

/**
 * Database schema tabs
 */
export const zGetSchemaResponse = zSchemaResponse;

/**
 * All registered schema databases
 */
export const zListSchemaDatabasesResponse = z.array(zSchemaDbInfo);

export const zAddSchemaDatabaseBody = zSchemaDbAddRequest;

export const zAddSchemaDatabaseResponse = zOkResponse;

export const zRemoveSchemaDatabasePath = z.object({
  name: z.string(),
});

export const zRemoveSchemaDatabaseResponse = zOkResponse;

export const zSearchDocsQuery = z.object({
  q: z.string().optional(),
  root: z.string().optional(),
});

/**
 * Search results
 */
export const zSearchDocsResponse = z.array(zSearchResult);

/**
 * All registered external specs
 */
export const zListSpecsResponse = z.array(zSpecMeta);

/**
 * All URL-registered specs from orca.db
 */
export const zListDbSpecsResponse = z.array(zSpecInfo);

export const zRegisterSpecBody = zSpecRegisterRequest;

/**
 * Spec fetched and stored
 */
export const zRegisterSpecResponse = zSpecInfo;

export const zSyncMcpSpecsPath = z.object({
  server: z.string(),
});

/**
 * Sync result
 */
export const zSyncMcpSpecsResponse = zOkResponse;

export const zRefreshSpecPath = z.object({
  name: z.string(),
});

/**
 * Spec refreshed from stored URL
 */
export const zRefreshSpecResponse = zSpecInfo;

export const zUnregisterSpecPath = z.object({
  name: z.string(),
});

/**
 * Spec removed from DB
 */
export const zUnregisterSpecResponse = zOkResponse;

export const zGetSpecPath = z.object({
  repo: z.string(),
});

export const zGetSpecQuery = z.object({
  format: z.string().optional(),
  download: z.boolean().optional(),
});

export const zDownloadSpecPath = z.object({
  repo: z.string(),
});

export const zDownloadSpecQuery = z.object({
  format: z.string().optional(),
});

export const zGetSpecGraphqlPath = z.object({
  repo: z.string(),
});

export const zGetSpecGraphqlQuery = z.object({
  download: z.boolean().optional(),
});

export const zDownloadGraphqlPath = z.object({
  repo: z.string(),
});

export const zDownloadGraphqlQuery = z.object({
  format: z.string().optional(),
});

export const zGetSpecGraphqlInfoPath = z.object({
  repo: z.string(),
});

/**
 * Parsed GraphQL schema — types, queries, mutations, subscriptions
 */
export const zGetSpecGraphqlInfoResponse = zGraphQlInfo;

export const zProxyGraphqlBody = zGraphqlProxyRequest;

export const zProxyGraphqlPath = z.object({
  repo: z.string(),
});

export const zGetSpecPublicPath = z.object({
  repo: z.string(),
});

export const zGetSpecPublicQuery = z.object({
  format: z.string().optional(),
  download: z.boolean().optional(),
});

export const zSystemActionHandlerBody = zSystemActionRequest;

/**
 * Action result
 */
export const zSystemActionHandlerResponse = zSystemActionResponse;

/**
 * Sync result
 */
export const zSystemDevSyncHandlerResponse = zSystemDevSyncResponse;

export const zRunTestsQuery = z.object({
  suite: z.string(),
});

/**
 * Test run result
 */
export const zRunTestsResponse = zTestRunResponse;

export const zGetTreeQuery = z.object({
  raw: z.boolean().optional(),
});
