[package]
name = "nfs"
version.workspace = true
edition.workspace = true

[lib]
name = "nfs"
path = "src/lib.rs"

[dependencies]
serde       = { workspace = true }
thiserror   = { workspace = true }
tokio       = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
