[package]
name = "platform"
version.workspace = true
edition.workspace = true

[lib]
name = "platform"
path = "src/lib.rs"

[features]
cli = [
    "dep:clap",
    "dep:colored",
]
[dependencies]
orca-dispatch        = { path = "../orca-dispatch" }
orca-contract    = { path = "../orca-contract", default-features = false }
orca-macro       = { path = "../orca-macro" }
schemars         = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
inventory        = { workspace = true }

orca-utils = { path = "../utils" }
orca-db = { package = "orca-db", path = "../db" }
anyhow = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
cron = { workspace = true }
clap              = { workspace = true,         optional = true }
colored           = { workspace = true,         optional = true }
rusqlite = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }

[lints]
workspace = true
