//! Typed clients for the *arr stack. One module per flavor; bodies are
//! generated by `progenitor` at build time from the matching spec under
//! `specs/<flavor>.openapi.json` — see `build.rs`.
//!
//! Adding a new flavor is two steps:
//!   1. Drop `specs/<flavor>.openapi.json` into the crate.
//!   2. Add `flavor!(<flavor>);` to the list below.
//!
//! Generated `Client` types are intentionally per-module (`arr::sonarr::Client`,
//! `arr::radarr::Client`, …) — the *arr forks diverge enough that a unified
//! trait would lie about which endpoints exist on which server.
//!
//! ## NOT a user-facing auth surface
//!
//! `auth` is `pub(crate)` on purpose: per
//! `feedback-canonical-model-is-load-bearing`, every credential-touching
//! affordance must route through an `#[orca_tool]` that resolves
//! coordinates via the capability transport chain, pulls/persists
//! creds through the `secrets` table with `self_secure`-gated
//! replication, and runs under the authenticated caller identity. None
//! of those prereqs exist yet — until they land, the *arr crate
//! deliberately exposes only the typed flavor clients and keeps the
//! transport primitives internal.

pub(crate) mod auth;

macro_rules! flavor {
    ($name:ident) => {
        #[allow(
            clippy::all,
            dead_code,
            unused_imports,
            unused_variables,
            non_snake_case
        )]
        pub mod $name {
            include!(concat!(
                env!("OUT_DIR"),
                "/",
                stringify!($name),
                "_codegen.rs"
            ));
        }
    };
}

flavor!(sonarr);
flavor!(radarr);
flavor!(prowlarr);
flavor!(lidarr);
flavor!(readarr);
