//! Typed clients for the *arr stack. One module per flavor; bodies are
//! generated by `progenitor` at build time from the matching spec under
//! `specs/<flavor>.openapi.json` — see `build.rs`.
//!
//! Adding a new flavor is two steps:
//!   1. Drop `specs/<flavor>.openapi.json` into the crate.
//!   2. Add `flavor!(<flavor>);` to the list below.
//!
//! Generated `Client` types are intentionally per-module (`arr::sonarr::Client`,
//! `arr::radarr::Client`, …) — the *arr forks diverge enough that a unified
//! trait would lie about which endpoints exist on which server.

pub mod auth;

macro_rules! flavor {
    ($name:ident) => {
        #[allow(
            clippy::all,
            dead_code,
            unused_imports,
            unused_variables,
            non_snake_case
        )]
        pub mod $name {
            include!(concat!(
                env!("OUT_DIR"),
                "/",
                stringify!($name),
                "_codegen.rs"
            ));
        }
    };
}

flavor!(sonarr);
flavor!(radarr);
flavor!(prowlarr);
flavor!(lidarr);
flavor!(readarr);
