//! Shared helpers for the surface generators (`openapi`, `graphql`).
//!
//! Deliberately small — only what BOTH shapes genuinely use. The
//! spec-vs-schema walking logic diverges (OpenAPI closes over a `types`
//! module; GraphQL anchors each operation module wholesale), so it stays in
//! the respective generator rather than being force-shared here.

/// Header prepended to every emitted `*_surface.rs`. The generated tools use
/// the plugin prelude for `Serialize`/`Deserialize`/`JsonSchema`/`ToolCtx`/
/// `orca_tool`/`anyhow!`.
pub(crate) const GENERATED_HEADER: &str = "// @generated by plugin_toolkit_build::surface — do not edit. Regenerated every build.\n\
     use plugin_toolkit::prelude::*;\n\n";

/// Push the JsonSchema derive + its crate anchor onto an item's attributes, so
/// the type's shape is runtime-introspectable through the tool's arg/output
/// schema. Both generators anchor the transitive closure of their surfaced
/// types this way.
pub(crate) fn push_jsonschema_anchor(attrs: &mut Vec<syn::Attribute>) {
    attrs.push(syn::parse_quote!(
        #[derive(::plugin_toolkit::schemars::JsonSchema)]
    ));
    attrs.push(syn::parse_quote!(
        #[schemars(crate = "::plugin_toolkit::schemars")]
    ));
}

/// The trailing idents of every `#[derive(...)]` on an item (`Serialize`,
/// `JsonSchema`, …), regardless of path qualification.
pub(crate) fn derive_list(attrs: &[syn::Attribute]) -> Vec<String> {
    let mut out = Vec::new();
    for a in attrs {
        if !a.path().is_ident("derive") {
            continue;
        }
        // Discard the parse result (accumulation happens in the closure); the
        // workspace denies `let _ = <must_use>`, so consume it via `drop`.
        drop(a.parse_nested_meta(|meta| {
            if let Some(last) = meta.path.segments.last() {
                out.push(last.ident.to_string());
            }
            Ok(())
        }));
    }
    out
}

/// True if the item carries `#[serde(crate = ...)]`, marking it a derive-based
/// serde type (as opposed to one with hand-written serde impls, e.g. GraphQL
/// enums, which carry no such attribute).
pub(crate) fn has_serde_crate_attr(attrs: &[syn::Attribute]) -> bool {
    attrs.iter().any(|a| {
        if !a.path().is_ident("serde") {
            return false;
        }
        let mut found = false;
        drop(a.parse_nested_meta(|meta| {
            if meta.path.is_ident("crate") {
                found = true;
            }
            Ok(())
        }));
        found
    })
}

/// Collect the doc-comment text of an item into one string (newline-joined).
pub(crate) fn collect_doc(attrs: &[syn::Attribute]) -> String {
    let mut s = String::new();
    for a in attrs {
        if a.path().is_ident("doc")
            && let syn::Meta::NameValue(nv) = &a.meta
            && let syn::Expr::Lit(syn::ExprLit {
                lit: syn::Lit::Str(ls),
                ..
            }) = &nv.value
        {
            s.push_str(&ls.value());
            s.push('\n');
        }
    }
    s
}

/// True if `ty` is a bare path ending in the single segment `ident` (e.g.
/// `bool`, `str`) with no generic arguments.
pub(crate) fn is_ident(ty: &syn::Type, ident: &str) -> bool {
    matches!(ty, syn::Type::Path(p)
        if p.path.segments.last().is_some_and(|s| s.ident == ident
            && matches!(s.arguments, syn::PathArguments::None)))
}

/// If `ty` is `Option<T>` (however the path is spelled), return `T`.
pub(crate) fn option_inner(ty: &syn::Type) -> Option<&syn::Type> {
    first_generic(ty, "Option")
}

/// If `ty`'s last path segment is `name<...>`, return its first type generic.
pub(crate) fn first_generic<'a>(ty: &'a syn::Type, name: &str) -> Option<&'a syn::Type> {
    let syn::Type::Path(p) = ty else { return None };
    let seg = p.path.segments.last()?;
    if seg.ident != name {
        return None;
    }
    let syn::PathArguments::AngleBracketed(args) = &seg.arguments else {
        return None;
    };
    args.args.iter().find_map(|a| match a {
        syn::GenericArgument::Type(t) => Some(t),
        _ => None,
    })
}
