[package]
name = "schema"
version.workspace = true
edition.workspace = true

[lib]
name = "schema"
path = "src/lib.rs"

[features]
cli = [
    "dep:clap",
    "dep:colored",
]
[dependencies]
orca-dispatch    = { path = "../orca-dispatch" }
orca-contract    = { path = "../orca-contract", default-features = false }
orca-macro       = { path = "../orca-macro" }
schemars         = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }
inventory        = { workspace = true }

orca-utils = { path = "../utils" }
db = { package = "orca-db", path = "../db" }
anyhow = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
mysql_async = { version = "0.36", default-features = false, features = ["default-rustls-ring"] }
tokio-postgres = { version = "0.7", default-features = false, features = ["runtime"] }
rusqlite = { workspace = true }
toml = { workspace = true }
clap           = { workspace = true,         optional = true }
colored        = { workspace = true,         optional = true }

[lints]
workspace = true
