[package]
name = "smb"
version.workspace = true
edition.workspace = true

[lib]
name = "smb"
path = "src/lib.rs"

[dependencies]
serde       = { workspace = true }
thiserror   = { workspace = true }
tokio       = { workspace = true }

[dev-dependencies]
tempfile   = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
