[package]
name = "auth"
version.workspace = true
edition.workspace = true

[lib]
name = "auth"
path = "src/lib.rs"

[dependencies]
plugin-toolkit = { path = "../plugin-toolkit" }
macro-runtime = { path = "../macro-runtime" }
contract    = { path = "../contract", default-features = false }
derive       = { path = "../derive" }
schemars         = { workspace = true }
serde            = { workspace = true }
serde_json       = { workspace = true }

utils = { path = "../utils" }
files = { path = "../files" }
db = { package = "db", path = "../db" }
anyhow = { workspace = true }
tokio = { workspace = true }
clap        = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
url = { workspace = true }
rusqlite = { workspace = true }
argon2 = { workspace = true }
reqwest = { workspace = true }

[dev-dependencies]
db = { path = "../db", features = ["test-util"] }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
model      = { path = "../model" }

[lints]
workspace = true
