#!/usr/bin/env bash
# Generates .github/workflows/ci.yml: one build+test job per workspace crate,
# each needing exactly the crates it depends on (normal, build AND dev edges:
# a crate's tests compile its dev-deps, so waiting for them keeps sccache warm
# and matches crate-hashes, which also closes over dev edges). A dependency
# cycle fails generation.
#
# Prints the workflow to stdout; `--write` writes it in place. The lint job's
# "Workflow matches crate graph" step diffs stdout against the committed file.
#
# CI_METADATA_JSON names a `cargo metadata --format-version 1 --no-deps` file
# to use instead of running cargo.
set -euo pipefail

cd "$(dirname "$0")/.."
OUT=.github/workflows/ci.yml

if [ -n "${CI_METADATA_JSON:-}" ]; then
  meta="$(cat "$CI_METADATA_JSON")"
else
  meta="$(cargo metadata --format-version 1 --no-deps --locked)"
fi

# name<TAB>space-separated sorted internal deps, sorted by name.
graph="$(jq -r '
  .workspace_members as $m
  | [.packages[] | select(.id as $id | $m | index($id))] as $ws
  | ($ws | map(.name)) as $names
  | $ws | sort_by(.name)[]
  | [.name, ([.dependencies[] | select(.path != null) | .name
              | select(. as $d | $names | index($d))] - [.name] | unique | join(" "))]
  | @tsv' <<<"$meta")"

# Kahn's algorithm: anything left unplaced is on a cycle.
jq -Rne '
  [inputs | split("\t") | {key: .[0], value: (.[1] | split(" ") | map(select(. != "")))}]
  | from_entries as $g
  | def drain($done):
      ([$g | to_entries[] | select((.key as $k | $done | index($k)) | not)
            | select(all(.value[]; . as $d | $done | index($d))) | .key]) as $ready
      | if ($ready | length) == 0 then $done else drain($done + $ready) end;
    (drain([])) as $placed
  | ($g | keys - $placed) as $cyc
  | if ($cyc | length) > 0 then error("dependency cycle among: \($cyc | join(" "))") else true end
' <<<"$graph" >/dev/null

job_id() { printf 'crate-%s' "${1#orca-}"; }

emit() {
  cat <<'EOF'
# GENERATED by scripts/gen-ci-crate-dag.sh from `cargo metadata` — do not edit.
# Regenerate with `scripts/gen-ci-crate-dag.sh --write` after changing the
# workspace graph or this template; lint fails when the two drift.
name: CI

# One job per workspace crate, each waiting only on the crates it depends on.
# A crate whose input hash (crate-hashes: its files, its internal deps' files,
# the toolchain, Cargo.lock and this workflow) has a recorded pass reuses it
# and skips build + test; the nightly schedule and workflow_dispatch force a
# full run. Coverage is report-only.
#
# CI runs on GITEA (canonical), executed by our self-hosted Gitea act_runner.
# `runs-on` labels map to local Docker runners, NOT GitHub-hosted VMs.
on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "17 9 * * *"

# Cancel in-flight runs when a newer commit arrives on the same ref.
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  # Disable per-target incremental files. Pointless on CI and MANDATORY for
  # sccache — incremental compilation and sccache are mutually exclusive
  # (leaving it on silently disables every cache hit).
  CARGO_INCREMENTAL: 0
  # Cheap KDF for the test/coverage build only. Honored solely when
  # cfg!(debug_assertions) is true (test/coverage builds) — release binaries
  # ignore it — so it never weakens production. Skips the memory-hard Argon2 +
  # SQLCipher PBKDF2 cost that otherwise makes auth/secrets tests run tens of
  # seconds each under coverage instrumentation.
  ORCA_TEST_FAST_KDF: "1"
  # No DWARF on CI: less compile, link and cache weight. Trade-off:
  # RUST_BACKTRACE frames lose file:line, but a panic still prints its
  # location. Coverage is unaffected (-Cinstrument-coverage emits its own
  # mapping sections). Local dev keeps line tables.
  CARGO_PROFILE_DEV_DEBUG: "0"
  CARGO_PROFILE_TEST_DEBUG: "0"

  # ── Kill vendored OpenSSL on the PR gate (biggest cold-compile win) ────────
  # OpenSSL is pulled in vendored TWICE — via git2's `vendored-openssl` and via
  # rusqlite's `bundled-sqlcipher-vendored-openssl` — so a cold build compiles
  # the whole OpenSSL C source from scratch, the single largest crate cost.
  # OPENSSL_NO_VENDOR=1 overrides the vendored feature at build-script time and
  # links the system OpenSSL (libssl-dev, baked into the ci-rust image) instead.
  # This is CI-ONLY: the release/cross (musl) workflow deliberately does NOT set
  # it, so production keeps statically vendoring OpenSSL for portable binaries.
  OPENSSL_NO_VENDOR: "1"

jobs:
  lint:
    name: lint
    runs-on: ci-large
    container:
      image: ${{ vars.CI_REGISTRY || 'gitea.scottkey.me' }}/argyle-labs/ci-rust:1.95.0
      credentials:
        username: ${{ secrets.CI_REGISTRY_USER }}
        password: ${{ secrets.CI_REGISTRY_TOKEN }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # Fails if a real fleet address returns (the repo mirrors to a PUBLIC
      # GitHub). The patterns are a secret so the guard does not leak the range
      # it protects; unset, the allowlist sweep still runs.
      - name: Check for forbidden real-fleet addresses
        env:
          ORCA_FORBIDDEN_IP_PATTERNS: ${{ secrets.FORBIDDEN_IP_PATTERNS }}
        run: ./scripts/check-no-real-ips.sh

      - name: Workflow matches crate graph
        if: ${{ !cancelled() }}
        run: diff -u .github/workflows/ci.yml <(scripts/gen-ci-crate-dag.sh)

      - name: Set up Rust
        uses: argyle-labs/.github/.github/actions/rust-setup@main
        if: ${{ !cancelled() }}
        with:
          drop-cargo-config: 'false'
          wrap-cc: 'true'
          sccache-endpoint: ${{ vars.SCCACHE_ENDPOINT }}
          sccache-access-key: ${{ secrets.SCCACHE_S3_ACCESS_KEY }}
          sccache-secret-key: ${{ secrets.SCCACHE_S3_SECRET_KEY }}
      - name: Format
        uses: argyle-labs/.github/.github/actions/cargo-fmt@main
        if: ${{ !cancelled() }}
      - name: Clippy
        uses: argyle-labs/.github/.github/actions/cargo-clippy@main
        if: ${{ !cancelled() }}
        with:
          args: --workspace --tests
      # Last: it deletes .cargo/config.toml, which the cargo steps above need.
      - name: Lock file check
        uses: argyle-labs/.github/.github/actions/cargo-lock-check@main
        if: ${{ !cancelled() }}
      - name: CI summary
        uses: argyle-labs/.github/.github/actions/ci-summary@main
        if: ${{ !cancelled() }}

  # Hashes every crate once and lists those without a recorded pass. Crates
  # whose tests read repo paths outside their directory hash those paths too:
  # docs/ (orca-files, inherited by its dependents), docs/plugin-authoring
  # (orca-plugin-toolkit) and the whole tree (orca-inventory-tests, which has
  # no dependents, so it simply runs every time).
  plan:
    name: plan
    runs-on: ci-large
    container:
      image: ${{ vars.CI_REGISTRY || 'gitea.scottkey.me' }}/argyle-labs/ci-rust:1.95.0
      credentials:
        username: ${{ secrets.CI_REGISTRY_USER }}
        password: ${{ secrets.CI_REGISTRY_TOKEN }}
    defaults:
      run:
        shell: bash
    outputs:
      hashes: ${{ steps.src.outputs.hashes }}
      missing: ${{ steps.pass.outputs.missing }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Crate hashes
        id: src
        uses: argyle-labs/.github/.github/actions/crate-hashes@main
        with:
          image: ci-rust:1.95.0
          workflow-file: .github/workflows/ci.yml
          extra-paths: |
            orca-files: docs
            orca-plugin-toolkit: docs/plugin-authoring
            orca-inventory-tests: .
      - name: Check pass cache per crate
        id: pass
        uses: argyle-labs/.github/.github/actions/ci-pass-cache@main
        with:
          mode: check-batch
          job: build
          hashes: ${{ steps.src.outputs.hashes }}
          force: ${{ github.event_name != 'pull_request' && 'true' || 'false' }}
          endpoint: ${{ vars.SCCACHE_ENDPOINT }}
          access-key: ${{ secrets.SCCACHE_S3_ACCESS_KEY }}
          secret-key: ${{ secrets.SCCACHE_S3_SECRET_KEY }}
EOF

  local crate_tpl
  crate_tpl="$(cat <<'EOF'

  @ID@:
    name: build (@NAME@)
    needs: [@NEEDS@]
    if: ${{ !cancelled() && !failure() }}
    runs-on: ci-large
    container:
      image: ${{ vars.CI_REGISTRY || 'gitea.scottkey.me' }}/argyle-labs/ci-rust:1.95.0
      credentials:
        username: ${{ secrets.CI_REGISTRY_USER }}
        password: ${{ secrets.CI_REGISTRY_TOKEN }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Check pass cache
        id: pass
        uses: argyle-labs/.github/.github/actions/ci-pass-cache@main
        with:
          mode: check
          job: build/crate/@NAME@
          hash: ${{ fromJSON(needs.plan.outputs.hashes)['@NAME@'] }}
          force: ${{ github.event_name != 'pull_request' && 'true' || 'false' }}
          endpoint: ${{ vars.SCCACHE_ENDPOINT }}
          access-key: ${{ secrets.SCCACHE_S3_ACCESS_KEY }}
          secret-key: ${{ secrets.SCCACHE_S3_SECRET_KEY }}
      - name: Reuse recorded pass
        if: ${{ steps.pass.outputs.hit == 'true' }}
        env:
          SHA: ${{ steps.pass.outputs.sha }}
        run: echo "Unchanged — reusing pass from ${SHA:-unknown}" | tee -a "$GITHUB_STEP_SUMMARY"
      - name: Set up Rust
        if: ${{ steps.pass.outputs.hit != 'true' }}
        uses: argyle-labs/.github/.github/actions/rust-setup@main
        with:
          drop-cargo-config: 'false'
          wrap-cc: 'true'
          sccache-endpoint: ${{ vars.SCCACHE_ENDPOINT }}
          sccache-access-key: ${{ secrets.SCCACHE_S3_ACCESS_KEY }}
          sccache-secret-key: ${{ secrets.SCCACHE_S3_SECRET_KEY }}
      # server/system build scripts derive ORCA_VERSION from git; a fixed
      # version keeps them cached. The -dev suffix keeps dev-build behaviour.
      - name: Pin orca version
        if: ${{ steps.pass.outputs.hit != 'true' }}
        run: |
          v="$(sed -n 's/^version = "\(.*\)"$/\1/p' Cargo.toml | head -1)"
          [ -n "$v" ] || exit 1
          echo "ORCA_RELEASE_VERSION=${v}-dev+gci" >> "$GITHUB_ENV"
      # The coverage-instrumented test binaries are the build: a separate
      # uninstrumented `cargo build` would compile everything a second time.
      - name: Build (coverage-instrumented test archive)
        if: ${{ steps.pass.outputs.hit != 'true' }}
        run: |
          cargo fetch --locked
          cargo llvm-cov nextest-archive --locked -p @NAME@ --archive-file nextest-archive.tar.zst
      - name: Test + coverage
        if: ${{ steps.pass.outputs.hit != 'true' }}
        uses: argyle-labs/.github/.github/actions/cargo-llvm-cov@main
        with:
          name-suffix: -@NAME@
      - name: Record pass
        if: ${{ success() && steps.pass.outputs.hit != 'true' }}
        uses: argyle-labs/.github/.github/actions/ci-pass-cache@main
        with:
          mode: record
          job: build/crate/@NAME@
          hash: ${{ fromJSON(needs.plan.outputs.hashes)['@NAME@'] }}
          endpoint: ${{ vars.SCCACHE_ENDPOINT }}
          access-key: ${{ secrets.SCCACHE_S3_ACCESS_KEY }}
          secret-key: ${{ secrets.SCCACHE_S3_SECRET_KEY }}
      - name: CI summary
        uses: argyle-labs/.github/.github/actions/ci-summary@main
        if: ${{ !cancelled() }}
EOF
)"

  local all=() name deps needs job d
  while IFS=$'\t' read -r name deps; do
    job="$(job_id "$name")"
    all+=("$job")
    needs="plan"
    for d in $deps; do needs+=", $(job_id "$d")"; done
    job="${crate_tpl//@ID@/$job}"
    job="${job//@NEEDS@/$needs}"
    printf '%s\n' "${job//@NAME@/$name}"
  done <<<"$graph"

  local all_needs
  all_needs="$(printf '      - %s\n' plan "${all[@]}")"

  cat <<EOF

  # The required \`test*\` check: crate jobs are named \`build (…)\` and test
  # their crate too, so this fails unless every one of them succeeded.
  test:
    name: test
    needs:
${all_needs}
    if: \${{ !cancelled() }}
    runs-on: ci-large
    container:
      image: \${{ vars.CI_REGISTRY || 'gitea.scottkey.me' }}/argyle-labs/ci-rust:1.95.0
      credentials:
        username: \${{ secrets.CI_REGISTRY_USER }}
        password: \${{ secrets.CI_REGISTRY_TOKEN }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Every crate built and tested
        env:
          RESULTS: \${{ toJSON(needs) }}
        run: |
          failed="\$(jq -r 'to_entries[] | select(.value.result != "success") | "\\(.key): \\(.value.result)"' <<<"\$RESULTS")"
          if [ -n "\$failed" ]; then
            echo "\$failed"
            exit 1
          fi
          echo "all crates passed"

  # Merges the per-crate lcov files; report-only. Crates reusing a recorded
  # pass upload none, so the total covers only crates that ran.
  coverage:
    name: coverage
    needs:
$(printf '      - %s\n' "${all[@]}")
    if: \${{ !cancelled() }}
    runs-on: ci-large
    container:
      image: \${{ vars.CI_REGISTRY || 'gitea.scottkey.me' }}/argyle-labs/ci-rust:1.95.0
      credentials:
        username: \${{ secrets.CI_REGISTRY_USER }}
        password: \${{ secrets.CI_REGISTRY_TOKEN }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Download per-crate lcov
        uses: actions/download-artifact@v4
        with:
          pattern: lcov-*
          path: lcov
      - name: Merge coverage
        run: |
          shopt -s nullglob globstar
          files=(lcov/**/lcov.info)
          if [ "\${#files[@]}" -eq 0 ]; then
            echo "No crate produced coverage (all reused recorded passes)." | tee -a "\$GITHUB_STEP_SUMMARY"
            exit 0
          fi
          # A line counts as hit when any crate's tests executed it.
          awk -F'[:,]' '
            /^SF:/ { sf = substr(\$0, 4) }
            /^DA:/ { k = sf SUBSEP \$2; if (!(k in hit)) hit[k] = 0; if (\$3 > 0) hit[k] = 1 }
            END {
              for (k in hit) { total++; covered += hit[k] }
              printf "### Coverage (merged)\n\n%d / %d lines (%.2f%%)\n", covered, total, total ? 100 * covered / total : 0
            }' "\${files[@]}" | tee -a "\$GITHUB_STEP_SUMMARY"
          cat "\${files[@]}" > lcov-merged.info
      - name: Upload merged lcov
        uses: actions/upload-artifact@v4
        if: \${{ hashFiles('lcov-merged.info') != '' }}
        with:
          name: lcov-merged
          path: lcov-merged.info
          retention-days: 7
EOF
}

if [ "${1:-}" = "--write" ]; then
  emit >"$OUT"
else
  emit
fi
