#!/usr/bin/env bash
# scaffold-plugin.sh — stamp the canonical orca SERVICE-BACKEND plugin skeleton.
#
# MINIMAL API: plugins expose ZERO #[orca_tool]s. The whole fleet shares ONE
# generic `service.*` surface in plugin-toolkit; each plugin just registers a
# `ServiceBackend` impl via `export_service_plugin!` — exactly how nfs/smb
# register a StorageBackend. See orca/docs/PLUGIN-PROGRAM.md.
#
# Usage:
#   scaffold-plugin.sh <name> <modalities> <port> "<description>"
#     modalities: csv from {docker,podman,lxc,vm,device,host}
set -euo pipefail

NAME="${1:?name}"; MODALITIES="${2:?modalities csv}"; PORT="${3:?port}"; DESC="${4:?description}"
ROOT="${SCAFFOLD_ROOT:-$HOME/code/argyle-labs}"
LICENSE_SRC="${ROOT}/jellyfin/LICENSE"
DIR="${ROOT}/${NAME}"
has() { [[ ",${MODALITIES}," == *",$1,"* ]]; }
SNAKE="${NAME//-/_}"
# PascalCase for the backend type name
PASCAL="$(printf '%s' "$NAME" | awk -F'[-_]' '{for(i=1;i<=NF;i++)printf toupper(substr($i,1,1)) substr($i,2)}')"

# Existence guard. SCAFFOLD_FORCE=1 regenerates source over an existing repo,
# preserving .git / Cargo.lock and pruning the old bash-era mechanics.
if [[ -e "$DIR" && "${SCAFFOLD_FORCE:-0}" != "1" ]]; then
  echo "[skip] $NAME exists"; exit 0
fi
echo "[scaffold] $NAME ($MODALITIES) :$PORT"
mkdir -p "$DIR/src" "$DIR/assets"

# A plugin is PURE RUST + config — no bash for consumers. Prune any
# previously-generated shell/compose/provision mechanics; deploy + install +
# entrypoint are rendered generically by deploy_target from the WorkloadSpec,
# backup/restore by the service domain's pluggable BackupMethod, configure by
# the Rust ServiceBackend::configure method.
rm -f "$DIR/compose.yml" "$DIR/Dockerfile" \
      "$DIR"/scripts/*.sh "$DIR"/lxc/*.sh "$DIR"/vm/*.sh 2>/dev/null || true
# `examples/` held per-service compose + lxc/provision.sh (hardcoded CTID, and
# misfiled services like lazylibrarian/mylar3 under arr). It IS the bash-for-
# consumers we eliminate — nuke the whole tree, not just leaf scripts. Placement
# (incl. CTID: env/spec override, else pvesh nextid) is the proxmox deploy_target
# adapter's job, rendered from the WorkloadSpec — never a checked-in script.
rm -rf "$DIR/examples" 2>/dev/null || true
rmdir "$DIR/scripts" "$DIR/lxc" "$DIR/vm" 2>/dev/null || true

# Runtimes this backend supports — only the deploy-target runtime axis
# {docker,podman,lxc,vm}. device/host modalities (mikrotik, a host UPS daemon)
# have NO Runtime variant: those backends advertise no runtimes and drop the
# Deploy capability (they connect/configure an existing thing, not place a workload).
RUNTIMES=""
for m in docker podman lxc vm; do has "$m" && RUNTIMES+="Runtime::${m^}, "; done
RUNTIMES="${RUNTIMES%, }"
# Deploy capability only when at least one runtime exists.
if [[ -n "$RUNTIMES" ]]; then
  CAP_LIST="ServiceCapability::Deploy, ServiceCapability::Backup, ServiceCapability::Restore, ServiceCapability::Configure, ServiceCapability::Status"
else
  CAP_LIST="ServiceCapability::Backup, ServiceCapability::Restore, ServiceCapability::Configure, ServiceCapability::Status"
fi

# ── Cargo.toml ──────────────────────────────────────────────────────────────
cat > "$DIR/Cargo.toml" <<EOF
[package]
name = "${NAME}"
version = "0.1.0"
edition = "2021"

[lib]
name = "${SNAKE}"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

# ${NAME} is a BACKEND-ONLY orca plugin: zero #[orca_tool]s. It registers a
# ServiceBackend across the cdylib FFI seam and reaches the whole orca system
# through plugin-toolkit alone.
[dependencies]
plugin-toolkit = { git = "https://github.com/argyle-labs/orca", branch = "main" }
# The ONE non-orca dep: #[export_root_module] expands to bare ::abi_stable paths.
abi_stable = "0.11"

[dev-dependencies]
plugin-toolkit = { git = "https://github.com/argyle-labs/orca", branch = "main" }
tokio    = { version = "1", features = ["macros", "rt-multi-thread"] }
tempfile = "3"

[lints.clippy]
let_underscore_must_use = "deny"
EOF

printf '/target\n**/*.rs.bk\nCargo.lock.orig\n' > "$DIR/.gitignore"
cp "$LICENSE_SRC" "$DIR/LICENSE"

# Dev override: resolve the orca git dep to the local in-tree crate so the
# plugin builds against the unreleased plugin-toolkit alongside ../orca.
mkdir -p "$DIR/.cargo"
cat > "$DIR/.cargo/config.toml" <<EOF
[net]
git-fetch-with-cli = true

[patch."https://github.com/argyle-labs/orca"]
plugin-toolkit = { path = "../orca/projects/plugin-toolkit" }
EOF

# ── src/abi_export.rs ───────────────────────────────────────────────────────
cat > "$DIR/src/abi_export.rs" <<EOF
//! ABI-stable cdylib export for the ${NAME} service backend.
//!
//! ${NAME} is a BACKEND-ONLY plugin: its entire export is generated by the
//! toolkit's \`export_service_plugin!\`. The generic \`service.*\` tool surface
//! lives once in plugin-toolkit; this plugin only provides the backend.
//! \`abi_stable\` stays a direct dep because \`#[export_root_module]\` expands
//! to bare \`::abi_stable\` paths.
plugin_toolkit::export_service_plugin! {
    name: "${NAME}",
    target_compat: "any",
    backend: crate::${PASCAL}Backend::new("${NAME}"),
}
EOF

# ── src/lib.rs : the ServiceBackend impl ────────────────────────────────────
cat > "$DIR/src/lib.rs" <<EOF
//! ${NAME} service backend — ${DESC}.
//!
//! Implements \`ServiceBackend\` so the generic \`service.*\` tools
//! (deploy/backup/restore/configure/status/connect/sync) drive ${NAME}. No
//! \`#[orca_tool]\`s — the only orca dep is \`plugin-toolkit\`. Modeled on the
//! nfs StorageBackend. See orca/docs/PLUGIN-PROGRAM.md.
#![allow(clippy::disallowed_types)]

use plugin_toolkit::service::{
    BoxFuture, Endpoint, Runtime, ServiceBackend, ServiceCapability, ServiceError, ServiceStatus,
    WorkloadSpec,
};

mod abi_export;

/// ${NAME} backend. Holds only the provider name; per-instance endpoint/creds
/// come from the \`Endpoint\` the generic \`service.*\` tools hand each op.
#[derive(Debug, Clone)]
pub struct ${PASCAL}Backend {
    provider: &'static str,
}

impl ${PASCAL}Backend {
    pub fn new(provider: &'static str) -> Self {
        Self { provider }
    }
}

impl ServiceBackend for ${PASCAL}Backend {
    fn provider(&self) -> &str { self.provider }

    /// Runtimes ${NAME} can be placed on. \`service.deploy\` hands the
    /// \`workload_spec\` below to a matching deploy target — this backend never
    /// drives pct/docker itself (that mechanic lives in the deploy-target domain).
    fn runtimes(&self) -> Vec<Runtime> { vec![${RUNTIMES}] }

    fn capabilities(&self) -> Vec<ServiceCapability> { vec![${CAP_LIST}] }

    fn default_port(&self) -> u16 { ${PORT} }

    /// In-workload paths holding config/data. This is ALL ${NAME} declares for
    /// backup — the generic pluggable backup (tar for containers/LXC, PBS for
    /// Proxmox guests when available) snapshots these. No backup/restore code
    /// here; those are inherited from ServiceBackend's defaults.
    fn data_paths(&self) -> Vec<String> { vec!["/config".to_string()] }

    fn workload_spec<'a>(&'a self, _runtime: Runtime, _ep: &'a Endpoint)
        -> BoxFuture<'a, Result<WorkloadSpec, ServiceError>>
    {
        // TODO: describe the ${NAME} workload (image/template, ports, mounts,
        // env) for the chosen runtime. The deploy target turns this into a
        // compose service / LXC config / VM. See deploy-target::WorkloadSpec.
        Box::pin(async move { Err(ServiceError::unimplemented("${NAME}.workload_spec")) })
    }

    fn configure<'a>(&'a self, _ep: &'a Endpoint, _config: &'a str)
        -> BoxFuture<'a, Result<(), ServiceError>>
    {
        // TODO: apply ${NAME}-specific config idempotently.
        Box::pin(async move { Err(ServiceError::unimplemented("${NAME}.configure")) })
    }

    fn status<'a>(&'a self, _ep: &'a Endpoint)
        -> BoxFuture<'a, Result<ServiceStatus, ServiceError>>
    {
        // TODO: real health/diagnostics.
        Box::pin(async move { Err(ServiceError::unimplemented("${NAME}.status")) })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn declares_provider() {
        let b = ${PASCAL}Backend::new("${NAME}");
        assert_eq!(b.provider(), "${NAME}");
    }
}
EOF

# No bash, no compose, no provision scripts. Deployment is rendered by
# deploy_target from the WorkloadSpec; backup/restore are the service domain's
# pluggable BackupMethod; configure/status are Rust methods. A plugin needing a
# custom container image is the rare exception and adds a Dockerfile by hand.

# ── CAPABILITIES.md — per-repo contract checklist (Checklist 2 tracking) ─────
cat > "$DIR/CAPABILITIES.md" <<EOF
# ${NAME} — ServiceBackend contract checklist

Pure-Rust plugin: **no bash, no compose, no provision scripts**. Driven by the
generic \`service.*\` surface (no per-plugin tools). Modalities: **${MODALITIES}**.

## What this plugin implements (the only per-plugin work)
- [ ] \`provider\` / \`runtimes\` / \`default_port\` / \`capabilities\` / \`data_paths\` — declarative
- [ ] \`workload_spec(runtime)\` — *what* to run; \`deploy_target\` renders it to compose/LXC/VM
- [ ] \`configure\` — service-specific config via the upstream API
- [ ] \`status\` — health/diagnostics

## Inherited generically (NO code in this plugin)
- \`deploy\` — \`service.deploy\` → \`deploy_target.launch(WorkloadSpec)\`
- \`backup\` / \`restore\` — pluggable \`BackupMethod\` (tar for containers/LXC, **PBS** for Proxmox guests when available)
- \`connect\` / \`sync\` — endpoint registry + peer sync in the toolkit
EOF

# ── README.md ───────────────────────────────────────────────────────────────
cat > "$DIR/README.md" <<EOF
# ${NAME}

${DESC} — a first-party [orca](https://github.com/argyle-labs/orca) **service
backend** plugin. Exposes no tools of its own; orca drives it through the generic
\`service.*\` surface (deploy, backup, restore, configure, status, connect, sync).

Modalities: **${MODALITIES}**. Status: **scaffolded** — see
[CAPABILITIES.md](CAPABILITIES.md). Generated by \`orca/scripts/scaffold-plugin.sh\`.
EOF

# ── Optional: seed a committed Cargo.lock with `time` pinned ────────────────
# A fresh tree resolves time 0.3.52, which breaks cookie 0.18.1 (pulled via the
# toolkit's reqwest `cookies` feature). Pin to the version orca's lock uses.
# Gated by SCAFFOLD_LOCK=1 since it needs cargo + network; the batch pass and
# release flow run it fleet-wide.
if [[ "${SCAFFOLD_LOCK:-0}" == "1" ]]; then
  ( cd "$DIR" && cargo generate-lockfile >/dev/null 2>&1 \
      && cargo update -p time --precise 0.3.47 >/dev/null 2>&1 ) \
    && echo "[lock] $NAME pinned time=0.3.47" || echo "[lock] $NAME skipped (cargo/network)"
fi

echo "[done] $NAME"
