[package]
name = "database"
version.workspace = true
edition.workspace = true

[lib]
name = "database"
path = "src/lib.rs"

[features]
cli = [
    "dep:clap",
    "dep:colored",
]

[dependencies]
dispatch    = { path = "../../dispatch" }
contract    = { path = "../../contract", default-features = false }
derive      = { path = "../../derive" }
schemars    = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
inventory   = { workspace = true }

utils  = { path = "../../utils" }
files    = { path = "../../files" }
db     = { path = "../../db" }
anyhow = { workspace = true }
async-trait = { workspace = true }
tokio  = { workspace = true }
mysql_async    = { version = "0.36", default-features = false, features = ["default-rustls-ring"] }
tokio-postgres = { version = "0.7", default-features = false, features = ["runtime"] }
rusqlite = { workspace = true }
toml = { workspace = true }
clap     = { workspace = true, optional = true }
colored  = { workspace = true, optional = true }

[lints]
workspace = true
