[package]
name = "proxmox"
version.workspace = true
edition.workspace = true

[lib]
name = "proxmox"
path = "src/lib.rs"

[features]
default = ["native"]
native = [
    "orca-contract/native",
    "dep:orca-db",
    "dep:anyhow",
    "dep:async-trait",
]
cli = [
    "native",
    "dep:clap",
]

[dependencies]
serde       = { workspace = true }
serde_json  = { workspace = true }
thiserror   = { workspace = true }
urlencoding = { workspace = true }
orca-utils  = { path = "../../utils" }

orca-dispatch        = { path = "../../orca-dispatch" }
orca-contract    = { path = "../../orca-contract", default-features = false }
orca-macro       = { path = "../../orca-macro" }
schemars         = { workspace = true }
inventory        = { workspace = true }

orca-db     = { package = "orca-db", path = "../../db", optional = true }
anyhow      = { workspace = true, optional = true }
async-trait = { workspace = true, optional = true }
clap        = { workspace = true, optional = true }

[dev-dependencies]
tokio    = { workspace = true }
wiremock = "0.6"

[lints]
workspace = true
