//! Typed Sonarr API client. Body is generated by progenitor at build time
//! from `sonarr.openapi.json` — see `build.rs`. Re-export the generated
//! `Client` and types so callers don't see the codegen module name.

#![allow(
    clippy::all,
    dead_code,
    unused_imports,
    unused_variables,
    non_snake_case
)]

include!(concat!(env!("OUT_DIR"), "/sonarr_codegen.rs"));
