[package]
name = "proxmox"
version.workspace = true
edition.workspace = true

[lib]
name = "proxmox"
path = "src/lib.rs"

[dependencies]
macro-runtime = { path = "../../macro-runtime" }
serde       = { workspace = true }
serde_json  = { workspace = true }
thiserror   = { workspace = true }
urlencoding = { workspace = true }
utils  = { path = "../../utils" }

dispatch        = { path = "../../dispatch" }
contract    = { path = "../../contract", default-features = false }
derive       = { path = "../../derive" }
schemars         = { workspace = true }
inventory        = { workspace = true }

db = { package = "db", path = "../../db" }
rusqlite    = { workspace = true }
plugin-toolkit = { path = "../../plugin-toolkit" }
anyhow = { workspace = true }
async-trait = { workspace = true }
clap        = { workspace = true }

[dev-dependencies]
tokio    = { workspace = true }
wiremock = "0.6"

[lints]
workspace = true
