[package]
name = "ntfy"
version.workspace = true
edition.workspace = true

[lib]
name = "ntfy"
path = "src/lib.rs"

[dependencies]
serde       = { workspace = true }
thiserror   = { workspace = true }
urlencoding = { workspace = true }
orca-utils  = { path = "../../utils" }

[dev-dependencies]
tokio       = { workspace = true }
wiremock    = "0.6"

[lints]
workspace = true
