[package]
name = "unraid-generated"
version.workspace = true
edition.workspace = true

[lib]
name = "unraid_generated"
path = "src/lib.rs"

[dependencies]
serde         = { workspace = true }
serde_json    = { workspace = true }
graphql_client = { workspace = true }

[build-dependencies]
orca-plugin-toolkit-build = { path = "../orca-plugin-toolkit-build" }

[lints]
workspace = true
