[package]
name    = "orca-unraid"
version = "0.1.0"
edition.workspace = true

[lib]
name = "orca_unraid"
path = "src/lib.rs"

[dependencies]
orca-graphql = { path = "../../graphql" }
orca-http    = { path = "../../http" }
serde        = { workspace = true }
serde_json   = { workspace = true }
thiserror    = { workspace = true }

[dev-dependencies]
tokio    = { workspace = true }
wiremock = "0.6"
