//! Prowlarr orca plugin. Thin tool surface over the shared `arr` base library.
//!
//! Prowlarr is the indexer-manager of the *arr stack: it speaks `/api/v1`
//! (not `/api/v3` like sonarr/radarr/lidarr) and is the only flavor exposing
//! `/indexerstatus`. The [`arr::Flavor`] is fixed to `Prowlarr`, so the
//! endpoint row carries no `flavor` column.
//!
//! Tool surface (one-tool-per-resource):
//!
//! - `prowlarr.{list, detail, create, update, delete}` — endpoint registry
//!   CRUD, generated by `endpoint_resource!` from the toolkit.
//! - `prowlarr.health` — **detection.** Health issues from `/api/v1/health`.
//! - `prowlarr.indexers` — configured indexers from `/api/v1/indexer`.
//! - `prowlarr.indexer_status` — per-indexer backoff from `/api/v1/indexerstatus`.
//! - `prowlarr.test_indexers` — **remediation.** Re-test every indexer.
//! - `prowlarr.system_status` — app name / version / instance.
//!
//! Endpoint resolution: tools accept the endpoint *name* and load
//! `(base_url, api_key)` from the toolkit-generated `endpoint_db` at call time.
//! Per [[project-colocated-api-clients]] + model B (any creds-holder may
//! execute), the row syncs to every paired peer.
//!
//! Imports flow through `plugin_toolkit::prelude::*` only — the plugin treats
//! the toolkit as the single gateway to the orca system.
#![allow(clippy::disallowed_types)]

use plugin_toolkit::prelude::*;

use arr::{
    Client, Config, Flavor, HealthIssue, Indexer, IndexerStatus, IndexerTestResult, SystemStatus,
};

// ═══════════════════════════════════════════════════════════════════════════
// prowlarr.{list,detail,create,update,delete} — endpoint registry CRUD.
// One declaration → five tools, three transports each, schema fragment, db
// helpers, row struct, args/output types. Power scales with the macro.
// ═══════════════════════════════════════════════════════════════════════════

#[endpoint_resource(plugin = "prowlarr")]
pub struct ProwlarrEndpoint {
    pub name: String,
    #[secret]
    pub api_key: String,
}

// ── HTTP client helper ──────────────────────────────────────────────────────

/// Resolve a registered Prowlarr endpoint to a live [`Client`], picking the
/// first reachable address from the endpoint's fallback list.
async fn make_client(name: &str) -> Result<Client> {
    let row = {
        let conn = runtime::open_db()?;
        endpoint_db::get(&conn, name)?
            .with_context(|| format!("prowlarr endpoint '{name}' not registered"))?
    };
    if !row.enabled {
        bail!("prowlarr endpoint '{name}' is disabled");
    }
    let base_url = address::resolve_reachable(name, &row.addresses).await?;
    Ok(Client::new(Config::new(
        base_url,
        row.api_key,
        Flavor::Prowlarr,
    )))
}

// ═══════════════════════════════════════════════════════════════════════════
// prowlarr.health — DETECTION
// ═══════════════════════════════════════════════════════════════════════════

#[derive(clap::Args, Serialize, Deserialize, JsonSchema)]
pub struct ProwlarrHealthArgs {
    /// Registered endpoint name.
    pub endpoint: String,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct ProwlarrHealthOutput {
    /// Total health issues raised.
    pub issue_count: usize,
    /// Health issues from `/health`.
    pub issues: Vec<HealthIssue>,
}

/// **Detection.** Health issues currently raised by a registered Prowlarr server.
#[orca_tool(domain = "prowlarr", verb = "health")]
async fn prowlarr_health(args: ProwlarrHealthArgs, _ctx: &ToolCtx) -> Result<ProwlarrHealthOutput> {
    let issues = arr::ops::health(&make_client(&args.endpoint).await?).await?;
    Ok(ProwlarrHealthOutput {
        issue_count: issues.len(),
        issues,
    })
}

// ═══════════════════════════════════════════════════════════════════════════
// prowlarr.indexers — configured indexers
// ═══════════════════════════════════════════════════════════════════════════

#[derive(clap::Args, Serialize, Deserialize, JsonSchema)]
pub struct ProwlarrIndexersArgs {
    /// Registered endpoint name.
    pub endpoint: String,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct ProwlarrIndexersOutput {
    /// Configured indexers from `/indexer`.
    pub indexers: Vec<Indexer>,
}

/// Configured indexers on a registered Prowlarr server.
#[orca_tool(domain = "prowlarr", verb = "indexers")]
async fn prowlarr_indexers(
    args: ProwlarrIndexersArgs,
    _ctx: &ToolCtx,
) -> Result<ProwlarrIndexersOutput> {
    let indexers = arr::ops::indexers(&make_client(&args.endpoint).await?).await?;
    Ok(ProwlarrIndexersOutput { indexers })
}

// ═══════════════════════════════════════════════════════════════════════════
// prowlarr.indexer_status — per-indexer backoff (prowlarr-only endpoint)
// ═══════════════════════════════════════════════════════════════════════════

#[derive(clap::Args, Serialize, Deserialize, JsonSchema)]
pub struct ProwlarrIndexerStatusArgs {
    /// Registered endpoint name.
    pub endpoint: String,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct ProwlarrIndexerStatusOutput {
    /// Per-indexer backoff status from `/indexerstatus` — rows present only for
    /// indexers currently backed off.
    pub status: Vec<IndexerStatus>,
}

/// Per-indexer backoff status from Prowlarr's `/indexerstatus`. Rows appear
/// only for indexers Prowlarr has temporarily disabled after failures.
#[orca_tool(domain = "prowlarr", verb = "indexer_status")]
async fn prowlarr_indexer_status(
    args: ProwlarrIndexerStatusArgs,
    _ctx: &ToolCtx,
) -> Result<ProwlarrIndexerStatusOutput> {
    let status = arr::ops::indexer_status(&make_client(&args.endpoint).await?).await?;
    Ok(ProwlarrIndexerStatusOutput { status })
}

// ═══════════════════════════════════════════════════════════════════════════
// prowlarr.test_indexers — REMEDIATION
// ═══════════════════════════════════════════════════════════════════════════

#[derive(clap::Args, Serialize, Deserialize, JsonSchema)]
pub struct ProwlarrTestIndexersArgs {
    /// Registered endpoint name.
    pub endpoint: String,
}

#[derive(Serialize, Deserialize, JsonSchema)]
pub struct ProwlarrTestIndexersOutput {
    /// Indexers tested.
    pub tested_count: usize,
    /// Indexers that passed.
    pub valid_count: usize,
    /// Per-indexer result.
    pub results: Vec<IndexerTestResult>,
}

/// **Remediation.** Re-test every indexer on a registered Prowlarr server,
/// clearing stale backoff so recovered indexers are used again immediately.
#[orca_tool(domain = "prowlarr", verb = "test_indexers")]
async fn prowlarr_test_indexers(
    args: ProwlarrTestIndexersArgs,
    _ctx: &ToolCtx,
) -> Result<ProwlarrTestIndexersOutput> {
    let results = arr::ops::test_indexers(&make_client(&args.endpoint).await?).await?;
    let valid_count = results
        .iter()
        .filter(|r| r.is_valid.unwrap_or(false))
        .count();
    Ok(ProwlarrTestIndexersOutput {
        tested_count: results.len(),
        valid_count,
        results,
    })
}

// ═══════════════════════════════════════════════════════════════════════════
// prowlarr.system_status — app name + version
// ═══════════════════════════════════════════════════════════════════════════

#[derive(clap::Args, Serialize, Deserialize, JsonSchema)]
pub struct ProwlarrSystemStatusArgs {
    /// Registered endpoint name.
    pub endpoint: String,
}

/// App name, version, and instance name from `/system/status`.
#[orca_tool(domain = "prowlarr", verb = "system_status")]
async fn prowlarr_system_status(
    args: ProwlarrSystemStatusArgs,
    _ctx: &ToolCtx,
) -> Result<SystemStatus> {
    Ok(arr::ops::system_status(&make_client(&args.endpoint).await?).await?)
}

// TODO: prowlarr.add_indexer — add an indexer over `/api/v1/indexer`.
// TODO: prowlarr.sync_apps — push indexers to linked sonarr/radarr/lidarr apps
//       over `/api/v1/applications`.
