[package]
name = "llm"
version.workspace = true
edition.workspace = true

[lib]
name = "llm"
path = "src/lib.rs"

[dependencies]
contract = { path = "../contract" }
utils    = { path = "../utils" }
db            = { package = "db", path = "../db" }

anyhow       = { workspace = true }
async-trait  = { workspace = true }
colored      = { workspace = true }
futures-util = { workspace = true }
reqwest      = { workspace = true }
rustls       = { workspace = true }
serde        = { workspace = true }
serde_json   = { workspace = true }
tokio        = { workspace = true }
tokio-util   = { workspace = true }
tracing      = { workspace = true }
uuid         = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
