[package]
name = "docker"
version.workspace = true
edition.workspace = true

[lib]
name = "docker"
path = "src/lib.rs"

[features]
default = []
native = [
    "orca-tool/native",
    "orca-contract/native",
    "dep:orca-db",
    "dep:async-trait",
]
cli = [
    "native",
    "orca-tool/cli",
    "dep:clap",
]

[dependencies]
anyhow      = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
thiserror   = { workspace = true }
tokio       = { workspace = true }

orca-tool        = { path = "../../orca-tool", default-features = false }
orca-contract    = { path = "../../orca-contract", default-features = false }
orca-macro       = { path = "../../orca-macro" }
schemars         = { workspace = true }
inventory        = { workspace = true }

orca-db     = { package = "orca-db", path = "../../db", optional = true }
async-trait = { workspace = true, optional = true }
clap        = { workspace = true, optional = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
