[package]
name = "docker"
version.workspace = true
edition.workspace = true

[lib]
name = "docker"
path = "src/lib.rs"

[features]
cli = [
    "dep:clap",
]
[dependencies]
anyhow      = { workspace = true }
serde       = { workspace = true }
serde_json  = { workspace = true }
thiserror   = { workspace = true }
tokio       = { workspace = true }

orca-dispatch        = { path = "../../orca-dispatch" }
orca-contract    = { path = "../../orca-contract", default-features = false }
orca-macro       = { path = "../../orca-macro" }
schemars         = { workspace = true }
inventory        = { workspace = true }

orca-db = { package = "orca-db", path = "../../db" }
async-trait = { workspace = true }
clap        = { workspace = true, optional = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
